# ──────────────────────────────────────────────────────────────────────────────
# config.py — USER-MANAGED hyperparameters & runtime settings
# ──────────────────────────────────────────────────────────────────────────────
# This file is **NOT** auto-generated. It is safe to edit by hand.
#
# The auto-generated system prompts and schema constants live in
# ``agent/prompts.py`` (regenerated by ``python -m schema.gen_system_prompt``
# from the live Neo4j schema).
# Keeping the two files separate prevents ``setup_project.py`` from
# overwriting the LLM configuration / pipeline knobs every time the schema
# is re-derived.
#
# Layout
# ──────
#   1. LLM configuration (per pipeline stage)
#   2. Runtime constants (sampling, validation, threading)
#   3. NER pipeline mode
# ──────────────────────────────────────────────────────────────────────────────

import os
from dataclasses import dataclass
from typing import Optional

# ──────────────────────────────────────────────────────────────────────────────
# LLM configuration  (per pipeline stage)
# ──────────────────────────────────────────────────────────────────────────────
# Each pipeline stage has its own LLM "slot" so experiments can mix providers
# (e.g. GPT for NER, Claude Opus for Cypher generation) without code changes.
#
# Schema for every entry:
#   {
#     "provider":    "openai" | "azure" | "anthropic" | "hf_compatible" | "auto",
#     "model":       <model-name | deployment | MODEL_REGISTRY key>,
#     "temperature": <float>,         # optional, default 0
#     # Anything else (max_tokens, top_p, …) is forwarded verbatim to the
#     # chat-model constructor.
#   }
#
# When ``provider == "hf_compatible"`` the ``model`` field is interpreted as
# a key into ``MODEL_REGISTRY`` (see below).  The factory looks the key up to
# get the actual base_url / api_key / model id that should be sent to the
# OpenAI-compatible server.
#
# ``agent_helper.build_llm(**LLM_CONFIG)`` consumes these dicts and returns a
# concrete ``BaseChatModel`` — see ``agent_helper.ner_llm`` / ``qa_llm`` /
# ``cypher_llm`` for the resolved singletons.
#
# Examples
# --------
#   NER_LLM_CONFIG    = {"provider": "openai",        "model": "gpt-4.1"}
#   CYPHER_LLM_CONFIG = {"provider": "anthropic",     "model": "claude-opus-4-20250514"}
#   QA_LLM_CONFIG     = {"provider": "openai",        "model": "gpt-4o-mini"}
#   NER_LLM_CONFIG    = {"provider": "hf_compatible", "model": "llama-8b-hf"}
# ──────────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────────
# MODEL_REGISTRY — open-source / fine-tuned model endpoints
# ──────────────────────────────────────────────────────────────────────────────
# Every entry describes a single OpenAI-compatible HTTP endpoint.  The factory
# in ``agent_helper`` instantiates an ``openai``-SDK-compatible chat client
# (LangChain's ``ChatOpenAI`` is just a thin wrapper around the openai SDK)
# pointed at ``base_url`` with credentials from ``os.environ[api_key_env]`` and
# uses ``model`` as the value to send in the request body's ``model`` field.
#
# ── Why a single ``hf_compatible`` provider for all of these? ────────────────
# The Hugging Face serverless router, HF Inference Endpoints, Groq, Together,
# Fireworks, Anyscale, etc. ALL expose an OpenAI-compatible
# ``/v1/chat/completions`` endpoint.  That means the same openai SDK works for
# every one of them — only ``base_url``, ``api_key``, and ``model`` change.
# We funnel them through one provider name and let the registry encode the
# differences.
#
# ── HF Inference Endpoints + TGI ─────────────────────────────────────────────
# HF Inference Endpoints use TGI (Text Generation Inference) as the default
# inference engine.  TGI exposes an OpenAI-compatible
# ``/v1/chat/completions`` endpoint, which is why we can use the openai SDK
# to call it.  For HF Inference Endpoint registry entries:
#
#   * ``base_url`` is the *unique* endpoint URL HF gives you per-deployment.
#     The URL itself identifies which model is being served.
#   * ``model`` should be set to the literal string ``"tgi"``.  The OpenAI
#     request schema requires a ``model`` field, but TGI ignores it because
#     the URL already pins the model — convention is to fill it with "tgi".
#
# Recommendation: when deploying your own fine-tuned models, use HF Inference
# Endpoints with TGI.  You get a stable URL, an OpenAI-compatible API, and
# zero engine-config work — just push the merged model to the Hub and click
# "Deploy ▸ Inference Endpoints".
#
# ── HF serverless router ─────────────────────────────────────────────────────
# For ``https://router.huggingface.co/v1`` the ``model`` field must be the
# full HF Hub repo id (e.g. ``meta-llama/Llama-3.1-8B-Instruct``), NOT
# ``"tgi"``.  The router uses ``model`` to route between many models behind
# one URL.
#
# ── Other OpenAI-compatible providers ────────────────────────────────────────
# For Groq, Together, Fireworks, etc. use whatever model id the provider
# documents (e.g. Groq's ``llama-3.1-8b-instant``).
#
# ── Adding a new fine-tuned model ────────────────────────────────────────────
# 1. Deploy the merged model to an HF Inference Endpoint.
# 2. Add a new entry below: a unique key, the endpoint URL as ``base_url``,
#    ``"HUGGINGFACE_TOKEN"`` for ``api_key_env`` (this is the variable name
#    used by .env / .env.example in this repo — point it at whatever env var
#    actually holds the HF token), and ``"tgi"`` for ``model``.
# 3. Reference the new key from any of NER_LLM_CONFIG / QA_LLM_CONFIG /
#    CYPHER_LLM_CONFIG (with ``provider="hf_compatible"``).
# ──────────────────────────────────────────────────────────────────────────────

MODEL_REGISTRY: dict = {
    # ── HF serverless router (multiplexes many open-source models) ──────────
    # ``model`` must be the full HF Hub repo id; the router uses it to pick
    # which backend to forward the request to.
    "llama-8b-hf": {
        "base_url":    "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "meta-llama/Llama-3.1-8B-Instruct",
    },
    "qwen-7b-hf": {
        "base_url":    "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "Qwen/Qwen2.5-7B-Instruct",
    },

    # ── Groq (other OpenAI-compatible provider, kept for flexibility) ───────
    # Use Groq's documented model id (NOT a HF Hub repo id, NOT "tgi").
    "llama-8b-groq": {
        "base_url":    "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "model":       "llama-3.1-8b-instant",
    },

    # ── Dedicated HF Inference Endpoint (per fine-tuned model) ──────────────
    # Each fine-tuned model gets its own URL.  The URL pins the model, so
    # ``model`` is just ``"tgi"`` (TGI ignores the field but the OpenAI
    # request schema requires it).  Replace the placeholder URL below with
    # the real endpoint URL after deploying.
    "my-svl-cypher-lora-v1": {
        "base_url":    "https://abc123.us-east-1.aws.endpoints.huggingface.cloud/v1/",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "tgi",  # TGI: URL identifies the model, "tgi" is a placeholder
    },
    # Add more fine-tuned model endpoints here as you deploy them.
    # "my-ner-lora-v2": {
    #     "base_url":    "https://xyz789.us-east-1.aws.endpoints.huggingface.cloud/v1/",
    #     "api_key_env": "HUGGINGFACE_TOKEN",
    #     "model":       "tgi",
    # },

    "qwen-coder-7b-hf": {
        "base_url": "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model": "Qwen/Qwen2.5-Coder-7B-Instruct",
    },
    "qwen-coder-32b-hf": {
        "base_url": "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
    },
    "qwen-coder-32b-groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "model": "qwen-2.5-coder-32b",
    },

    # ── DeepInfra (OpenAI-compatible; one key serves both open-weights models
    #    of the generator sweep — see MODEL_PRESETS) ─────────────────────────
    "deepseek-v3.1-deepinfra": {
        "base_url":    "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "model":       "deepseek-ai/DeepSeek-V3.1",
    },
    "qwen3-32b-deepinfra": {
        # Hybrid thinking model: the preset passes chat_template_kwargs.enable_thinking=false
        # (vLLM convention on DeepInfra) so it runs as a plain text model. If the endpoint
        # rejects that field, switch to the non-thinking checkpoint
        # "Qwen/Qwen3-30B-A3B-Instruct-2507" and drop the params. Id/price unverified until
        # the first smoke test (registered without network access).
        "base_url":    "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "model":       "Qwen/Qwen3-32B",
    },
    "llama-3.3-70b-deepinfra": {
        "base_url":    "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "model":       "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    },
    # ── Together (alternate host for the same two models) ────────────────────
    "deepseek-v3.1-together": {
        "base_url":    "https://api.together.xyz/v1",
        "api_key_env": "TOGETHER_API_KEY",
        "model":       "deepseek-ai/DeepSeek-V3.1",
    },
    "llama-3.3-70b-together": {
        "base_url":    "https://api.together.xyz/v1",
        "api_key_env": "TOGETHER_API_KEY",
        "model":       "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    },
}


# NER_LLM_CONFIG: dict = {
#     "provider":    "anthropic",
#     "model":       "claude-opus-4-7",
#     "temperature": 0,
# }

# NER_LLM_CONFIG: dict = {
#     "provider":    "anthropic",
#     "model":       "claude-sonnet-4-5",
#     "temperature": 0,
# }

# ── Generator LLM: presets + the eval receiver ───────────────────────────────
# One name selects the generator LLM for all three stages (NER / Cypher / QA).
# Edit it in eval_config.py (``GENERATOR_LLM = "gpt-5.6-terra"``) — the control
# panel — never here and never in .env, which holds API keys only. eval_run
# injects the chosen name into the worker as the GENERATOR_LLM env var, the
# same way it passes METHOD; the name is also what appears in the run
# directory (``cyanchor_fl@gpt-5.6-terra``), so a sweep never mixes models.
#
# provider "openai" / "anthropic" call the vendor directly; "hf_compatible"
# routes through an OpenAI-compatible endpoint described in MODEL_REGISTRY.
# An optional "params" dict is passed to the chat-model constructor verbatim
# (e.g. {"reasoning_effort": "medium"}); the builders already choose safe
# defaults per model family, so most presets need none.
MODEL_PRESETS: dict = {
    # ── the gpt-4.1 baseline every existing run was made with ──
    "gpt-4.1":          {"provider": "openai",        "model": "gpt-4.1"},
    # ── GPT family ──
    "gpt-5.6-terra":    {"provider": "openai",        "model": "gpt-5.6-terra"},   # workhorse (primary)
    "gpt-5.6-luna":     {"provider": "openai",        "model": "gpt-5.6-luna"},    # cheap tier / smoke tests
    # ── Claude family (temperature is rejected and thinking is switched off
    #    for the 4.6+/5 generation — see agent_helper._anthropic_generation_kwargs) ──
    "claude-sonnet-5":  {"provider": "anthropic",     "model": "claude-sonnet-5"},   # sweep: Claude strong tier
    "claude-opus-5":    {"provider": "anthropic",     "model": "claude-opus-5"},     # extra — not in the sweep (~2.5x Sonnet)
    "claude-haiku-4.5": {"provider": "anthropic",     "model": "claude-haiku-4-5"},
    # ── open-weights, served by DeepInfra (one key for both; Together entries
    #    exist in MODEL_REGISTRY as alternates) ──
    "deepseek-v3.1":    {"provider": "hf_compatible", "model": "deepseek-v3.1-deepinfra"},
    "llama-3.3-70b":    {"provider": "hf_compatible", "model": "llama-3.3-70b-deepinfra"},
    "qwen3-32b":        {"provider": "hf_compatible", "model": "qwen3-32b-deepinfra",     # open-weights small tier
                         "params": {"extra_body": {"chat_template_kwargs": {"enable_thinking": False}}}},
}

# ⚙ eval receiver — edit GENERATOR_LLM in the eval_config panel, not here.
GENERATOR_LLM = os.getenv("GENERATOR_LLM") or None


def resolve_preset(name: str) -> dict:
    """Preset name -> ``{"provider", "model"}``. Unknown names fail loudly with
    the list of valid ones; a silent fallback here would put the wrong model
    behind a directory that claims another."""
    if name in MODEL_PRESETS:
        return dict(MODEL_PRESETS[name])
    raise KeyError(f"GENERATOR_LLM={name!r} is not a preset. Known presets: "
                   + ", ".join(sorted(MODEL_PRESETS)))


def _apply_llm_override(cfg: dict) -> dict:
    """Overlay the selected preset onto one stage config (no-op when unset).
    A preset's optional ``"params"`` (e.g. ``{"reasoning_effort": "low"}``) are
    flattened in and reach the chat-model constructor as keyword arguments."""
    if not GENERATOR_LLM:
        return cfg
    spec = resolve_preset(GENERATOR_LLM)
    params = spec.pop("params", None) or {}
    return {**cfg, **spec, **params}


NER_LLM_CONFIG: dict = {
   "provider":    "openai",
   "model":       "gpt-4.1",
   "temperature": 0,
}

# NER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "llama-8b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }


QA_LLM_CONFIG: dict = {
    "provider":    "openai",
    "model":       "gpt-4.1",
    "temperature": 0,
}



# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "qwen-coder-32b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
# }


CYPHER_LLM_CONFIG: dict = {
   "provider":    "openai",
   "model":       "gpt-4.1",
   "temperature": 0,
}

# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "llama-8b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }

# Example: route the Cypher generator at an open-source / fine-tuned model
# served behind an OpenAI-compatible endpoint (HF router, HF Inference
# Endpoint, Groq, etc.).  The ``model`` field is a key into MODEL_REGISTRY.
# Uncomment to switch — no other code change needed.
#
# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "my-svl-cypher-lora-v1",   # ← MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }

# ── Apply the generator-LLM sweep override ───────────────────────────────────
# Must run before anything is *derived* from a stage config (DEFAULT_LLM_CONFIG
# below): a value copied out earlier would keep the pre-override model, and the
# stage built from it would silently run a different generator than the one the
# run directory is named for.
NER_LLM_CONFIG    = _apply_llm_override(NER_LLM_CONFIG)
QA_LLM_CONFIG     = _apply_llm_override(QA_LLM_CONFIG)
CYPHER_LLM_CONFIG = _apply_llm_override(CYPHER_LLM_CONFIG)

# Legacy default — used by any code path that imports ``agent_helper.llm``
# without specifying a stage (the entity-extraction tool inside the NER agent
# goes through it).  Same setup as NER, *after* the override.
DEFAULT_LLM_CONFIG: dict = dict(NER_LLM_CONFIG)


# ──────────────────────────────────────────────────────────────────────────────
# Runtime constants
# ──────────────────────────────────────────────────────────────────────────────

MAX_THREAD            = 5    # parallel tool calls in the NER agent
# DEFAULT_TOP_K: how many tools the FAISS tool-selector returns per question.
#
# Bumped from 10 → 15 because the partial-name probe showed that on the
# movie graph, top-10 systematically excluded Person tools when the
# question used relational verbs ("feature X in cast", "starring Y",
# "directed by Z"). The eight movie/film-series/award tools dominated the
# top half of the ranking and Person.name fell to ~#11, so the ReAct
# agent never even saw it and resorted to calling `get_movie_eid("Elijah
# Wood")` — a wrong-label tool with predictable empty results. 15 leaves
# slack for the agent to discover the right tool without inflating
# token usage materially.
DEFAULT_TOP_K         = 15   # FAISS tool-selection top-k
TOOL_TOP_K            = 10   # fulltext search top-k per tool call


# ──────────────────────────────────────────────────────────────────────────────
# Method selection — ONE axis names the method directly
# ──────────────────────────────────────────────────────────────────────────────
# METHOD picks the whole pipeline. Five peer methods:
#   no_val_link — feed only {schema}+{question} to the Cypher LLM (lower bound).
#   fcav        — retrieve-then-generate RAG baseline (fcav.py; needs setup_fcav.py).
#   react       — ReAct NER-agent grounder (baseline). Retrieval fixed = fuzzy.
#   graphrag    — Multi-Agent GraphRAG baseline (graphrag.py): generate→execute→
#                 evaluate→repair loop.
#   cyanchor    — OUR method (plan-and-execute grounder; the code internally still
#                 lives in plan_exec.py). Its retrieval is ablatable via the three
#                 RETRIEVAL_* switches below.
#
# RETRIEVAL_* — CyANCHOR's retrieval arms, independently toggleable (≥1 must be on).
# Baselines keep their own FIXED retrieval (react = fuzzy) and IGNORE these switches.
#   RETRIEVAL_FUZZY        BM25 / Lucene full-text        (default on)
#   RETRIEVAL_VECTOR       in-graph embedding kNN          (default off — needs embeddings)
#   RETRIEVAL_LEVENSHTEIN  APOC normalized edit-distance   (default on)
#
# TOOL_TYPE — react/cyanchor tool scope: node | node_rel.
#
# Examples:
#   METHOD=cyanchor RETRIEVAL_VECTOR=1 python eval_run.py     # CyANCHOR, all 3 arms
#   METHOD=cyanchor RETRIEVAL_VECTOR=0 python eval_run.py     # CyANCHOR, fuzzy+lev
#   METHOD=graphrag python eval_run.py                        # baseline
# Back-compat: the legacy VAL_LINK_MODE / AGENT_TYPE / RETRIEVAL_TYPE still work
# (val_link+plan_exec → cyanchor, val_link+react → react, hybrid → +vector).
# ──────────────────────────────────────────────────────────────────────────────
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ ⚙ THE EXPERIMENT KNOBS BELOW ARE RECEIVERS — edit them in eval_config.      │
# │   Every `os.getenv("X", <literal>)` experiment knob in this file (METHOD,   │
# │   TOOL_TYPE, RETRIEVAL_*, PLAN_EXEC_*, CYPHER_*, GRAPHRAG_*) is read from    │
# │   an env var that eval_run injects from the eval_config control panel.       │
# │   To change what an EVAL run does, edit the ★ EXPERIMENT PARAMETERS ★ panel  │
# │   in eval_config.py — NOT the literal here. The literal is only the fallback │
# │   for the bare `ner_agent_auto.py` demo/CLI (a shell env var may override    │
# │   it there, which is a CLI convenience). Do not treat it as a 2nd knob.      │
# └──────────────────────────────────────────────────────────────────────────┘
METHOD:    str = os.getenv("METHOD", os.getenv("VAL_LINK_MODE", "cyanchor")).strip().lower()
TOOL_TYPE: str = os.getenv("TOOL_TYPE", "node_rel").strip().lower()
RETRIEVAL_FUZZY       = os.getenv("RETRIEVAL_FUZZY",       "1").lower() in ("1", "true", "yes")
RETRIEVAL_VECTOR      = os.getenv("RETRIEVAL_VECTOR",      "0").lower() in ("1", "true", "yes")
RETRIEVAL_LEVENSHTEIN = os.getenv("RETRIEVAL_LEVENSHTEIN", "1").lower() in ("1", "true", "yes")

_METHODS    = ("no_val_link", "fcav", "react", "graphrag", "cyanchor")
_TOOL_TYPES = ("node", "node_rel")


@dataclass(frozen=True)
class GroundingSpec:
    """Resolved method configuration. ``tool`` applies to react/cyanchor; the arm
    flags (``fuzzy``/``vector``/``lev``) apply to cyanchor only."""
    method: str
    tool:   Optional[str] = None
    fuzzy:  bool = True
    vector: bool = False
    lev:    bool = False

    @property
    def canonical(self) -> str:
        """Internal flat name the pipeline keys on. NOTE: no_val_link maps to the
        legacy ``"no_ner"`` sentinel and react to ``"react_<suffix>"`` because those
        strings are load-bearing (dispatch checks + FAISS index dirs). cyanchor gets
        its own ``"cyanchor_<arms>_<suffix>"`` (arms = f/v/l)."""
        if self.method == "no_val_link":
            return "no_ner"
        if self.method in ("fcav", "graphrag"):
            return self.method
        suffix = "node_only" if self.tool == "node" else "node_rel"
        if self.method == "react":
            return f"react_{suffix}"
        arms = "".join(a for a, on in (("f", self.fuzzy), ("v", self.vector), ("l", self.lev)) if on) or "none"
        return f"cyanchor_{arms}_{suffix}"

    @property
    def retrieval(self) -> Optional[str]:
        """The retrieval mechanism this method actually uses.

        The arm flags are cyanchor-only; the baselines each have their own FIXED
        retrieval and never read them. Deriving this string from the raw flags
        would report the dataclass default (``fuzzy=True``) for fcav/graphrag,
        which is simply wrong — hence the explicit per-method mapping."""
        if self.method == "no_val_link":
            return None                      # grounding bypassed entirely
        if self.method == "fcav":
            return "vector"                  # FAISS over embedded values
        if self.method == "graphrag":
            return "norm-Lev"                # APOC levenshteinSimilarity scan
        if self.method == "react":
            return "fuzzy"                   # fixed BM25/Lucene
        return "+".join(a for a, on in (("fuzzy", self.fuzzy), ("vector", self.vector),
                                        ("lev", self.lev)) if on) or None

    @property
    def label(self) -> str:
        """Human-readable name for eval records / reports."""
        if self.method == "no_val_link":
            return "No Val Link"
        if self.method == "fcav":
            return "FCAV"
        if self.method == "graphrag":
            return "GraphRAG"
        tl = "Node" if self.tool == "node" else "Node + Rel"
        if self.method == "react":
            return f"ReAct ({tl})"
        arms = "+".join(a for a, on in (("fuzzy", self.fuzzy), ("vector", self.vector), ("lev", self.lev)) if on)
        return f"CyANCHOR [{arms}] ({tl})"


def _spec_from_env() -> GroundingSpec:
    m = METHOD
    # ── Back-compat with the old four-axis scheme ────────────────────────────
    if m == "val_link":
        ag = os.getenv("AGENT_TYPE", "plan_exec").strip().lower()
        m = "cyanchor" if ag in ("plan_exec", "cyanchor") else "react"
    elif m == "plan_exec":
        m = "cyanchor"
    if m not in _METHODS:
        raise ValueError(f"METHOD must be one of {_METHODS}, got {METHOD!r}.")
    if m in ("no_val_link", "fcav", "graphrag"):
        return GroundingSpec(m)
    tool = TOOL_TYPE if TOOL_TYPE in _TOOL_TYPES else "node_rel"
    if m == "react":
        return GroundingSpec("react", tool=tool)
    # cyanchor: read the three retrieval arms (legacy RETRIEVAL_TYPE=hybrid → +vector)
    fuzzy, vector, lev = RETRIEVAL_FUZZY, RETRIEVAL_VECTOR, RETRIEVAL_LEVENSHTEIN
    if os.getenv("RETRIEVAL_TYPE", "").strip().lower() == "hybrid":
        vector = True
    if not (fuzzy or vector or lev):
        raise ValueError("CyANCHOR needs at least one RETRIEVAL_* arm enabled.")
    return GroundingSpec("cyanchor", tool=tool, fuzzy=fuzzy, vector=vector, lev=lev)


def _spec_from_canonical(name: str) -> GroundingSpec:
    """Parse a canonical internal name back into a spec. Used by internal callers
    that thread the flat string (e.g. per-mode FAISS index selection)."""
    n = (name or "").strip().lower()
    if n in ("", "no_ner", "no_val_link"):
        return GroundingSpec("no_val_link")
    if n in ("fcav", "graphrag"):
        return GroundingSpec(n)
    if n.startswith("react_"):
        suf = n[len("react_"):]
        return GroundingSpec("react", tool="node" if suf == "node_only" else "node_rel")
    if n.startswith("cyanchor_") or n.startswith("plan_exec_"):
        rest = n.split("_", 1)[1] if n.startswith("cyanchor_") else n[len("plan_exec_"):]
        hybrid = rest.endswith("_hybrid")          # legacy plan_exec_..._hybrid
        rest = rest[: -len("_hybrid")] if hybrid else rest
        for suf in ("node_only", "node_rel"):
            if rest.endswith(suf):
                tool = "node" if suf == "node_only" else "node_rel"
                arms = rest[: -(len(suf) + 1)]      # leading f/v/l, or "" for legacy
                if n.startswith("plan_exec_"):      # legacy: fuzzy + (vector if hybrid)
                    return GroundingSpec("cyanchor", tool=tool, fuzzy=True, vector=hybrid, lev=False)
                return GroundingSpec("cyanchor", tool=tool,
                                     fuzzy="f" in arms, vector="v" in arms, lev="l" in arms)
    raise ValueError(f"Unknown grounding mode {name!r}.")


def resolve_spec(mode=None) -> GroundingSpec:
    """Resolve the active :class:`GroundingSpec`.

    *mode* may be a :class:`GroundingSpec` (returned as-is), a canonical internal
    name string (parsed — internal callers), or ``None`` (read from METHOD + the
    RETRIEVAL_*/TOOL_TYPE env vars — the user-facing entry point)."""
    if isinstance(mode, GroundingSpec):
        return mode
    if mode:
        return _spec_from_canonical(mode)
    return _spec_from_env()

# RAG baseline: the ReAct NER agent restricted to a SINGLE tool-call round and
# with the tool-result backfill DISABLED. It uses the same (node + relation)
# tool set as `full`, but the agent gets one think→act→observe cycle and must
# then answer — no iterative refinement, no safety net. This isolates "what one
# retrieval round of an LLM agent recovers" as a lower-effort baseline against
# the full agentic `full` / `node_only` modes (which loop + backfill).
# RAG_RECURSION_LIMIT caps the LangGraph supersteps: agent → tools → agent ≈ 3.
RAG_RECURSION_LIMIT = 1

# plan_exec baseline: a deterministic plan-and-execute grounder (no ReAct loop).
#   PLAN     — one LLM call decomposes the question into entity mentions, each
#              tagged node|relation + a short type descriptor.
#   EXECUTE  — per mention: route to the matching tool via the tool-VectorDB
#              (by descriptor), then search_tool(mention) for the top-K
#              canonical values (node mentions) / emit the relationship pattern
#              (relation mentions). No per-tool get_entity re-extraction.
#   GENERATE — the per-mention candidate lists are handed verbatim to the
#              Cypher LLM, which does the value-linking while writing Cypher.
# Contrasts with `full`: per-entity tool routing (no top-k tool crowding), no
# get_entity intermediate layer, and candidates (not a single forced pick) are
# given to the generator. Retrieval stays fuzzy (no value-embedding index).
PLAN_EXEC_TOOLS_PER_ENTITY = int(os.getenv("PLAN_EXEC_TOOLS_PER_ENTITY", "2"))    # tools routed per extracted mention
PLAN_EXEC_VALUES_PER_TOOL  = int(os.getenv("PLAN_EXEC_VALUES_PER_TOOL", "10"))   # top-K canonical values searched per tool (fuzzy modes)

# plan_exec_node_rel_hybrid: per tool, union fuzzy top-K with vector top-K
# candidates (fuzzy first, vector fills the tail). Tests whether in-graph
# embedding recall recovers the alias/abbrev cases fuzzy misses.
PLAN_EXEC_HYBRID_FUZZY_K  = 10    # fuzzy candidates per tool
PLAN_EXEC_HYBRID_VECTOR_K = 5     # embedding (vector-index) candidates per tool

# plan_exec corrective-retrieval escalation (orthogonal to fuzzy/hybrid):
# after the initial retrieval, an LLM judge checks whether the entity mention
# is actually grounded in the candidates retrieved so far. If not, retrieval is
# escalated with a diminishing budget — FIRST deeper into the already-used
# tool(s) (the canonical value may rank below the initial top-K), THEN to the
# next-ranked tools — re-judging after each step and stopping once grounded or
# the budget is spent. Only fires on a miss, so well-grounded entities pay just
# one judge call and no extra retrieval (avoids the candidate-noise penalty of
# blanket top-K increases).
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
PLAN_EXEC_ESCALATE        = os.getenv("PLAN_EXEC_ESCALATE", "1").lower() in ("1", "true", "yes")
PLAN_EXEC_MAX_ITER        = int(os.getenv("PLAN_EXEC_MAX_ITER", "3"))           # max escalation rounds per mention
PLAN_EXEC_ESCALATE_BUDGET = tuple(int(x) for x in os.getenv("PLAN_EXEC_ESCALATE_BUDGET", "5,3,1").split(","))   # values added per successive round (deepen step)
PLAN_EXEC_ROUTE_FETCH     = int(os.getenv("PLAN_EXEC_ROUTE_FETCH", "6"))           # tools FAISS-routed per mention (initial + escalation pool)
# In escalation the LLM judge picks the next action from: done | value (deepen
# the used field) | a specific Label.property field to ADD (chosen from the menu
# of available node fields). 'value' deepens fuzzy in the fuzzy mode and BOTH
# fuzzy+vector in hybrid. A newly chosen field gets a full initial-style fetch.

# ──────────────────────────────────────────────────────────────────────────────
# Multi-Agent GraphRAG baseline  (VAL_LINK_MODE=graphrag — see graphrag.py)
# ──────────────────────────────────────────────────────────────────────────────
# A self-correcting generate→execute→evaluate loop (NO pre-grounding stage):
#
#   GENERATE  — the Cypher LLM writes a query from {schema}+{question} (round 1
#               has no entity hints; later rounds get the aggregated feedback).
#   EXECUTE   — run the query; classify (error | empty | rows).
#   EVALUATE  — an LLM judge labels the outcome:
#                 accept                        → format & return the answer.
#                 incorrect|illogical|incomplete→ hand the semantic/logical
#                                                 feedback straight to GENERATE.
#                 error|empty                   → STRUCTURAL repair: extract the
#                   query's node labels, property–value pairs and relationship
#                   patterns, verify each against the DB, retrieve normalized-
#                   Levenshtein candidate replacements for the invalid values,
#                   aggregate execution+semantic+validation feedback, regenerate.
#   …iterate up to GRAPHRAG_MAX_ITER rounds, then return the best attempt.
#
# Generator reuses CYPHER_LLM_CONFIG; evaluator/selector reuse NER_LLM_CONFIG.
# Selection is purely env-driven, like the other baselines:
#   VAL_LINK_MODE=graphrag python eval_run.py
GRAPHRAG_MAX_ITER       = 4     # generate→execute→correct rounds (paper = 4)
GRAPHRAG_CANDIDATE_K    = 10    # Levenshtein candidates retrieved per invalid value
GRAPHRAG_LEV_THRESHOLD  = 0.0   # min normalized-Levenshtein sim to keep a candidate (0 = keep all)
# Candidate replacements are ranked by normalized Levenshtein over the (label,
# property) value set — server-side via APOC (apoc.text.levenshteinSimilarity);
# if APOC is unavailable we scan distinct values in Python, capped at this many.
GRAPHRAG_SCAN_CAP       = 50000
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
GRAPHRAG_EMPTY_IS_WRONG = os.getenv("GRAPHRAG_EMPTY_IS_WRONG", "1").lower() in ("1", "true", "yes")
GRAPHRAG_LLM_EVALUATOR  = os.getenv("GRAPHRAG_LLM_EVALUATOR", "1").lower() in ("1", "true", "yes")

# ──────────────────────────────────────────────────────────────────────────────
# Cypher execution-error retry  (applies to the val_link Cypher stage only)
# ──────────────────────────────────────────────────────────────────────────────
# After value-linking finishes and the Cypher LLM has written a query, if that
# query FAILS TO EXECUTE (syntax/runtime error), feed the Neo4j error message
# back to the Cypher LLM and have it rewrite the query — up to
# CYPHER_RETRY_MAX_ROUNDS total attempts. This is error-driven only: an empty
# result is NOT a retry trigger (there is no error message to act on).
#
# Scope: only the value-linking pipeline (VAL_LINK_MODE=val_link, i.e. the
# ReAct / Plan&Exec grounders). The baselines (no_val_link, fcav) keep using
# GraphCypherQAChain unchanged; graphrag has its own loop.
# On a DB execution error the repair is a SINGLE error-message-informed CoT pass
# (reason about the error + required structure, then rewrite) — NOT N blind
# retries (blind re-rolls reproduce the same structural mistake; one CoT repair
# corrects more per round at far lower latency).
#   0 = use the legacy GraphCypherQAChain path (reproduce pre-retry ablations).
#   1 = single attempt, NO repair (transparent manual generate→execute path —
#       a clean A/B control).
#   2 = 1 generate + 1 CoT repair on error (default).
#   N = 1 generate + up to N-1 CoT repairs.
# NOTE: val_link with this knob uses a direct cypher_llm.invoke path (not
# GraphCypherQAChain). The recorded movie/flight ablations predate it and went
# through GraphCypherQAChain — re-measure the val_link rows for a clean compare.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
CYPHER_RETRY_MAX_ROUNDS = int(os.getenv("CYPHER_RETRY_MAX_ROUNDS", "2"))
# ── CyANCHOR-only semantic repair (generate→execute→EVALUATE-result→repair) ──
# Extends CyANCHOR's existing error-driven CoT retry with a GraphRAG-style
# semantic check on a SUCCESSFULLY-EXECUTED result: an LLM evaluator judges
# accept / incorrect / illogical / incomplete (empty counts as wrong when
# CYPHER_EMPTY_IS_WRONG), and on a defect CyANCHOR regenerates — keeping its
# grounding injection + CoT, plus the semantic feedback. CyANCHOR ONLY (the
# shared helper is gated by a per-call flag); react/graphrag/baselines untouched.
# Anti-oscillation: the final query is the first ACCEPTED attempt, else the first
# executable attempt (so it can only match-or-beat the no-repair result, never
# silently drift below it). Default on (finished optimizations ship default-on).
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
CYPHER_SEMANTIC_REPAIR  = os.getenv("CYPHER_SEMANTIC_REPAIR", "1").lower() in ("1", "true", "yes")
CYPHER_REPAIR_MAX_ROUNDS = int(os.getenv("CYPHER_REPAIR_MAX_ROUNDS", "4"))
# Default OFF (2026-09): the empty-result trigger showed zero contribution in a
# 4-graph paired ablation — with grounding front-loaded, residual empties are
# mostly legitimately-empty answers and re-generation only churns.
CYPHER_EMPTY_IS_WRONG    = os.getenv("CYPHER_EMPTY_IS_WRONG", "0").lower() in ("1", "true", "yes")
# Retry is error-driven only — an empty result does NOT trigger a rewrite. An
# empty result is not evidence of a wrong query (the answer may legitimately be
# empty), and on this benchmark the dominant failure is "wrong-but-non-empty"
# grounding, which execution feedback can't detect anyway. (Measured: empty-retry
# had 2/20 opportunities, fixed 0, and risks fabricating answers on zero-count
# questions.) The real lever there is semantic verification of the grounded value.

# ──────────────────────────────────────────────────────────────────────────────
# Plan&Exec value-snap  (post-generation grounding guard for the SELECTION error)
# ──────────────────────────────────────────────────────────────────────────────
# Targets the "retrieved-but-not-used" grounding failure: plan_exec DID retrieve
# the canonical value, but the Cypher LLM copied the question's perturbed surface
# form into the WHERE clause (e.g. WHERE p.name = "Tmo Hooper" while "Tom Hooper"
# sat in the candidate list). After generation, for each entity value the query
# uses:
#   • EXISTENCE GATE — if the value EXISTS in the DB, never touch it (so correct/
#     normal queries are structurally safe — they use real values).
#   • if it does NOT exist (the predicate provably matches 0 rows), one batched
#     LLM call picks the matching candidate from plan_exec's already-retrieved
#     candidates, or NONE. The pick is validated to be in the candidate list
#     (guards hallucination); NONE → no snap (recall misses are left for richer
#     retrieval, never fabricated).
# Only `=` / inline-map string literals are considered (not =~ / CONTAINS, which
# are intentional partials). plan_exec only; fires only on non-existent values,
# so the extra LLM call is rare. Set to 0 to disable.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
PLAN_EXEC_VALUE_SNAP = os.getenv("PLAN_EXEC_VALUE_SNAP", "1").lower() in ("1", "true", "yes")

# Latency: skip the escalation loop for a mention that is ALREADY cleanly
# grounded — i.e. a retrieved candidate exact/substring-matches the mention
# (the free, no-LLM check from _judge_grounded's fast path). Only skips work
# that escalation would not have improved, so it's ~EA-neutral. Set 0 to ablate.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
PLAN_EXEC_SKIP_GROUNDED = os.getenv("PLAN_EXEC_SKIP_GROUNDED", "1").lower() in ("1", "true", "yes")
# Pre-generation select-or-abstain judge on non-cheaply-grounded node mentions
# (plan_exec._judge_select). Default ON = the shipped method; exposed as a knob
# so the ablation can toggle it like every other CyANCHOR component.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
PLAN_EXEC_SELECT_JUDGE = os.getenv("PLAN_EXEC_SELECT_JUDGE", "1").lower() in ("1", "true", "yes")
# Latency: run the per-mention EXECUTE/escalation concurrently (mentions are
# independent — same calls, same results, just not serialized). Capped by
# MAX_THREAD. Set 0 to force serial.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
PLAN_EXEC_PARALLEL_MENTIONS = os.getenv("PLAN_EXEC_PARALLEL_MENTIONS", "1").lower() in ("1", "true", "yes")

# CyANCHOR retrieval arms are the three RETRIEVAL_FUZZY / RETRIEVAL_VECTOR /
# RETRIEVAL_LEVENSHTEIN switches (defined in the Method-selection block above).
# The Levenshtein arm is a server-side APOC scan (apoc.text.levenshteinSimilarity)
# over each (label,property) value set; cheap on small graphs (flight ~1.7k), but
# O(N) per mention on large graphs (movie ~218k) — gate at movie scale.
# ⚙ eval receiver — edit in the eval_config panel, not here (literal = demo/CLI fallback).
RETRIEVAL_LEVENSHTEIN_K = int(os.getenv("RETRIEVAL_LEVENSHTEIN_K", "10"))  # candidates from the Lev arm

#  python ner_agent_auto.py "Who played neo in matrix?"  --verbose
#  python ner_agent_auto.py "Who played Neo or Morpheus in The Matrix?" " --verbose
#  python ner_agent_auto.py "Who act  in matrix?"  --verbose
#  python ner_agent_auto.py "Who played neo or morphes in matrix?" --verbose


def active_generator_model() -> str:
    """The generator this process actually uses, as a *preset name* — what run
    directories and reports are keyed by. The GENERATOR_LLM receiver when set
    (the worker, after eval_run injected it), else the preset whose model
    matches the Cypher stage's literal (the stage that defines a run's
    identity), else that literal itself."""
    if GENERATOR_LLM:
        return GENERATOR_LLM
    lit = CYPHER_LLM_CONFIG.get("model") or ""
    for name, spec in MODEL_PRESETS.items():
        if spec["model"] == lit and spec["provider"] == CYPHER_LLM_CONFIG.get("provider"):
            return name
    return lit
