# ──────────────────────────────────────────────────────────────────────────────
# config.py — USER-MANAGED hyperparameters & runtime settings
# ──────────────────────────────────────────────────────────────────────────────
# This file is **NOT** auto-generated. It is safe to edit by hand.
#
# The auto-generated system prompts and schema constants live in
# ``agent/prompts.py`` (regenerated by ``python -m schema.gen_system_prompt``
# from the live Neo4j schema).
# Keeping the two files separate prevents ``setup_project.py`` from
# overwriting the LLM configuration / pipeline knobs every time the schema
# is re-derived.
#
# Layout
# ──────
#   1. LLM configuration (per pipeline stage)
#   2. Runtime constants (sampling, validation, threading)
#   3. NER pipeline mode
# ──────────────────────────────────────────────────────────────────────────────

import os

# ──────────────────────────────────────────────────────────────────────────────
# LLM configuration  (per pipeline stage)
# ──────────────────────────────────────────────────────────────────────────────
# Each pipeline stage has its own LLM "slot" so experiments can mix providers
# (e.g. GPT for NER, Claude Opus for Cypher generation) without code changes.
#
# Schema for every entry:
#   {
#     "provider":    "openai" | "azure" | "anthropic" | "hf_compatible" | "auto",
#     "model":       <model-name | deployment | MODEL_REGISTRY key>,
#     "temperature": <float>,         # optional, default 0
#     # Anything else (max_tokens, top_p, …) is forwarded verbatim to the
#     # chat-model constructor.
#   }
#
# When ``provider == "hf_compatible"`` the ``model`` field is interpreted as
# a key into ``MODEL_REGISTRY`` (see below).  The factory looks the key up to
# get the actual base_url / api_key / model id that should be sent to the
# OpenAI-compatible server.
#
# ``agent_helper.build_llm(**LLM_CONFIG)`` consumes these dicts and returns a
# concrete ``BaseChatModel`` — see ``agent_helper.ner_llm`` / ``qa_llm`` /
# ``cypher_llm`` for the resolved singletons.
#
# Examples
# --------
#   NER_LLM_CONFIG    = {"provider": "openai",        "model": "gpt-4.1"}
#   CYPHER_LLM_CONFIG = {"provider": "anthropic",     "model": "claude-opus-4-20250514"}
#   QA_LLM_CONFIG     = {"provider": "openai",        "model": "gpt-4o-mini"}
#   NER_LLM_CONFIG    = {"provider": "hf_compatible", "model": "llama-8b-hf"}
# ──────────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────────
# MODEL_REGISTRY — open-source / fine-tuned model endpoints
# ──────────────────────────────────────────────────────────────────────────────
# Every entry describes a single OpenAI-compatible HTTP endpoint.  The factory
# in ``agent_helper`` instantiates an ``openai``-SDK-compatible chat client
# (LangChain's ``ChatOpenAI`` is just a thin wrapper around the openai SDK)
# pointed at ``base_url`` with credentials from ``os.environ[api_key_env]`` and
# uses ``model`` as the value to send in the request body's ``model`` field.
#
# ── Why a single ``hf_compatible`` provider for all of these? ────────────────
# The Hugging Face serverless router, HF Inference Endpoints, Groq, Together,
# Fireworks, Anyscale, etc. ALL expose an OpenAI-compatible
# ``/v1/chat/completions`` endpoint.  That means the same openai SDK works for
# every one of them — only ``base_url``, ``api_key``, and ``model`` change.
# We funnel them through one provider name and let the registry encode the
# differences.
#
# ── HF Inference Endpoints + TGI ─────────────────────────────────────────────
# HF Inference Endpoints use TGI (Text Generation Inference) as the default
# inference engine.  TGI exposes an OpenAI-compatible
# ``/v1/chat/completions`` endpoint, which is why we can use the openai SDK
# to call it.  For HF Inference Endpoint registry entries:
#
#   * ``base_url`` is the *unique* endpoint URL HF gives you per-deployment.
#     The URL itself identifies which model is being served.
#   * ``model`` should be set to the literal string ``"tgi"``.  The OpenAI
#     request schema requires a ``model`` field, but TGI ignores it because
#     the URL already pins the model — convention is to fill it with "tgi".
#
# Recommendation: when deploying your own fine-tuned models, use HF Inference
# Endpoints with TGI.  You get a stable URL, an OpenAI-compatible API, and
# zero engine-config work — just push the merged model to the Hub and click
# "Deploy ▸ Inference Endpoints".
#
# ── HF serverless router ─────────────────────────────────────────────────────
# For ``https://router.huggingface.co/v1`` the ``model`` field must be the
# full HF Hub repo id (e.g. ``meta-llama/Llama-3.1-8B-Instruct``), NOT
# ``"tgi"``.  The router uses ``model`` to route between many models behind
# one URL.
#
# ── Other OpenAI-compatible providers ────────────────────────────────────────
# For Groq, Together, Fireworks, etc. use whatever model id the provider
# documents (e.g. Groq's ``llama-3.1-8b-instant``).
#
# ── Adding a new fine-tuned model ────────────────────────────────────────────
# 1. Deploy the merged model to an HF Inference Endpoint.
# 2. Add a new entry below: a unique key, the endpoint URL as ``base_url``,
#    ``"HUGGINGFACE_TOKEN"`` for ``api_key_env`` (this is the variable name
#    used by .env / .env.example in this repo — point it at whatever env var
#    actually holds the HF token), and ``"tgi"`` for ``model``.
# 3. Reference the new key from any of NER_LLM_CONFIG / QA_LLM_CONFIG /
#    CYPHER_LLM_CONFIG (with ``provider="hf_compatible"``).
# ──────────────────────────────────────────────────────────────────────────────

MODEL_REGISTRY: dict = {
    # ── HF serverless router (multiplexes many open-source models) ──────────
    # ``model`` must be the full HF Hub repo id; the router uses it to pick
    # which backend to forward the request to.
    "llama-8b-hf": {
        "base_url":    "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "meta-llama/Llama-3.1-8B-Instruct",
    },
    "qwen-7b-hf": {
        "base_url":    "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "Qwen/Qwen2.5-7B-Instruct",
    },

    # ── Groq (other OpenAI-compatible provider, kept for flexibility) ───────
    # Use Groq's documented model id (NOT a HF Hub repo id, NOT "tgi").
    "llama-8b-groq": {
        "base_url":    "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "model":       "llama-3.1-8b-instant",
    },

    # ── Dedicated HF Inference Endpoint (per fine-tuned model) ──────────────
    # Each fine-tuned model gets its own URL.  The URL pins the model, so
    # ``model`` is just ``"tgi"`` (TGI ignores the field but the OpenAI
    # request schema requires it).  Replace the placeholder URL below with
    # the real endpoint URL after deploying.
    "my-svl-cypher-lora-v1": {
        "base_url":    "https://abc123.us-east-1.aws.endpoints.huggingface.cloud/v1/",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model":       "tgi",  # TGI: URL identifies the model, "tgi" is a placeholder
    },
    # Add more fine-tuned model endpoints here as you deploy them.
    # "my-ner-lora-v2": {
    #     "base_url":    "https://xyz789.us-east-1.aws.endpoints.huggingface.cloud/v1/",
    #     "api_key_env": "HUGGINGFACE_TOKEN",
    #     "model":       "tgi",
    # },

    "qwen-coder-7b-hf": {
        "base_url": "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model": "Qwen/Qwen2.5-Coder-7B-Instruct",
    },
    "qwen-coder-32b-hf": {
        "base_url": "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_TOKEN",
        "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
    },
    "qwen-coder-32b-groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "model": "qwen-2.5-coder-32b",
    },
}


# NER_LLM_CONFIG: dict = {
#     "provider":    "anthropic",
#     "model":       "claude-opus-4-7",
#     "temperature": 0,
# }

# NER_LLM_CONFIG: dict = {
#     "provider":    "anthropic",
#     "model":       "claude-sonnet-4-5",
#     "temperature": 0,
# }

NER_LLM_CONFIG: dict = {
   "provider":    "openai",
   "model":       "gpt-4.1",
   "temperature": 0,
}

# NER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "llama-8b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }


QA_LLM_CONFIG: dict = {
    "provider":    "openai",
    "model":       "gpt-4.1",
    "temperature": 0,
}



# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "qwen-coder-32b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
# }


CYPHER_LLM_CONFIG: dict = {
   "provider":    "openai",
   "model":       "gpt-4.1",
   "temperature": 0,
}

# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "llama-8b-hf",   # MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }

# Example: route the Cypher generator at an open-source / fine-tuned model
# served behind an OpenAI-compatible endpoint (HF router, HF Inference
# Endpoint, Groq, etc.).  The ``model`` field is a key into MODEL_REGISTRY.
# Uncomment to switch — no other code change needed.
#
# CYPHER_LLM_CONFIG: dict = {
#     "provider":    "hf_compatible",
#     "model":       "my-svl-cypher-lora-v1",   # ← MODEL_REGISTRY key
#     "temperature": 0,
#     "max_tokens":  512,
# }

# Legacy default — used by any code path that imports ``agent_helper.llm``
# without specifying a stage.  Defaults to the same setup as NER.
DEFAULT_LLM_CONFIG: dict = dict(NER_LLM_CONFIG)


# ──────────────────────────────────────────────────────────────────────────────
# Runtime constants
# ──────────────────────────────────────────────────────────────────────────────

MAX_THREAD            = 5    # parallel tool calls in the NER agent
# DEFAULT_TOP_K: how many tools the FAISS tool-selector returns per question.
#
# Bumped from 10 → 15 because the partial-name probe showed that on the
# movie graph, top-10 systematically excluded Person tools when the
# question used relational verbs ("feature X in cast", "starring Y",
# "directed by Z"). The eight movie/film-series/award tools dominated the
# top half of the ranking and Person.name fell to ~#11, so the ReAct
# agent never even saw it and resorted to calling `get_movie_eid("Elijah
# Wood")` — a wrong-label tool with predictable empty results. 15 leaves
# slack for the agent to discover the right tool without inflating
# token usage materially.
DEFAULT_TOP_K         = 15   # FAISS tool-selection top-k
TOOL_TOP_K            = 10   # fulltext search top-k per tool call
STABILITY_K           = 3    # consecutive stable validation rounds before stopping
MAX_VALIDATION_ROUNDS = 20   # hard cap on validation rounds per property pair
SAMPLE_T              = 20   # sample size t per round (sample_property_values)
CAP_MULTIPLIER        = 1000    # scan cap = t * CAP_MULTIPLIER (cheap over-fetch for random sampling)


# ──────────────────────────────────────────────────────────────────────────────
# NER pipeline mode
# ──────────────────────────────────────────────────────────────────────────────
# Controls how (or whether) the grounding stage runs in front of the Cypher
# generator.  Names follow a {grounder}_{tool-scope} scheme so the two axes are
# explicit: the grounder (react vs plan_exec) and the tool scope (node-only vs
# node+relation).  Drives both ``ner_agent_auto.ask_auto`` and the CypherBench
# evaluator (``metrics_CypherBench.evaluate_dataset``).
#
#   "no_ner"               — Bypass grounding entirely.  ``ask_auto`` feeds only
#                            ``{schema}`` + ``{question}`` to GraphCypherQAChain.
#                            Lower bound: what the Cypher LLM does unaided.
#
#   "rag"                  — ReAct NER agent capped at a SINGLE tool-call round
#                            with the tool-result backfill DISABLED (node+rel
#                            tool scope).  One retrieval round, no safety net.
#
#   "react_node_only"      — ReAct NER agent, node-property tools only
#                            (``generated_node_tools.py``); relation tools
#                            skipped.  Ablates relation-aware grounding.
#
#   "react_node_rel"       — ReAct NER agent, full tool set (node + relation +
#                            structural traversal).  The richest agentic mode.
#
#   "plan_exec_node_only"  — Plan-and-execute grounder (see plan_exec.py),
#                            routing restricted to node tools.
#
#   "plan_exec_node_rel"   — Plan-and-execute grounder, node + relation tools.
#
# The setting can be overridden per-call by passing ``mode=...`` to
# ``ner_agent_auto.ask_auto`` / ``get_ner_auto`` / ``select_tools_for_query``,
# or via ``--ner-mode`` on the ``metrics_CypherBench`` CLI.
# ──────────────────────────────────────────────────────────────────────────────

# Env-overridable so eval runs can switch mode without editing this file:
#     NER_MODE=react_node_rel python eval_run.py
# Falls back to the literal default when the env var is unset.
NER_MODE: str = os.getenv("NER_MODE", "no_ner")

# Allowed (canonical) values — kept centrally so callers can validate user
# input without hard-coding the literal strings.
NER_MODES = (
    "no_ner",
    "rag",
    "react_node_only",
    "react_node_rel",
    "plan_exec_node_only",
    "plan_exec_node_rel",
)

# Back-compat aliases: legacy mode names → canonical names.  Existing eval
# scripts / NER_MODE env values / saved logs keep working; ``_resolve_mode``
# maps these to the canonical name before validation.
NER_MODE_ALIASES = {
    "full":      "react_node_rel",
    "node_only": "react_node_only",
    "plan_exec": "plan_exec_node_rel",
}

# RAG baseline: the ReAct NER agent restricted to a SINGLE tool-call round and
# with the tool-result backfill DISABLED. It uses the same (node + relation)
# tool set as `full`, but the agent gets one think→act→observe cycle and must
# then answer — no iterative refinement, no safety net. This isolates "what one
# retrieval round of an LLM agent recovers" as a lower-effort baseline against
# the full agentic `full` / `node_only` modes (which loop + backfill).
# RAG_RECURSION_LIMIT caps the LangGraph supersteps: agent → tools → agent ≈ 3.
RAG_RECURSION_LIMIT = 3

# plan_exec baseline: a deterministic plan-and-execute grounder (no ReAct loop).
#   PLAN     — one LLM call decomposes the question into entity mentions, each
#              tagged node|relation + a short type descriptor.
#   EXECUTE  — per mention: route to the matching tool via the tool-VectorDB
#              (by descriptor), then search_tool(mention) for the top-K
#              canonical values (node mentions) / emit the relationship pattern
#              (relation mentions). No per-tool get_entity re-extraction.
#   GENERATE — the per-mention candidate lists are handed verbatim to the
#              Cypher LLM, which does the value-linking while writing Cypher.
# Contrasts with `full`: per-entity tool routing (no top-k tool crowding), no
# get_entity intermediate layer, and candidates (not a single forced pick) are
# given to the generator. Retrieval stays fuzzy (no value-embedding index).
PLAN_EXEC_TOOLS_PER_ENTITY = 2    # tools routed per extracted mention
PLAN_EXEC_VALUES_PER_TOOL  = 10   # top-K canonical values searched per tool

#  python ner_agent_auto.py "Who played neo in matrix?"  --verbose
#  python ner_agent_auto.py "Who played Neo or Morpheus in The Matrix?" " --verbose
#  python ner_agent_auto.py "Who act  in matrix?"  --verbose
#  python ner_agent_auto.py "Who played neo or morphes in matrix?" --verbose
