#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_tools.py
============
Introspects a live Neo4j database and emits two ready-to-import Python source
files containing LangChain ``@tool``-decorated functions:

  generated_node_tools.py
      One tool per (node label × property) pair.
      Each tool extracts a keyword from the user query with ``get_entity()``,
      then calls ``search_tool()`` to return canonical property values.

  generated_rel_tools.py
      • Part 1 – relationships WITH properties:
        One tool per (relationship type × property) pair.
        Calls ``search_rel_tool()`` (defined in neo4j_search.py).
      • Part 2 – structural (property-less) relationships:
        One tool per unique (rel_type, from_label, to_label) pattern.
        Calls ``search_tool()`` on the end-node's primary identifying property.

Usage
-----
  python gen_tools.py
  python gen_tools.py --node-output node_tools.py --rel-output rel_tools.py
  python gen_tools.py --database movies

Environment variables  (loaded from .env)
-----------------------------------------
  NEO4J_URI        bolt / neo4j+s URI
  NEO4J_USERNAME
  NEO4J_PASSWORD
  NEO4J_DATABASE   default: movies
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Dict, List, Set, Tuple

from dotenv import load_dotenv
from neo4j import GraphDatabase
from neo4j.exceptions import Neo4jError

load_dotenv()

# ──────────────────────────────────────────────────────────────────────────────
# File headers written verbatim into the generated files
# ──────────────────────────────────────────────────────────────────────────────

_NODE_HEADER = '''\
# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from ner_agent import get_entity
from neo4j_search import search_tool
from config import TOOL_TOP_K


'''

_REL_HEADER = '''\
# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from ner_agent import get_entity
from neo4j_search import search_tool, search_rel_tool
from config import TOOL_TOP_K


'''


# ──────────────────────────────────────────────────────────────────────────────
# Neo4j connection helpers
# ──────────────────────────────────────────────────────────────────────────────

def _require_env(name: str) -> str:
    """Raise a clear error when a required environment variable is missing."""
    v = os.getenv(name)
    if not v:
        raise RuntimeError(
            f"Missing required environment variable: {name}. "
            "Set it in .env or your system environment."
        )
    return v


def _get_driver():
    """Build a Neo4j driver from environment variables."""
    return GraphDatabase.driver(
        _require_env("NEO4J_URI"),
        auth=(_require_env("NEO4J_USERNAME"), _require_env("NEO4J_PASSWORD")),
    )


# ──────────────────────────────────────────────────────────────────────────────
# Schema introspection
# ──────────────────────────────────────────────────────────────────────────────

def list_node_pairs(driver, database: str) -> List[Tuple[str, str]]:
    """
    Return deduplicated ``(primary_label, property_name)`` pairs for every
    node property found in the database.

    Tries ``db.schema.nodeTypeProperties()`` first (Neo4j 4.4+).
    Falls back to scanning each label's ``keys(n)`` if the procedure is
    unavailable.
    """
    pairs: List[Tuple[str, str]] = []
    seen: Set[Tuple[str, str]] = set()

    with driver.session(database=database) as session:
        # ── Primary path: schema procedure ────────────────────────────────────
        try:
            records = list(session.run(
                "CALL db.schema.nodeTypeProperties() "
                "YIELD nodeType, propertyName "
                "RETURN nodeType, propertyName"
            ))
            for r in records:
                nt = str(r.get("nodeType") or "").strip()
                pn = str(r.get("propertyName") or "").strip()
                if not nt or not pn:
                    continue
                label = _parse_primary_label(nt)
                key = (label, pn)
                if key not in seen:
                    seen.add(key)
                    pairs.append(key)
            return pairs
        except (Neo4jError, Exception):
            pass  # fall through to scan

        # ── Fallback: scan each label ─────────────────────────────────────────
        label_rows = list(session.run("CALL db.labels() YIELD label RETURN label"))
        for lr in label_rows:
            label = str(lr.get("label") or "").strip()
            if not label:
                continue
            safe = label.replace("`", "``")
            for r in session.run(
                f"MATCH (n:`{safe}`) UNWIND keys(n) AS k RETURN DISTINCT k AS propertyName"
            ):
                pn = str(r.get("propertyName") or "").strip()
                if pn:
                    key = (label, pn)
                    if key not in seen:
                        seen.add(key)
                        pairs.append(key)

    return pairs


def list_rel_property_pairs(driver, database: str) -> List[Tuple[str, str]]:
    """
    Return deduplicated ``(rel_type, property_name)`` pairs for every
    relationship property found in the database.

    Tries ``db.schema.relTypeProperties()`` first (Neo4j 4.4+).
    Falls back to scanning live relationships.
    """
    pairs: List[Tuple[str, str]] = []
    seen: Set[Tuple[str, str]] = set()

    with driver.session(database=database) as session:
        # ── Primary path: schema procedure ────────────────────────────────────
        try:
            records = list(session.run(
                "CALL db.schema.relTypeProperties() "
                "YIELD relType, propertyName "
                "WHERE propertyName IS NOT NULL "
                "RETURN relType, propertyName"
            ))
            for r in records:
                # relType may arrive as `:`ACTED_IN`` — clean it unconditionally
                rt = _clean_rel_type(str(r.get("relType") or ""))
                pn = str(r.get("propertyName") or "").strip()
                if not rt or not pn:
                    continue
                key = (rt, pn)
                if key not in seen:
                    seen.add(key)
                    pairs.append(key)
            return pairs
        except (Neo4jError, Exception):
            pass  # fall through to scan

        # ── Fallback: scan live relationship keys ─────────────────────────────
        for r in session.run(
            "MATCH ()-[r]->() "
            "WHERE size(keys(r)) > 0 "
            "UNWIND keys(r) AS k "
            "RETURN DISTINCT type(r) AS relType, k AS propertyName "
            "ORDER BY relType, k"
        ):
            rt = _clean_rel_type(str(r.get("relType") or ""))
            pn = str(r.get("propertyName") or "").strip()
            if rt and pn:
                key = (rt, pn)
                if key not in seen:
                    seen.add(key)
                    pairs.append(key)

    return pairs


def list_structural_relations(driver, database: str) -> List[Tuple[str, str, str]]:
    """
    Return deduplicated ``(rel_type, from_label, to_label)`` triples for every
    unique relationship pattern in the database (including those with properties).

    The caller is responsible for filtering out rel types that already have
    property-specific tools in Part 1.
    """
    patterns: List[Tuple[str, str, str]] = []
    seen: Set[Tuple[str, str, str]] = set()

    with driver.session(database=database) as session:
        for r in session.run(
            "MATCH (a)-[r]->(b) "
            "RETURN DISTINCT type(r) AS relType, "
            "head(labels(a)) AS fromLabel, "
            "head(labels(b)) AS toLabel "
            "ORDER BY relType"
        ):
            rt = _clean_rel_type(str(r.get("relType") or ""))
            fl = str(r.get("fromLabel") or "").strip()
            tl = str(r.get("toLabel") or "").strip()
            if rt and fl and tl:
                key = (rt, fl, tl)
                if key not in seen:
                    seen.add(key)
                    patterns.append(key)

    return patterns


# ──────────────────────────────────────────────────────────────────────────────
# Naming helpers
# ──────────────────────────────────────────────────────────────────────────────

def _parse_primary_label(node_type: str) -> str:
    """
    Extract the primary label from a nodeType string, stripping any
    backtick quoting that Neo4j may include.

    Examples::

        ':Movie'           → 'Movie'
        ':`Movie`'         → 'Movie'
        ':Person:Employee' → 'Person'   (first label)
        'Movie'            → 'Movie'    (bare label, no colon prefix)
    """
    if node_type.startswith(":"):
        parts = [p.strip().strip("`") for p in node_type.split(":") if p.strip()]
        return parts[0] if parts else node_type.strip("`")
    return node_type.strip("`")


def _camel_to_snake(name: str) -> str:
    """
    Convert CamelCase (or mixedCase) to snake_case.

    Examples::

        'JobPosting' → 'job_posting'
        'tagline'    → 'tagline'
        'firstName'  → 'first_name'
    """
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def _safe_ident(s: str) -> str:
    """
    Replace every non-alphanumeric character with ``_``, collapse runs,
    strip leading/trailing underscores, and lower-case.
    """
    s = re.sub(r"[^a-zA-Z0-9]", "_", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_").lower()


def _label_snake(label: str) -> str:
    """Convert a node label to a snake_case identifier fragment."""
    return _camel_to_snake(_safe_ident(label))


def _clean_rel_type(raw: str) -> str:
    """
    Strip Neo4j formatting artefacts from a relationship type string.

    Neo4j's ``db.schema.relTypeProperties()`` may return the type wrapped in
    backticks and prefixed with a colon, e.g. `` :`ACTED_IN` ``.
    This helper normalises all variants to the bare type name, e.g. ``ACTED_IN``.
    """
    s = raw.strip()           # remove surrounding whitespace
    s = s.strip("`")          # remove wrapping backticks
    s = s.lstrip(":")         # remove leading colon (`:ACTED_IN` → `ACTED_IN`)
    s = s.strip("`")          # remove any remaining inner backticks
    return s


def _rel_snake(rel_type: str) -> str:
    """
    Convert a relationship type (ALL_CAPS, possibly prefixed with ``:`` or
    wrapped in backticks) to a safe snake_case Python identifier fragment.

    Examples::

        'ACTED_IN'        → 'acted_in'
        ':ACTED_IN'       → 'acted_in'
        ':`ACTED_IN`'     → 'acted_in'
        'HAS_WORKED_FOR'  → 'has_worked_for'
    """
    return _safe_ident(_clean_rel_type(rel_type))


def _prop_snake(prop: str) -> str:
    """Convert a property name to snake_case."""
    return _camel_to_snake(prop)


def _unique_name(base: str, seen: Set[str]) -> str:
    """
    Return *base* if not already taken; otherwise append ``_2``, ``_3`` …
    Mutates *seen* by adding the returned name.
    """
    name = base
    counter = 2
    while name in seen:
        name = f"{base}_{counter}"
        counter += 1
    seen.add(name)
    return name


# ──────────────────────────────────────────────────────────────────────────────
# Topic string helpers (feed into get_entity's `topic` argument)
# ──────────────────────────────────────────────────────────────────────────────

# Properties whose names benefit from a clarifying suffix in the topic string.
_PROP_TOPIC_SUFFIX: Dict[str, str] = {
    "released": "year",
    "born":     "year",
    "year":     "year",
    "date":     "date",
    "id":       "ID",
    "rating":   "rating",
    "score":    "score",
}


def _node_topic(label: str, prop: str) -> str:
    """Human-readable topic for a node property search."""
    suffix = _PROP_TOPIC_SUFFIX.get(prop.lower(), "")
    base = f"{label} {prop}"
    return f"{base} {suffix}".strip() if suffix else base


def _rel_prop_topic(rel_type: str, prop: str) -> str:
    """Human-readable topic for a relationship property search."""
    return f"{prop} in {rel_type} relationship"


def _structural_rel_topic(rel_type: str, to_label: str, end_prop: str) -> str:
    """Human-readable topic for a structural (property-less) relationship tool."""
    return f"{to_label.lower()} {end_prop} in {rel_type} relationship"


def _guess_id_property(label: str) -> str:
    """
    Heuristically pick the primary identifying text property for a label.

    Returns ``"title"`` for movie/book/film-like labels, ``"name"`` otherwise.
    """
    lower = label.lower()
    if any(kw in lower for kw in ("movie", "film", "book", "song", "album",
                                   "article", "post", "product", "item")):
        return "title"
    return "name"


# ──────────────────────────────────────────────────────────────────────────────
# Code-rendering helpers — each returns a complete function block as a string
# ──────────────────────────────────────────────────────────────────────────────

def _render_node_tool(func_name: str, label: str, prop: str) -> str:
    """
    Render a single node @tool function.

    Matches the exact style used in ``ner_agent.py``::

        @tool
        def get_movie_title(user_query: str) -> List[str]:
            \"\"\"Get the canonical Movie.title values from the database.\"\"\"
            search_term = get_entity(user_query, topic="Movie title")
            return search_tool(phrase=search_term, node_label="Movie",
                               property_name="title", verbose=True)
    """
    topic = _node_topic(label, prop)
    doc   = f"Get the canonical {label}.{prop} values from the database."
    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    return search_tool(phrase=search_term, node_label="{label}", '
        f'property_name="{prop}", k=TOOL_TOP_K, verbose=True)\n'
    )


def _render_rel_property_tool(func_name: str, rel_type: str, prop: str) -> str:
    """
    Render a relationship-property @tool function.

    Calls ``search_rel_tool`` (defined in ``neo4j_search.py``)::

        @tool
        def get_acted_in_roles(user_query: str) -> List[str]:
            \"\"\"Get the canonical ACTED_IN.roles values from the database.\"\"\"
            search_term = get_entity(user_query, topic="roles in ACTED_IN relationship")
            return search_rel_tool(phrase=search_term, rel_type="ACTED_IN",
                                   property_name="roles", verbose=True)
    """
    topic = _rel_prop_topic(rel_type, prop)
    doc   = f"Get the canonical {rel_type}.{prop} values from the database."
    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    return search_rel_tool(phrase=search_term, rel_type="{rel_type}", '
        f'property_name="{prop}", k=TOOL_TOP_K, verbose=True)\n'
    )


def _render_structural_rel_tool(
    func_name: str,
    rel_type: str,
    from_label: str,
    to_label: str,
) -> str:
    """
    Render a structural (property-less) relationship @tool function.

    Searches the end-node's primary identifying property so the agent can
    resolve canonical values for Cypher WHERE clauses::

        @tool
        def get_directed_relation(user_query: str) -> List[str]:
            \"\"\"Find Movie.title values reachable via
            (:Person)-[:DIRECTED]->(:Movie) in the database.\"\"\"
            search_term = get_entity(user_query, topic="movie title in DIRECTED relationship")
            return search_tool(phrase=search_term, node_label="Movie",
                               property_name="title", verbose=True)
    """
    end_prop = _guess_id_property(to_label)
    topic    = _structural_rel_topic(rel_type, to_label, end_prop)
    doc      = (
        f"Find {to_label}.{end_prop} values reachable via "
        f"(:{from_label})-[:{rel_type}]->(:{to_label}) in the database."
    )
    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    return search_tool(phrase=search_term, node_label="{to_label}", '
        f'property_name="{end_prop}", k=TOOL_TOP_K, verbose=True)\n'
    )


# ──────────────────────────────────────────────────────────────────────────────
# File generators
# ──────────────────────────────────────────────────────────────────────────────

def generate_node_tools_file(
    node_pairs: List[Tuple[str, str]],
    output_path: str,
) -> int:
    """
    Write ``generated_node_tools.py``.

    Returns the number of @tool functions written.
    """
    seen_names: Set[str] = set()
    blocks: List[str] = []

    for label, prop in node_pairs:
        base      = f"get_{_label_snake(label)}_{_prop_snake(prop)}"
        func_name = _unique_name(base, seen_names)
        blocks.append(_render_node_tool(func_name, label, prop))

    content = _NODE_HEADER + "\n\n".join(blocks) + "\n"
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    return len(blocks)


def generate_rel_tools_file(
    rel_prop_pairs: List[Tuple[str, str]],
    structural_relations: List[Tuple[str, str, str]],
    output_path: str,
) -> int:
    """
    Write ``generated_rel_tools.py``.

    The file has two clearly separated sections:

    * **Part 1** – relationship property tools (``search_rel_tool``).
    * **Part 2** – structural traversal tools for property-less relationships
      (``search_tool`` on the end node).

    Returns the total number of @tool functions written.
    """
    seen_names: Set[str] = set()
    blocks: List[str]    = []

    # ── Part 1: relationship property tools ───────────────────────────────────
    if rel_prop_pairs:
        blocks.append(
            "# " + "─" * 72 + "\n"
            "# Part 1 — Relationship PROPERTY tools\n"
            "#          Search canonical values stored on relationship objects.\n"
            "# " + "─" * 72
        )
        for rel_type, prop in rel_prop_pairs:
            base      = f"get_{_rel_snake(rel_type)}_{_prop_snake(prop)}"
            func_name = _unique_name(base, seen_names)
            blocks.append(_render_rel_property_tool(func_name, rel_type, prop))

    # ── Part 2: structural (property-less) relationship tools ─────────────────
    # Exclude rel types that already have dedicated property tools above.
    rels_with_props: Set[str] = {rt for rt, _ in rel_prop_pairs}
    pure_structural = [
        (rt, fl, tl)
        for rt, fl, tl in structural_relations
        if rt not in rels_with_props
    ]

    if pure_structural:
        blocks.append(
            "\n\n# " + "─" * 72 + "\n"
            "# Part 2 — Structural TRAVERSAL tools\n"
            "#          No properties on the relationship itself; searches the\n"
            "#          end-node's primary identifying property instead.\n"
            "# " + "─" * 72
        )
        for rel_type, from_label, to_label in pure_structural:
            base      = f"get_{_rel_snake(rel_type)}_relation"
            func_name = _unique_name(base, seen_names)
            blocks.append(
                _render_structural_rel_tool(func_name, rel_type, from_label, to_label)
            )

    content = _REL_HEADER + "\n\n".join(blocks) + "\n"
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    # Count only @tool blocks (skip comment-only separator blocks)
    return sum(1 for b in blocks if b.startswith("@tool"))


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Generate LangChain @tool functions from a Neo4j schema "
            "into two Python files."
        )
    )
    p.add_argument(
        "--node-output",
        default="generated_node_tools.py",
        metavar="PATH",
        help="Output path for node tools (default: generated_node_tools.py)",
    )
    p.add_argument(
        "--rel-output",
        default="generated_rel_tools.py",
        metavar="PATH",
        help="Output path for relation tools (default: generated_rel_tools.py)",
    )
    p.add_argument(
        "--database",
        default=os.getenv("NEO4J_DATABASE", "neo4j"),
        metavar="DB",
        help="Neo4j database name (default: $NEO4J_DATABASE or 'movies')",
    )
    return p.parse_args()


def main() -> None:
    args = _parse_args()

    print("Connecting to Neo4j …", flush=True)
    driver = _get_driver()

    try:
        db = args.database
        print(f"Introspecting schema  (database={db!r}) …", flush=True)

        node_pairs       = list_node_pairs(driver, db)
        rel_prop_pairs   = list_rel_property_pairs(driver, db)
        structural_rels  = list_structural_relations(driver, db)

    finally:
        driver.close()

    print(
        f"  {len(node_pairs):>3d}  node (label, property) pairs\n"
        f"  {len(rel_prop_pairs):>3d}  relationship property pairs\n"
        f"  {len(structural_rels):>3d}  unique relationship patterns",
        flush=True,
    )

    n_node = generate_node_tools_file(node_pairs, args.node_output)
    print(f"\n✓  {n_node:>3d} node tools  →  {args.node_output}", flush=True)

    n_rel = generate_rel_tools_file(rel_prop_pairs, structural_rels, args.rel_output)
    print(f"✓  {n_rel:>3d} rel  tools  →  {args.rel_output}", flush=True)


if __name__ == "__main__":
    main()
