# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
#
# Retrieval-mode dispatch (v1):
#   • Relationship-property tools (Part 1)       → fuzzy ONLY.
#       v2 extension point: vector retrieval over relationship properties
#       is deferred until the target database with rel-property semantics
#       is finalized. `mode="fuzzy"` is passed explicitly so this stays
#       fixed even if TOOL_RETRIEVAL_MODE is flipped to "hybrid" for the
#       node ablation.
#   • Structural traversal tools (Part 2)        → fuzzy ONLY (PERMANENT).
#       Structural tools follow graph paths to reach values; they are NOT
#       semantic retrieval. Mixing in a vector index over the end-node
#       label would conflate "value linking via traversal" with "value
#       linking via embedding similarity" and break tool semantics.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from agent_helper import get_entity
from neo4j_search import search_tool, search_rel_tool
from config import TOOL_TOP_K


# ────────────────────────────────────────────────────────────────────────
# Part 1 — Relationship PROPERTY tools
#          Search canonical values stored on relationship objects.
# ────────────────────────────────────────────────────────────────────────

@tool
def get_acted_in_roles(user_query: str) -> List[str]:
    """Get the canonical ACTED_IN.roles values from the database."""
    search_term = get_entity(user_query, topic="character names")
    # v1: relationship-property retrieval is fuzzy-only.
    # TODO(v2): drop mode="fuzzy" once rel-property vector indexes ship.
    return search_rel_tool(phrase=search_term, rel_type="ACTED_IN", property_name="roles", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_reviewed_summary(user_query: str) -> List[str]:
    """Get the canonical REVIEWED.summary values from the database."""
    search_term = get_entity(user_query, topic="review summary")
    # v1: relationship-property retrieval is fuzzy-only.
    # TODO(v2): drop mode="fuzzy" once rel-property vector indexes ship.
    return search_rel_tool(phrase=search_term, rel_type="REVIEWED", property_name="summary", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_reviewed_rating(user_query: str) -> List[str]:
    """Get the canonical REVIEWED.rating values from the database."""
    search_term = get_entity(user_query, topic="review score")
    # v1: relationship-property retrieval is fuzzy-only.
    # TODO(v2): drop mode="fuzzy" once rel-property vector indexes ship.
    return search_rel_tool(phrase=search_term, rel_type="REVIEWED", property_name="rating", k=TOOL_TOP_K, verbose=True, mode="fuzzy")




# ────────────────────────────────────────────────────────────────────────
# Part 2 — Structural TRAVERSAL tools
#          No properties on the relationship itself; searches the
#          end-node's primary identifying property instead.
# ────────────────────────────────────────────────────────────────────────

@tool
def get_authored_relation(user_query: str) -> List[str]:
    """Find Work.title values reachable via (:Author)-[:AUTHORED]->(:Work) in the database."""
    search_term = get_entity(user_query, topic="work title in AUTHORED relationship")
    # PERMANENT: structural traversal tools are not semantic retrieval.
    # mode="fuzzy" is intentional and must NOT be removed.
    return search_tool(phrase=search_term, node_label="Work", property_name="title", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_directed_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:DIRECTED]->(:Movie) in the database."""
    search_term = get_entity(user_query, topic="movie title in DIRECTED relationship")
    # PERMANENT: structural traversal tools are not semantic retrieval.
    # mode="fuzzy" is intentional and must NOT be removed.
    return search_tool(phrase=search_term, node_label="Movie", property_name="title", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_follows_relation(user_query: str) -> List[str]:
    """Find Person.name values reachable via (:Person)-[:FOLLOWS]->(:Person) in the database."""
    search_term = get_entity(user_query, topic="person name in FOLLOWS relationship")
    # PERMANENT: structural traversal tools are not semantic retrieval.
    # mode="fuzzy" is intentional and must NOT be removed.
    return search_tool(phrase=search_term, node_label="Person", property_name="name", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_produced_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:PRODUCED]->(:Movie) in the database."""
    search_term = get_entity(user_query, topic="movie title in PRODUCED relationship")
    # PERMANENT: structural traversal tools are not semantic retrieval.
    # mode="fuzzy" is intentional and must NOT be removed.
    return search_tool(phrase=search_term, node_label="Movie", property_name="title", k=TOOL_TOP_K, verbose=True, mode="fuzzy")


@tool
def get_wrote_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:WROTE]->(:Movie) in the database."""
    search_term = get_entity(user_query, topic="movie title in WROTE relationship")
    # PERMANENT: structural traversal tools are not semantic retrieval.
    # mode="fuzzy" is intentional and must NOT be removed.
    return search_tool(phrase=search_term, node_label="Movie", property_name="title", k=TOOL_TOP_K, verbose=True, mode="fuzzy")

