# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from ner_agent import get_entity
from neo4j_search import search_tool, search_rel_tool
from config import TOOL_TOP_K


# ────────────────────────────────────────────────────────────────────────
# Part 1 — Relationship PROPERTY tools
#          Search canonical values stored on relationship objects.
# ────────────────────────────────────────────────────────────────────────

@tool
def get_acted_in_roles(user_query: str) -> List[str]:
    """Get the canonical ACTED_IN.roles values from the database."""
    search_term = get_entity(user_query, topic='roles in ACTED_IN relationship')
    return search_rel_tool(phrase=search_term, rel_type='ACTED_IN', property_name='roles', k=TOOL_TOP_K, verbose=True)


@tool
def get_reviewed_summary(user_query: str) -> List[str]:
    """Get the canonical REVIEWED.summary values from the database."""
    search_term = get_entity(user_query, topic='summary in REVIEWED relationship')
    return search_rel_tool(phrase=search_term, rel_type='REVIEWED', property_name='summary', k=TOOL_TOP_K, verbose=True)


@tool
def get_reviewed_rating(user_query: str) -> List[str]:
    """Get the canonical REVIEWED.rating values from the database."""
    search_term = get_entity(user_query, topic='rating in REVIEWED relationship')
    return search_rel_tool(phrase=search_term, rel_type='REVIEWED', property_name='rating', k=TOOL_TOP_K, verbose=True)




# ────────────────────────────────────────────────────────────────────────
# Part 2 — Structural TRAVERSAL tools
#          No properties on the relationship itself; searches the
#          end-node's primary identifying property instead.
# ────────────────────────────────────────────────────────────────────────

@tool
def get_directed_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:DIRECTED]->(:Movie). This property represents the title of a movie."""
    search_term = get_entity(user_query, topic='movie title')
    return search_tool(phrase=search_term, node_label='Movie', property_name='title', k=TOOL_TOP_K, verbose=True)


@tool
def get_follows_relation(user_query: str) -> List[str]:
    """Find Person.name values reachable via (:Person)-[:FOLLOWS]->(:Person). This property represents the full name of a person."""
    search_term = get_entity(user_query, topic='person name')
    return search_tool(phrase=search_term, node_label='Person', property_name='name', k=TOOL_TOP_K, verbose=True)


@tool
def get_produced_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:PRODUCED]->(:Movie). This property represents the title of a movie."""
    search_term = get_entity(user_query, topic='movie title')
    return search_tool(phrase=search_term, node_label='Movie', property_name='title', k=TOOL_TOP_K, verbose=True)


@tool
def get_wrote_relation(user_query: str) -> List[str]:
    """Find Movie.title values reachable via (:Person)-[:WROTE]->(:Movie). This property represents the title of a movie."""
    search_term = get_entity(user_query, topic='movie title')
    return search_tool(phrase=search_term, node_label='Movie', property_name='title', k=TOOL_TOP_K, verbose=True)

