#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ner_agent_auto.py
=================
Drop-in extension of ``ner_agent.py`` that *automatically* picks only the
most relevant ``@tool`` functions for each user query instead of wiring every
tool into every agent call.

New public API (mirrors ner_agent.py)
--------------------------------------
  get_ner_auto(prompt, top_k=5, verbose=False)  → JSON string
  get_ner_dict_auto(prompt, top_k=5, verbose=False) → dict

Prerequisite
------------
Run ``python gen_tools.py`` once to generate
``generated_node_tools.py`` and ``generated_rel_tools.py``.
The first call to any ``*_auto`` function will also build the
FAISS index in ``faiss_tools_auto/`` (subsequent calls load it from disk).

How tool selection works
------------------------
1. ``build_tool_registry()``
   Imports ``generated_node_tools`` and ``generated_rel_tools``, scans their
   module-level names for ``BaseTool`` instances, and returns a registry dict::

       {"get_movie_title": <BaseTool>, "get_person_name": <BaseTool>, ...}

2. ``get_or_build_tools_faiss(registry)``
   Builds (or loads from disk) a FAISS vector index where each document
   represents one tool. The embedding text is::

       "get_movie_title: get_movie_title: Get the canonical Movie.title …"

3. ``select_tools_for_query(user_query, top_k)``
   Embeds the user query, searches FAISS, and returns the top-k matching
   ``BaseTool`` callables.

4. ``create_agent_auto(user_query, top_k)``
   Builds a LangGraph ReAct agent wired with only the selected tools.

5. ``get_ner_auto(prompt, top_k, verbose)``
   Orchestrates steps 3-4, runs the agent, and parses the output to the
   canonical JSON string ``{"Label.property": [values, ...]}`` — identical
   format to ``ner_agent.get_ner()``.
"""

from __future__ import annotations

import ast
import importlib
import json
import os
import re
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Union

from dotenv import load_dotenv
from loguru import logger

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, ToolMessage
from langchain_core.prompts import PromptTemplate
from langchain_core.tools import BaseTool
from langchain_neo4j import GraphCypherQAChain
from langgraph.prebuilt import create_react_agent

from config import DEFAULT_TOP_K, NER_MODE, NER_MODES
from paths import FAISS_AUTO_DIR as _FAISS_AUTO_DIR_PATH, SCHEMA_META
from agent.prompts import NER_SP   # auto-generated by gen_system_prompt.py
from agent.agent_helper import (
    llm,                       # legacy default — kept for backward compat
    ner_llm     as _ner_llm,   # configured NER-stage LLM      (config.NER_LLM_CONFIG)
    qa_llm      as _qa_llm,    # configured QA-stage LLM       (config.QA_LLM_CONFIG)
    cypher_llm  as _cypher_llm,# configured Cypher-stage LLM   (config.CYPHER_LLM_CONFIG)
    neo4j_graph,
    get_entity,
    build_llm,                 # noqa: F401  (re-exported for caller convenience)
)
from neo4j_lib.neo4j_search import search_tool
from tools.tool_search import (
    ToolSearchHit,
    build_embeddings,
    build_tool_registry_from_modules,
    get_or_build_tools_faiss,
    hits_to_callables,
    search_tools,
)

load_dotenv(".env", override=True)

# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

FAISS_AUTO_DIR: str = str(_FAISS_AUTO_DIR_PATH)
# DEFAULT_TOP_K is imported from config.py so it can be tuned in one place.

# Per-mode FAISS index directories.  Each mode caches its registry-specific
# vectorstore in its own directory so switching ``NER_MODE`` (or passing
# ``mode=...`` at call time) doesn't invalidate the index for the other mode.
_FAISS_DIR_BY_MODE: Dict[str, str] = {
    "full":      str(_FAISS_AUTO_DIR_PATH),
    "node_only": str(_FAISS_AUTO_DIR_PATH.with_name(_FAISS_AUTO_DIR_PATH.name + "_node_only")),
    # "no_ner" never touches FAISS, but we still register a placeholder so
    # ``_FAISS_DIR_BY_MODE[mode]`` never raises a KeyError.
    "no_ner":    str(_FAISS_AUTO_DIR_PATH),
}


def _resolve_mode(mode: Optional[str]) -> str:
    """Return the effective NER mode.

    Resolution order:

    1. Explicit *mode* argument when provided (must be one of ``NER_MODES``).
    2. Fallback to the module-level default :data:`config.NER_MODE`.

    A :class:`ValueError` is raised for unknown values so a typo in
    ``config.py`` or a CLI flag fails loudly rather than silently
    behaving like ``"full"``.
    """
    effective = (mode or NER_MODE or "full").strip().lower()
    if effective not in NER_MODES:
        raise ValueError(
            f"Unknown NER mode {effective!r}. Expected one of {NER_MODES}."
        )
    return effective

# ──────────────────────────────────────────────────────────────────────────────
# 1. LLM, Neo4j & entity extraction — reused from ner_agent.py
#    Imported at the top of this module:
#      from agent_helper import llm, neo4j_graph, get_entity
# ──────────────────────────────────────────────────────────────────────────────


# ──────────────────────────────────────────────────────────────────────────────
# 3. Tool registry  — scan generated modules for @tool instances
# ──────────────────────────────────────────────────────────────────────────────

def build_tool_registry(mode: Optional[str] = None) -> Dict[str, BaseTool]:
    """
    Import the generated tool modules and return a registry mapping
    ``func_name → BaseTool``.

    Which modules are loaded depends on the resolved NER *mode*:

    ====== ============================================================
    mode    Modules loaded
    ====== ============================================================
    ``"full"``       ``generated_node_tools`` + ``generated_rel_tools``
    ``"node_only"``  ``generated_node_tools`` only (relation tools dropped)
    ``"no_ner"``     no modules — the registry is empty because the agent
                     is bypassed entirely (callers must check the mode
                     before relying on the registry).
    ====== ============================================================

    Parameters
    ----------
    mode : str | None
        Explicit override of :data:`config.NER_MODE`.  See :func:`_resolve_mode`.

    Raises
    ------
    RuntimeError
        If *mode* expects tool modules but none can be imported (i.e.
        ``gen_tools.py`` has not been run yet).
    """
    effective = _resolve_mode(mode)

    if effective == "no_ner":
        logger.info("Tool registry skipped — NER mode is 'no_ner'.")
        return {}

    if effective == "node_only":
        target_modules = ("generated.generated_node_tools",)
    else:                           # "full"
        target_modules = ("generated.generated_node_tools", "generated.generated_rel_tools")

    modules = []
    for mod_name in target_modules:
        try:
            mod = importlib.import_module(mod_name)
            importlib.reload(mod)          # pick up fresh re-generations
            modules.append(mod)
            logger.debug(f"Imported {mod_name!r}")
        except ImportError:
            logger.warning(
                f"Could not import {mod_name!r}. "
                "Run `python gen_tools.py` to generate it."
            )

    if not modules:
        raise RuntimeError(
            f"No generated tool modules found for NER mode {effective!r}. "
            "Please run `python gen_tools.py` first to create "
            "`generated_node_tools.py` and `generated_rel_tools.py`."
        )

    registry = build_tool_registry_from_modules(modules)
    logger.info(
        f"Tool registry built (mode={effective!r}): {len(registry)} tools loaded."
    )
    return registry


# ──────────────────────────────────────────────────────────────────────────────
# 4. Module-level lazy singletons for registry and FAISS
# ──────────────────────────────────────────────────────────────────────────────

# Cached per-mode so switching mode at runtime (e.g. for an evaluation
# sweep) doesn't force every call to rebuild the registry / FAISS index.
_registry_by_mode:    Dict[str, Dict[str, BaseTool]] = {}
_vectorstore_by_mode: Dict[str, Any]                 = {}
_embeddings                                          = None


def _get_registry(mode: Optional[str] = None) -> Dict[str, BaseTool]:
    """Return the tool registry for the resolved *mode*, building on first call."""
    effective = _resolve_mode(mode)
    if effective not in _registry_by_mode:
        _registry_by_mode[effective] = build_tool_registry(mode=effective)
    return _registry_by_mode[effective]


def _get_embeddings():
    """Return the shared embeddings client, building it on first call."""
    global _embeddings
    if _embeddings is None:
        _embeddings = build_embeddings()
    return _embeddings


def _get_vectorstore(
    faiss_dir: Optional[str] = None,
    rebuild:   bool          = False,
    mode:      Optional[str] = None,
):
    """Return the FAISS vectorstore for *mode*, building / loading on first call.

    Each mode has its own FAISS directory (``_FAISS_DIR_BY_MODE``) so the
    indexes for ``"full"`` and ``"node_only"`` never collide.

    The ``"no_ner"`` mode never touches FAISS — callers must guard against
    invoking this function in that mode.
    """
    effective = _resolve_mode(mode)
    if effective == "no_ner":
        raise RuntimeError(
            "_get_vectorstore() is not callable in NER mode 'no_ner' — "
            "the ReAct agent is bypassed entirely."
        )

    target_dir = faiss_dir or _FAISS_DIR_BY_MODE[effective]

    cached = _vectorstore_by_mode.get(effective)
    if cached is None or rebuild:
        cached = get_or_build_tools_faiss(
            registry   = _get_registry(mode=effective),
            faiss_dir  = target_dir,
            rebuild    = rebuild,
            embeddings = _get_embeddings(),
        )
        _vectorstore_by_mode[effective] = cached
    return cached


# ──────────────────────────────────────────────────────────────────────────────
# 5. Tool selection
# ──────────────────────────────────────────────────────────────────────────────

def select_tools_for_query(
    user_query:           str,
    top_k:                int  = DEFAULT_TOP_K,
    faiss_dir:            Optional[str] = None,
    rebuild:              bool = False,
    filter_connectivity:  bool = True,
    verbose:              bool = False,
    mode:                 Optional[str] = None,
) -> List[BaseTool]:
    """
    Use FAISS semantic search to select the *top_k* most relevant tools for
    *user_query* from the full tool registry, then optionally prune relation
    tools that are not connected to any selected node label.

    Parameters
    ----------
    user_query           : Natural-language question or instruction.
    top_k                : Maximum number of tools to return (default 5).
    faiss_dir            : Directory of the FAISS index (built automatically if absent).
    rebuild              : Force-rebuild the FAISS index even if it already exists.
    filter_connectivity  : When *True* (default), call
                           :func:`filter_tools_by_connectivity` after FAISS
                           search to remove relation tools whose node labels
                           don't overlap with the selected node tools.
                           Set to *False* to keep all FAISS hits as-is.
    verbose              : Print ranked hits and filter decisions to stdout.

    Returns
    -------
    List[BaseTool]
        Ordered from most to least relevant.  May be fewer than *top_k* if
        the registry is smaller, duplicates are collapsed, or connectivity
        filtering removes unrelated relation tools.

    Example
    -------
    >>> tools = select_tools_for_query("movies released in 2015", top_k=5)
    >>> [t.name for t in tools]
    ['get_movie_released', 'get_movie_title', 'get_acted_in_roles']
    # get_follows_relation was dropped — FOLLOWS connects Person→Person,
    # not connected to Movie which is the only selected node label.
    """
    effective_mode = _resolve_mode(mode)
    if effective_mode == "no_ner":
        # The agent is bypassed in this mode, so there are no tools to select.
        if verbose:
            print(
                f"\n── Tool selection skipped (NER mode='no_ner') for: "
                f"{user_query!r} ──"
            )
        return []

    vs   = _get_vectorstore(faiss_dir=faiss_dir, rebuild=rebuild, mode=effective_mode)
    hits = search_tools(vs, user_query=user_query, top_l=top_k)

    if verbose:
        print(
            f"\n── Tool selection for: {user_query!r} "
            f"(top_k={top_k}, mode={effective_mode!r}) ──"
        )
        for h in hits:
            print(f"  [{h.rank}] score={h.score:.4f}  {h.func_name}  — {h.description[:80]}")

    tools = hits_to_callables(hits, _get_registry(mode=effective_mode))

    if filter_connectivity:
        tools = filter_tools_by_connectivity(
            tools,
            registry=_get_registry(mode=effective_mode),
            verbose=verbose,
        )

    return tools


# ──────────────────────────────────────────────────────────────────────────────
# 5.5  Connectivity filter — drop relation tools that don't connect to any
#      node label covered by the selected node tools
# ──────────────────────────────────────────────────────────────────────────────

# Pre-compiled patterns used by the helpers below.
_RE_NODE_DESC       = re.compile(r"canonical\s+(\w+)\.(\w+)\s+values")
_RE_STRUCTURAL_DESC = re.compile(
    r"via\s+\(:(\w+)\)-\[:(\w+)\]->\(:(\w+)\)"
)
_RE_ALL_CAPS        = re.compile(r"^[A-Z][A-Z_]+$")   # rel type (e.g. ACTED_IN)
_RE_PASCAL          = re.compile(r"^[A-Z][a-z]\w*$")  # node label (e.g. Movie)


_SCHEMA_META_PATH: str = str(SCHEMA_META)


def _load_rel_connectivity_from_meta(
    meta_path: Union[str, Path] = _SCHEMA_META_PATH,
) -> Optional[Dict[str, Set[str]]]:
    """
    Read ``schema_meta.json`` and return ``{rel_type: {label, …}}`` built from
    the ``endpoints`` field persisted by ``gen_schema_meta.py``.

    Returns
    -------
    dict
        Connectivity map when the meta file exposes the new ``endpoints``
        field on at least one relationship.
    None
        When the file is absent, malformed, or pre-dates the ``endpoints``
        field — in which case callers should fall back to the legacy
        description-parsing path.
    """
    try:
        with open(meta_path, encoding="utf-8") as fh:
            meta = json.load(fh)
    except FileNotFoundError:
        logger.warning(
            "schema_meta.json not found at {!r}; falling back to "
            "description parsing for relationship connectivity. "
            "Run gen_schema_meta.py to regenerate.", meta_path,
        )
        return None
    except json.JSONDecodeError as exc:
        logger.warning(
            "schema_meta.json could not be parsed ({}); falling back to "
            "description parsing for relationship connectivity.", exc,
        )
        return None

    rels = meta.get("relationships") or {}
    if not isinstance(rels, dict) or not rels:
        return None

    conn: Dict[str, Set[str]] = {}
    found_any = False
    for rt, info in rels.items():
        if not isinstance(info, dict):
            continue
        endpoints = info.get("endpoints")
        if not endpoints:
            continue
        found_any = True
        for ep in endpoints:
            if not isinstance(ep, dict):
                continue
            fl = ep.get("from")
            tl = ep.get("to")
            labels = {x for x in (fl, tl) if isinstance(x, str) and x}
            if labels:
                conn.setdefault(rt, set()).update(labels)

    if not found_any:
        logger.warning(
            "schema_meta.json lacks the 'endpoints' field on every "
            "relationship; falling back to description parsing. "
            "Re-run gen_schema_meta.py to regenerate with endpoints."
        )
        return None

    return conn


def _build_rel_connectivity_map(
    registry: Dict[str, BaseTool],
) -> Dict[str, Set[str]]:
    """
    Build a ``{rel_type: {label, …}}`` map describing which node labels each
    relationship type connects.

    Resolution order
    ----------------
    1. **Preferred** — read endpoints directly from ``schema_meta.json``.
       This is the single source of truth and covers *every* relationship
       type, including property-bearing ones (e.g. ``ACTED_IN``,
       ``REVIEWED``) whose connectivity is otherwise unrecoverable from tool
       descriptions because ``gen_tools.py`` does not emit structural
       traversal tools for them.
    2. **Fallback** — scan the registry for structural relation tool
       descriptions matching ``(:X)-[:Y]->(:Z)``.  Used only when
       ``schema_meta.json`` is missing or pre-dates the ``endpoints`` field;
       a warning is emitted recommending regeneration.

    The map is consumed by :func:`_get_tool_node_labels` to resolve the
    connected labels of relationship-property tools whose own descriptions
    don't mention node labels.
    """
    # ── Preferred: schema_meta.json (authoritative) ────────────────────────────
    from_meta = _load_rel_connectivity_from_meta()
    if from_meta is not None:
        return from_meta

    # ── Fallback: description parsing (legacy behaviour) ──────────────────────
    conn: Dict[str, Set[str]] = {}
    for tool_obj in registry.values():
        m = _RE_STRUCTURAL_DESC.search(tool_obj.description or "")
        if m:
            from_label = m.group(1)
            rel_type   = m.group(2)
            to_label   = m.group(3)
            conn.setdefault(rel_type, set()).update({from_label, to_label})
    return conn


def _is_rel_tool(tool_obj: BaseTool) -> bool:
    """
    Return *True* when *tool_obj* is a relation tool (property or structural).

    Heuristic:
    - Structural rel tool  → description contains ``"via (:"``
    - Rel-property tool    → description matches ``"canonical ALL_CAPS.prop"``
    """
    desc = tool_obj.description or ""
    if "via (:" in desc:
        return True
    m = _RE_NODE_DESC.search(desc)
    if m:
        return bool(_RE_ALL_CAPS.match(m.group(1)))
    return False


def _get_tool_node_labels(
    tool_obj: BaseTool,
    rel_conn: Dict[str, Set[str]],
) -> Set[str]:
    """
    Return the set of node labels that *tool_obj* relates to.

    ============== ======================================== =============
    Tool kind      Example description                      Labels
    ============== ======================================== =============
    Node           "canonical Movie.title values"           {"Movie"}
    Structural rel "via (:Person)-[:DIRECTED]->(:Movie)"    {"Person","Movie"}
    Rel property   "canonical ACTED_IN.roles values"        rel_conn["ACTED_IN"]
    ============== ======================================== =============

    Returns an empty set when the tool type cannot be determined.
    """
    desc = tool_obj.description or ""

    # ── Structural rel tool ────────────────────────────────────────────────────
    m = _RE_STRUCTURAL_DESC.search(desc)
    if m:
        return {m.group(1), m.group(3)}          # {from_label, to_label}

    # ── Node tool or rel-property tool ────────────────────────────────────────
    m = _RE_NODE_DESC.search(desc)
    if m:
        word = m.group(1)
        if _RE_ALL_CAPS.match(word):
            # Rel-property tool — look up connected labels from the map
            return rel_conn.get(word, set())
        if _RE_PASCAL.match(word):
            # Node tool
            return {word}

    return set()


def filter_tools_by_connectivity(
    selected_tools: List[BaseTool],
    registry: Optional[Dict[str, BaseTool]] = None,
    verbose: bool = False,
) -> List[BaseTool]:
    """
    Remove relation tools from *selected_tools* whose connected node labels
    have **no overlap** with the node labels already covered by the selected
    node tools.

    Algorithm
    ---------
    1. Build a ``{rel_type: {labels}}`` connectivity map from **all** tools in
       the full registry (structural rel tool docstrings encode the pattern
       ``(:{From})-[:{REL}]->(:{To})``).
    2. Collect the node labels covered by every *node* tool in the selection.
    3. For each *relation* tool in the selection, compute its connected labels
       and test whether they intersect with the node-label set from step 2.
       Drop the relation tool if the intersection is empty.

    Node tools are **always** kept.

    Parameters
    ----------
    selected_tools : Tools returned by :func:`select_tools_for_query`.
    registry       : Full tool registry.  When *None*, the module-level
                     singleton ``_registry`` is used.
    verbose        : Log which tools are dropped and why.

    Returns
    -------
    List[BaseTool]  Filtered tool list, preserving the original order.

    Example
    -------
    Suppose the query is *"movies directed by Spielberg"* and FAISS returns::

        [get_movie_title, get_acted_in_roles, get_follows_relation]

    Node labels from node tools = {``Movie``}

    ========================== ============================ ======
    Relation tool              Connected labels             Action
    ========================== ============================ ======
    ``get_acted_in_roles``     ``{Person, Movie}``          **KEEP**  (Movie ∈ {Movie})
    ``get_follows_relation``   ``{Person}``                 **DROP**  (Person ∉ {Movie})
    ========================== ============================ ======

    Result: ``[get_movie_title, get_acted_in_roles]``
    """
    if registry is None:
        registry = _get_registry()

    # Build {rel_type → {label, …}} from the full registry
    rel_conn = _build_rel_connectivity_map(registry)

    # ── Step 1: collect labels from selected NODE tools ────────────────────────
    selected_node_labels: Set[str] = set()
    for tool_obj in selected_tools:
        if not _is_rel_tool(tool_obj):
            labels = _get_tool_node_labels(tool_obj, rel_conn)
            selected_node_labels.update(labels)

    if not selected_node_labels:
        # Cannot determine node context → skip filtering to avoid dropping
        # all relation tools incorrectly.
        if verbose:
            logger.info(
                "filter_tools_by_connectivity: no node labels identified "
                "in selected tools — skipping filter."
            )
        return selected_tools

    # ── Step 2: filter ─────────────────────────────────────────────────────────
    kept:    List[BaseTool] = []
    dropped: List[BaseTool] = []

    for tool_obj in selected_tools:
        if not _is_rel_tool(tool_obj):
            kept.append(tool_obj)          # node tools are always kept
            continue

        labels = _get_tool_node_labels(tool_obj, rel_conn)
        if labels & selected_node_labels:
            kept.append(tool_obj)
        else:
            dropped.append(tool_obj)

    if verbose:
        if dropped:
            logger.info(
                f"filter_tools_by_connectivity: "
                f"selected node labels = {selected_node_labels}  |  "
                f"dropped {len(dropped)} unconnected relation tool(s): "
                f"{[t.name for t in dropped]}"
            )
        else:
            logger.info(
                f"filter_tools_by_connectivity: "
                f"selected node labels = {selected_node_labels}  |  "
                f"all {len(kept)} relation tools are connected — nothing dropped."
            )

    return kept


def _render_tool_section(tools: List[BaseTool]) -> str:
    """Render the 'Available tools' block for exactly *tools*, grouped
    into node / relationship-property / structural sections — matching
    the format that gen_system_prompt.py produces for the static NER_SP."""
    node_lines:   List[str] = []
    rel_p_lines:  List[str] = []
    struct_lines: List[str] = []

    for t in tools:
        desc = (t.description or "").strip()
        line = f"  {t.name:<34}  {desc[:72]}"

        if "via (:" in desc:
            struct_lines.append(line)
            continue

        m = _RE_NODE_DESC.search(desc)
        if m and _RE_ALL_CAPS.match(m.group(1)):
            rel_p_lines.append(line)
        else:
            node_lines.append(line)

    parts: List[str] = []
    if node_lines:
        parts.append("  ── Node property tools ──\n" + "\n".join(node_lines))
    if rel_p_lines:
        parts.append("  ── Relationship property tools ──\n" + "\n".join(rel_p_lines))
    if struct_lines:
        parts.append("  ── Structural traversal tools ──\n" + "\n".join(struct_lines))

    return "\n\n".join(parts) if parts else "  (no tools selected)"


_TOOL_LIST_PLACEHOLDER = "{tool_list}"


def _build_dynamic_prompt(selected_tools: List[BaseTool]) -> str:
    """Return a copy of NER_SP whose ``{tool_list}`` placeholder has been
    replaced with a rendering of *selected_tools*.

    ``gen_system_prompt.py`` emits NER_SP with a ``{tool_list}`` token in
    the "Available tools" section instead of a baked-in tool list, because
    the actual tools available to the NER agent are decided at runtime
    (after FAISS selection + connectivity filtering).  This function does
    the runtime substitution.

    Fallbacks (in order):
      1. Substitute the ``{tool_list}`` placeholder if present.
      2. Otherwise, treat NER_SP as a legacy prompt with an inline tool
         list and replace the section between "Available tools" and
         "Extraction rules" via regex.  Warn so the maintainer knows the
         prompt is stale.
      3. As a last resort, return NER_SP unchanged with a warning.
    """
    tool_block = _render_tool_section(selected_tools)

    # Preferred path — placeholder substitution.
    if _TOOL_LIST_PLACEHOLDER in NER_SP:
        return NER_SP.replace(_TOOL_LIST_PLACEHOLDER, tool_block, 1)

    # Legacy path — older prompts that baked the tool list inline.
    new_prompt, n = re.subn(
        r"(Available tools\n[─\-]+\n).*?(\n\nExtraction rules)",
        lambda m: m.group(1) + tool_block + m.group(2),
        NER_SP,
        count=1,
        flags=re.DOTALL,
    )
    if n > 0:
        logger.warning(
            "_build_dynamic_prompt: NER_SP has no {tool_list} placeholder; "
            "falling back to legacy regex substitution. "
            "Re-run `python gen_system_prompt.py` to regenerate prompts.py."
        )
        return new_prompt

    logger.warning(
        "_build_dynamic_prompt: could not locate {tool_list} placeholder "
        "or 'Available tools' section in NER_SP — falling back to "
        "unmodified NER_SP."
    )
    return NER_SP


# ──────────────────────────────────────────────────────────────────────────────
# 6. Agent factory with auto tool selection
# ──────────────────────────────────────────────────────────────────────────────

def create_agent_auto(
    user_query:          str,
    top_k:               int  = DEFAULT_TOP_K,
    faiss_dir:           Optional[str] = None,
    rebuild:             bool = False,
    filter_connectivity: bool = True,
    verbose:             bool = False,
    llm_obj:             Optional[BaseChatModel] = None,
    mode:                Optional[str] = None,
):
    """
    Build a LangGraph ReAct agent wired with only the tools that are
    semantically relevant to *user_query*.

    First calls :func:`select_tools_for_query` (which internally runs
    :func:`filter_tools_by_connectivity`) so the agent never receives
    relation tools that are disconnected from the selected node labels.

    Parameters
    ----------
    user_query           : The user's natural-language question.
    top_k                : How many FAISS-selected tools to start with (default 5).
    faiss_dir            : FAISS index directory.
    rebuild              : Force-rebuild the FAISS index.
    filter_connectivity  : Drop relation tools unconnected to selected node
                           labels (default *True*).
    verbose              : Log selected tools and filter decisions.
    llm_obj              : Optional ``BaseChatModel`` to drive the NER agent.
                           When *None*, the module-level default ``llm``
                           (auto-resolved by ``agent_helper.build_llm``) is
                           used.  Pass e.g.
                           ``build_llm(provider="anthropic", model="claude-opus-4-20250514")``
                           to run the NER agent on Claude Opus instead of GPT.

    Returns
    -------
    CompiledStateGraph  A LangGraph ReAct agent ready to ``.stream()``.

    Raises
    ------
    RuntimeError
        If no relevant tools remain after selection and filtering.
    """
    effective_mode = _resolve_mode(mode)
    if effective_mode == "no_ner":
        raise RuntimeError(
            "create_agent_auto() must not be called in NER mode 'no_ner' — "
            "the ReAct agent is bypassed entirely.  Call ask_auto() instead, "
            "which short-circuits NER and goes straight to Cypher generation."
        )

    selected_tools = select_tools_for_query(
        user_query          = user_query,
        top_k               = top_k,
        faiss_dir           = faiss_dir,
        rebuild             = rebuild,
        filter_connectivity = filter_connectivity,
        verbose             = verbose,
        mode                = effective_mode,
    )

    if not selected_tools:
        raise RuntimeError(
            f"No tools selected for query {user_query!r} (mode={effective_mode!r}). "
            "Ensure generated tool files exist and the FAISS index is populated."
        )

    if verbose:
        names = [t.name for t in selected_tools]
        logger.info(f"Agent assembled with {len(selected_tools)} tools: {names}")

    return create_react_agent(
        model       = llm_obj if llm_obj is not None else _ner_llm,
        tools       = selected_tools,
        prompt      = _build_dynamic_prompt(selected_tools),
        checkpointer= False,
    )


# ──────────────────────────────────────────────────────────────────────────────
# 7. Output parsing  (identical to ner_agent.py)
# ──────────────────────────────────────────────────────────────────────────────

def _to_list(v: Any) -> List[Any]:
    """Normalise any scalar / list-ish value into a plain Python list."""
    if v is None:
        return []
    if isinstance(v, (list, tuple, set)):
        return list(v)
    return [v]


def extract_content(input_string: str) -> str:
    """
    Parse the agent's final message into a canonical JSON string of the form::

        {"Label.property": [values, ...]}

    Returns ``"{}"`` on any failure so downstream code never crashes.
    """
    if not input_string:
        return "{}"
    text = input_string.strip()

    # Strip optional markdown fences
    m = re.search(r"```(?:python|json)?\s*(.*?)\s*```", text, re.DOTALL)
    if m:
        text = m.group(1).strip()

    parsed: Optional[Dict[str, Any]] = None
    for loader in (json.loads, ast.literal_eval):
        try:
            obj = loader(text)
            if isinstance(obj, dict):
                parsed = obj
                break
        except Exception:
            continue

    if parsed is None:
        return "{}"

    normalized = {k: _to_list(v) for k, v in parsed.items()}
    return json.dumps(normalized, ensure_ascii=False)


# ──────────────────────────────────────────────────────────────────────────────
# 8. Main entry points
# ──────────────────────────────────────────────────────────────────────────────

def get_ner_auto(
    prompt:    str,
    top_k:     int  = DEFAULT_TOP_K,
    faiss_dir: Optional[str] = None,
    rebuild:   bool = False,
    verbose:   bool = False,
    llm_obj:   Optional[BaseChatModel] = None,
    mode:      Optional[str] = None,
) -> str:
    """
    Run the NER agent on *prompt* with auto-selected tools and return a
    canonical JSON string.

    This is the ``ner_agent_auto`` counterpart of ``ner_agent.get_ner()``.
    The return format is identical::

        '{"Movie.title": ["The Matrix"], "Movie.released": [1999]}'

    Parameters
    ----------
    prompt    : User's natural-language question.
    top_k     : Number of tools to select (default 5).
    faiss_dir : FAISS index directory.
    rebuild   : Force-rebuild the FAISS tool index.
    verbose   : Stream agent messages and print tool-selection details.
    llm_obj   : Optional ``BaseChatModel`` to drive the NER agent.
                When *None*, the module-level default ``llm`` is used.

    Returns
    -------
    str  Canonical JSON string (``"{}"`` on failure).
    """
    effective_mode = _resolve_mode(mode)
    if effective_mode == "no_ner":
        # Short-circuit: skip the ReAct agent entirely and return the empty
        # entity dict.  Downstream code (ask_auto / cypher prompt) treats
        # an empty dict as "no entity hints" and lets the LLM generate
        # Cypher purely from the question + schema.
        if verbose:
            logger.info(
                "get_ner_auto: NER mode='no_ner' — skipping ReAct agent, "
                "returning empty entity dict."
            )
        return "{}"

    inputs      = {"messages": [("user", prompt)]}
    agent_graph = create_agent_auto(
        user_query = prompt,
        top_k      = top_k,
        faiss_dir  = faiss_dir,
        rebuild    = rebuild,
        verbose    = verbose,
        llm_obj    = llm_obj,
        mode       = effective_mode,
    )

    message = None
    for msgs in agent_graph.stream(inputs, stream_mode="values"):
        tool_msgs = [m for m in msgs["messages"] if isinstance(m, ToolMessage)]
        message   = msgs["messages"][-1]

        if verbose:
            if isinstance(message, tuple):
                logger.info(message)
            else:
                message.pretty_print()
            for tm in tool_msgs:
                logger.info(tm.content)

    if message is None:
        return "{}"

    return extract_content(message.content)


def get_ner_dict_auto(
    prompt:    str,
    top_k:     int  = DEFAULT_TOP_K,
    faiss_dir: Optional[str] = None,
    rebuild:   bool = False,
    verbose:   bool = False,
    llm_obj:   Optional[BaseChatModel] = None,
    mode:      Optional[str] = None,
) -> Dict[str, List[Any]]:
    """
    Convenience wrapper around :func:`get_ner_auto` that returns a Python dict
    instead of a JSON string.

    Returns
    -------
    dict  ``{"Label.property": [values, ...]}`` or ``{}`` on failure.
    """
    raw = get_ner_auto(
        prompt    = prompt,
        top_k     = top_k,
        faiss_dir = faiss_dir,
        rebuild   = rebuild,
        verbose   = verbose,
        llm_obj   = llm_obj,
        mode      = mode,
    )
    try:
        obj = json.loads(raw)
        return obj if isinstance(obj, dict) else {}
    except Exception:
        return {}


# ──────────────────────────────────────────────────────────────────────────────
# 9. Full pipeline: NER → Cypher → Neo4j → answer
# ──────────────────────────────────────────────────────────────────────────────

# Cypher generation prompt template.
# ``{relevant_entities}`` is filled at runtime with the NER output.
# ``{schema}`` and ``{question}`` are handled by GraphCypherQAChain.
CYPHER_TEMPLATE = """\
Task: Generate a Cypher statement to query a Neo4j database.

Rules:
- Use ONLY relationship types, labels, and properties present in the provided schema.
- Do NOT invent properties or relationship types not in the schema.
- Return ONLY the Cypher query (no backticks, no prose, no explanation).
- Prefer safe read patterns; avoid destructive operations (no WRITE, MERGE, DELETE).

Cypher rules for literals:
- DO NOT use Cypher parameters ($param). Inline all values as literals.
  GOOD: WHERE toLower(m.title) = toLower("Inception")
  BAD:  WHERE toLower(m.title) = toLower($movie_title)
- Inline numbers directly: 2015
- Inline strings with double quotes: "Inception", "CA"

Cypher rules for list-typed properties (CRITICAL):
- When the schema declares a property as a list/array type
  (e.g. StringArray, FloatArray) -- for example ACTED_IN.roles is a
  StringArray of character names -- the NER pipeline emits the corresponding
  entity-filter value as a LIST OF LISTS:
      "Label.prop": [[v1], [v2], ...]
  The outer list is the standard "candidate values" wrapper; each inner list
  is the list-typed value itself.
- For each inner value vi, emit a membership predicate `vi IN <alias>.<prop>`
  (or `vi IN n.<prop>` for node properties).  Combine multiple values with OR.
    GOOD: "Neo" IN r.roles
    GOOD: ("Neo" IN r.roles OR "Morpheus" IN r.roles)
    BAD:  ["Neo"] IN r.roles               (list-in-list never matches a string array)
    BAD:  r.roles CONTAINS "Neo"           (CONTAINS is a string-substring operator)
- Never paste the inner list literal into the predicate; always unwrap to its
  scalar element(s).
- For non-list (scalar) properties, keep the existing `=` / `toLower(...)` /
  numeric-comparison behaviour unchanged.  The new rule applies ONLY when the
  schema marks the target property as an array type.

Examples
- - - - -
# 1. List-typed relationship property -- single value
Question: Who played Neo in The Matrix?
Schema-relevant entity filters:
  "Movie.title": ["The Matrix"], "ACTED_IN.roles": [["Neo"]]
Cypher:
  MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix") AND "Neo" IN r.roles
  RETURN p.name AS person_name
  LIMIT 25

# 2. List-typed relationship property -- multiple values
Question: Who played Neo or Morpheus in The Matrix?
Schema-relevant entity filters:
  "Movie.title": ["The Matrix"], "ACTED_IN.roles": [["Neo"], ["Morpheus"]]
Cypher:
  MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix")
        AND ("Neo" IN r.roles OR "Morpheus" IN r.roles)
  RETURN DISTINCT p.name AS person_name
  LIMIT 25

# 3. Scalar relationship property -- DO NOT apply the IN-expansion rule
Question: Which reviewers gave The Matrix a rating above 90?
Schema-relevant entity filters:
  "Movie.title": ["The Matrix"], "REVIEWED.rating": [90]
Cypher:
  MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix") AND r.rating > 90
  RETURN p.name AS person_name, r.rating AS rating
  LIMIT 25

Schema:
{schema}

Schema-relevant attribute and value pairs extracted from the question
(incorporate ALL of the following in the WHERE clause):
{relevant_entities}

User question:
{question}
"""


def ask_auto(
    prompt:        str,
    top_k:         int  = DEFAULT_TOP_K,
    faiss_dir:     Optional[str] = None,
    rebuild:       bool = False,
    verbose:       bool = False,
    ner_llm:       Optional[BaseChatModel] = None,
    qa_llm:        Optional[BaseChatModel] = None,
    cypher_llm:    Optional[BaseChatModel] = None,
    mode:          Optional[str] = None,
) -> Dict[str, Any]:
    """
    Full end-to-end pipeline with auto tool selection:

    1. **NER** — :func:`get_ner_auto` extracts canonical entity values using
       only the FAISS-selected, connectivity-filtered tools.
    2. **Cypher generation** — injects the extracted entities into
       ``CYPHER_TEMPLATE`` and passes it to ``GraphCypherQAChain`` which asks
       the LLM to write a Cypher query against the actual schema.
    3. **Execution** — the chain runs the Cypher query on the connected
       Neo4j graph and formats the rows into a natural-language answer.

    The pipeline uses **three independent LLM slots** so experiments can mix
    providers freely (e.g. GPT for NER, Claude Opus for Cypher):

    ============ ========================================================
    Slot          Role
    ============ ========================================================
    ``ner_llm``   Drives the LangGraph ReAct agent that does entity NER.
    ``qa_llm``    "Value-linking" LLM passed to ``GraphCypherQAChain.from_llm``
                  via ``llm=`` — formats Cypher results into natural language.
    ``cypher_llm`` Generates the Cypher query from the schema + question.
    ============ ========================================================

    Each slot defaults to the **configured singleton** from ``config.py``
    when *None* is passed (``NER_LLM_CONFIG`` / ``QA_LLM_CONFIG`` /
    ``CYPHER_LLM_CONFIG``), so callers don't need to thread LLM objects
    through their code — just edit ``config.py`` once and re-import.

    Parameters
    ----------
    prompt    : User's natural-language question.
    top_k     : Number of tools to select via FAISS (default 5).
    faiss_dir : FAISS tool-index directory.
    rebuild   : Force-rebuild the FAISS index before running.
    verbose   : Stream agent messages, print tool-selection decisions, and
                enable ``GraphCypherQAChain`` verbose mode.
    ner_llm    : LLM for the NER agent stage.
                 Defaults to ``agent_helper.ner_llm`` (config.NER_LLM_CONFIG).
    qa_llm     : LLM for the answer-formatting (value-linking) stage in
                 ``GraphCypherQAChain``.
                 Defaults to ``agent_helper.qa_llm`` (config.QA_LLM_CONFIG).
    cypher_llm : LLM for the Cypher-generation stage in
                 ``GraphCypherQAChain``.
                 Defaults to ``agent_helper.cypher_llm`` (config.CYPHER_LLM_CONFIG).

    Returns
    -------
    dict with keys:

    =========== ============================================================
    ``entities`` Canonical entity JSON string, e.g.
                 ``'{"Movie.released": [2015]}'``
    ``cypher``   The Cypher query generated by the LLM.
    ``result``   Natural-language answer produced by the QA LLM.
    ``context``  Raw list of dicts returned by Neo4j before formatting.
    =========== ============================================================

    Example
    -------
    >>> # Default — all three slots use the singletons built from config.py.
    >>> # Edit NER_LLM_CONFIG / QA_LLM_CONFIG / CYPHER_LLM_CONFIG in config.py
    >>> # to switch providers; no other code changes are required.
    >>> out = ask_auto("How many movies were released before 2000?")

    >>> # One-off override: keep config.py defaults for NER + QA, but try
    >>> # Claude Opus for Cypher generation only.
    >>> from agent_helper import build_llm
    >>> opus = build_llm(provider="anthropic", model="claude-opus-4-20250514")
    >>> out  = ask_auto(
    ...     "How many movies were released before 2000?",
    ...     cypher_llm = opus,
    ... )
    """
    # ── Resolve LLM slots ─────────────────────────────────────────────────────
    # Each slot defaults to the configured singleton built from config.py:
    #     ner_llm    → config.NER_LLM_CONFIG
    #     qa_llm     → config.QA_LLM_CONFIG
    #     cypher_llm → config.CYPHER_LLM_CONFIG
    # Pass an explicit ``BaseChatModel`` to override at runtime.
    ner_llm_eff    = ner_llm    if ner_llm    is not None else _ner_llm
    qa_llm_eff     = qa_llm     if qa_llm     is not None else _qa_llm
    cypher_llm_eff = cypher_llm if cypher_llm is not None else _cypher_llm

    # ── Resolve NER mode ──────────────────────────────────────────────────────
    # "full"      → register every generated tool, run the ReAct NER agent.
    # "node_only" → register only generated_node_tools, run the ReAct agent.
    # "no_ner"    → bypass the agent entirely; entities = "{}".
    effective_mode = _resolve_mode(mode)
    if verbose:
        print(f"\n── NER mode ────────────────────────────────────────────────────────")
        print(f"  {effective_mode}")

    # ── Step 1: entity extraction (NER) ───────────────────────────────────────
    if effective_mode == "no_ner":
        entities = "{}"
        if verbose:
            print(
                "\n── Extracted entities ──────────────────────────────────────────────"
            )
            print(f"  {entities}  (NER skipped — mode='no_ner')")
    else:
        entities = get_ner_auto(
            prompt    = prompt,
            top_k     = top_k,
            faiss_dir = faiss_dir,
            rebuild   = rebuild,
            verbose   = verbose,
            llm_obj   = ner_llm_eff,
            mode      = effective_mode,
        )
        if verbose:
            print(f"\n── Extracted entities ──────────────────────────────────────────────")
            print(f"  {entities}")

    # ── Step 2: build the filled Cypher prompt ────────────────────────────────
    # Escape curly braces in the entity JSON so PromptTemplate doesn't treat
    # them as placeholder markers (e.g. {"Movie.released": [2015]} → safe).
    safe_entities = entities.replace("{", "{{").replace("}", "}}")
    filled = CYPHER_TEMPLATE.replace("{relevant_entities}", safe_entities)

    cypher_prompt = PromptTemplate(
        input_variables=["schema", "question"],
        template=filled,
    )

    # ── Step 3: build GraphCypherQAChain and run ──────────────────────────────
    chain = GraphCypherQAChain.from_llm(
        graph                    = neo4j_graph,
        llm                      = qa_llm_eff,      # value linking LLM
        cypher_llm               = cypher_llm_eff,  # Cypher generation LLM
        cypher_prompt            = cypher_prompt,
        verbose                  = verbose,
        allow_dangerous_requests = True,
        return_intermediate_steps= True,
    )

    response = chain.invoke({"query": prompt})

    # ── Step 4: extract Cypher + raw context from intermediate steps ──────────
    cypher_query: str  = ""
    context:      list = []
    for step in response.get("intermediate_steps", []):
        if isinstance(step, dict):
            if "query" in step and not cypher_query:
                cypher_query = str(step["query"]).strip()
            if "context" in step:
                context = step["context"]

    result = str(response.get("result", "")).strip()

    if verbose:
        print(f"\n── Generated Cypher ────────────────────────────────────────────────")
        print(f"  {cypher_query}")
        print(f"\n── Answer ──────────────────────────────────────────────────────────")
        print(f"  {result}")

    return {
        "entities": entities,
        "cypher":   cypher_query,
        "result":   result,
        "context":  context,
        "mode":     effective_mode,
    }


# ──────────────────────────────────────────────────────────────────────────────
# 10. Utility: rebuild the FAISS index on demand
# ──────────────────────────────────────────────────────────────────────────────

def _drop_embedding_tool_names(registry: Dict[str, BaseTool]) -> Dict[str, BaseTool]:
    """
    Defense-in-depth filter applied immediately before FAISS indexing.

    Drops any tool whose name ends in ``_embedding`` or ``_vector``. This is
    redundant with the schema-layer filter in ``tools.gen_tools`` (which is
    the real fix), but costs nothing and protects against:
      • hand-written tools that accidentally use the suffix,
      • stale ``generated_*.py`` files from before the schema-layer fix,
      • future drift if a new code path bypasses ``gen_tools`` entirely.
    """
    filtered: Dict[str, BaseTool] = {}
    for name, tool in registry.items():
        lower = name.lower()
        if lower.endswith("_embedding") or lower.endswith("_vector"):
            logger.info(
                f"[ner_agent_auto] FAISS pre-index filter: dropping tool "
                f"{name!r} (suffix _embedding/_vector)"
            )
            continue
        filtered[name] = tool
    return filtered


def _purge_faiss_dir(target_dir: str) -> None:
    """
    Remove the FAISS index directory and every artifact under it, in place.

    The FAISS index is a pure derivative of the current schema. It is
    rebuilt from scratch on every call to :func:`rebuild_tools_faiss` —
    resumability on partial failure is handled in the embedding-backfill
    layer (``embedding_helper.backfill_embeddings``), NOT here.

    Why a full rmtree instead of relying on ``FAISS.save_local()``'s
    overwrite of ``index.faiss`` + ``index.pkl``:
      • ``save_local`` only rewrites those two files — any orphan
        artifact (e.g. ``.DS_Store``, a stale fingerprint file from a
        future PR, half-renamed experimental files) survives silently.
      • Reuse of a schema-derived artifact across schema changes is a
        known bug source. Clean rebuild is the only behaviour we want.
      • CypherBench databases are tiny (1k–50k nodes). The FAISS rebuild
        cost is dominated by the embedding API call, which the registry
        already requires regardless of disk state. Deleting first costs
        microseconds and adds zero retry burden.
    """
    p = Path(target_dir)
    if not p.exists():
        logger.info(
            f"[ner_agent_auto] FAISS purge: nothing to delete at {target_dir!r}"
        )
        return

    if p.is_dir():
        # List contents before deletion so the log shows exactly what was
        # blown away — useful when debugging a "stale orphan" report.
        try:
            entries = sorted(child.name for child in p.iterdir())
        except OSError:
            entries = []
        for name in entries:
            logger.info(
                f"[ner_agent_auto] FAISS purge: removing {target_dir}/{name}"
            )
        shutil.rmtree(target_dir, ignore_errors=True)
    else:
        # Defensive — should never happen because we always point at a dir,
        # but cover it in case a future caller passes an explicit file.
        logger.info(f"[ner_agent_auto] FAISS purge: removing file {target_dir!r}")
        p.unlink(missing_ok=True)


def rebuild_tools_faiss(
    faiss_dir: Optional[str] = None,
    mode:      Optional[str] = None,
) -> int:
    """
    Force-rebuild the tool FAISS index for the given NER *mode* from the
    current generated tool files.

    Call this after re-running ``gen_tools.py`` to pick up schema changes,
    or after switching ``config.NER_MODE`` between ``"full"`` and
    ``"node_only"`` so the per-mode index reflects the new tool set.

    The ``"no_ner"`` mode raises :class:`RuntimeError` because there is
    nothing to index in that mode.

    FAISS index is a pure derivative of the current schema. It is rebuilt
    from scratch every run. Resumability on partial failure is handled in
    the embedding-backfill layer, not here. The target directory is
    purged before rebuild so orphan files from prior runs (or from a
    different graph database) cannot leak through.

    Returns
    -------
    int  Number of tools indexed.
    """
    effective = _resolve_mode(mode)
    if effective == "no_ner":
        raise RuntimeError(
            "rebuild_tools_faiss() is not callable in NER mode 'no_ner'."
        )

    target_dir = faiss_dir or _FAISS_DIR_BY_MODE[effective]

    # Step 1 — purge any prior on-disk index BEFORE building the new one.
    # See _purge_faiss_dir for the full rationale.
    _purge_faiss_dir(target_dir)

    # Step 2 — build a fresh registry from the freshly regenerated tool
    # modules.  build_tool_registry() reloads the modules so on-disk
    # changes from gen_tools.py are picked up immediately.
    fresh_registry = build_tool_registry(mode=effective)

    # Defense-in-depth: strip any embedding/vector tools that slipped through
    # the schema-layer filter in tools.gen_tools (e.g. from a stale generated
    # module or a hand-written tool). See _drop_embedding_tool_names.
    fresh_registry = _drop_embedding_tool_names(fresh_registry)
    _registry_by_mode[effective] = fresh_registry      # reload cached registry

    # Step 3 — rebuild the on-disk FAISS index from scratch. After the
    # purge above, get_or_build_tools_faiss() always takes the build path
    # (rebuild=True is belt-and-braces — the directory is empty anyway).
    _vectorstore_by_mode[effective] = get_or_build_tools_faiss(
        registry   = fresh_registry,
        faiss_dir  = target_dir,
        rebuild    = True,
        embeddings = _get_embeddings(),
    )
    return len(fresh_registry)


# ──────────────────────────────────────────────────────────────────────────────
# 11. Quick demo / smoke-test
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(
        description="Full pipeline: NER (auto tool selection) → Cypher → answer."
    )
    ap.add_argument("prompt", nargs="?",
                    default="How many movies were released before 2000?")
    ap.add_argument("--top-k",    type=int,  default=DEFAULT_TOP_K,
                    help=f"Tools to select per query (default {DEFAULT_TOP_K})")
    ap.add_argument("--rebuild",  action="store_true",
                    help="Force-rebuild the FAISS tool index before running")
    ap.add_argument("--ner-only", action="store_true",
                    help="Run only the NER step (skip Cypher + Neo4j)")
    ap.add_argument("--mode", "--ner-mode", dest="mode",
                    choices=NER_MODES, default=None,
                    help=f"NER pipeline mode (overrides config.NER_MODE={NER_MODE!r}). "
                         f"One of {NER_MODES}.")
    ap.add_argument("--verbose",  action="store_true",
                    help="Print tool-selection, agent trace, and chain details")
    args = ap.parse_args()

    effective_mode = _resolve_mode(args.mode)
    print(f"\nPrompt : {args.prompt}")
    print(f"top_k  : {args.top_k}")
    print(f"mode   : {effective_mode}")
    print(f"rebuild: {args.rebuild}\n")

    # ── Step 1: show which tools were selected ────────────────────────────────
    if effective_mode == "no_ner":
        print("── Tool selection skipped (mode='no_ner') ──────────────────────────")
    else:
        print("── Selected tools (after connectivity filter) ──────────────────────")
        tools = select_tools_for_query(
            user_query = args.prompt,
            top_k      = args.top_k,
            rebuild    = args.rebuild,
            verbose    = True,
            mode       = effective_mode,
        )
        for i, t in enumerate(tools, 1):
            print(f"  {i}. {t.name:35s}  {t.description[:60]}")

    if args.ner_only:
        # ── NER only ─────────────────────────────────────────────────────────
        print("\n── NER result ──────────────────────────────────────────────────────")
        entities = get_ner_auto(
            prompt  = args.prompt,
            top_k   = args.top_k,
            rebuild = args.rebuild,
            verbose = args.verbose,
            mode    = effective_mode,
        )
        print("entities:", entities)
    else:
        # ── Full pipeline: NER → Cypher → Neo4j → answer ─────────────────────
        print("\n── Full pipeline (NER + Cypher + Neo4j) ────────────────────────────")
        out = ask_auto(
            prompt  = args.prompt,
            top_k   = args.top_k,
            rebuild = args.rebuild,
            verbose = args.verbose,
            mode    = effective_mode,
        )
        print("\nentities :", out["entities"])
        print("cypher   :", out["cypher"])
        print("result   :", out["result"])
