# -*- coding: utf-8 -*-
"""
paths.py
========
Centralized filesystem-layout constants for the t2c project.

All paths are :class:`pathlib.Path` objects anchored at the repository root
(the directory containing this file), so they resolve identically regardless
of the caller's current working directory.

Keep this file separate from ``config.py``: ``config.py`` holds runtime
settings / env-driven knobs, while this file holds the *physical layout* of
artifacts on disk. Mixing the two is what allowed the original bare-string
output paths to drift from the on-disk layout after the 2026-04-28 refactor.

Conventions
-----------
- Module-level names are :class:`pathlib.Path`.
- Directories end without a trailing slash; callers should `mkdir(parents=True,
  exist_ok=True)` before writing into a directory if it may not yet exist.
- File constants point at the canonical home for each artifact. If a script
  needs to read a stale or alternate copy, it should pass a different path
  explicitly rather than rebinding these names.
"""

from __future__ import annotations

from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Repository anchor
# ──────────────────────────────────────────────────────────────────────────────

REPO_ROOT: Path = Path(__file__).resolve().parent

# ──────────────────────────────────────────────────────────────────────────────
# Generated Python modules (tracked in git, regenerated by tools/gen_tools.py
# and schema/gen_system_prompt.py)
# ──────────────────────────────────────────────────────────────────────────────

GENERATED_NODE_TOOLS: Path = REPO_ROOT / "generated" / "generated_node_tools.py"
GENERATED_REL_TOOLS:  Path = REPO_ROOT / "generated" / "generated_rel_tools.py"
PROMPTS:              Path = REPO_ROOT / "agent" / "prompts.py"

# ──────────────────────────────────────────────────────────────────────────────
# Schema artifacts (gitignored runtime data, lives under schema_data/)
# ──────────────────────────────────────────────────────────────────────────────

SCHEMA_META:      Path = REPO_ROOT / "schema_data" / "schema_meta.json"
SCHEMA_NODES_CSV: Path = REPO_ROOT / "schema_data" / "schema_nodes.csv"
SCHEMA_RELS_CSV:  Path = REPO_ROOT / "schema_data" / "schema_relations.csv"

# ──────────────────────────────────────────────────────────────────────────────
# FAISS index for the auto-built tool registry (gitignored, lives under
# generated/faiss/). The "_node_only" sibling is appended at the call site by
# ner_agent_auto.py based on NER mode.
# ──────────────────────────────────────────────────────────────────────────────

FAISS_AUTO_DIR: Path = REPO_ROOT / "generated" / "faiss" / "tools_auto"
