#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_agent_helpers.py
=====================
Pure-unit tests for the NER agent helper changes:

  • Fix #1 — _adaptive_top_k (ner_agent_auto)
  • Fix #2 — _drop_embedding_tool_names L1/L2/L3 (ner_agent_auto)
  • Fix #4 — _normalize_for_match / _split_entity_candidates /
             best_candidate_by_similarity / _clean_entity_response
             whitespace collapse (agent.agent_helper)
  • Fix #5 — _token_fuzziness + _lucene_query_from_phrase AUTO mode
             (neo4j_lib.neo4j_search)
  • Fix #6 — _wrap_tools_with_failure_tracking short-circuit
             (ner_agent_auto)

All tests are offline: no Neo4j connection, no LLM call, no FAISS index.
Modules that import heavy deps at module load time (ner_agent_auto pulls in
langchain_neo4j → GraphCypherQAChain) are stubbed via importlib.util so
the tests can run in any environment with just stdlib + langchain_core.

Run directly:  ``python tests/test_agent_helpers.py``
Or with pytest: ``pytest tests/test_agent_helpers.py``
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

# Make the repo root importable when this file is run directly.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# ──────────────────────────────────────────────────────────────────────────────
# Test isolation: agent.agent_helper and ner_agent_auto eagerly initialise
# Neo4j connections, LLM clients, and import auto-generated artifacts at
# module load time.  None of that is available (or appropriate) in a unit
# test.  We stub each side-effecting dependency BEFORE the first import so
# the helper-function tests can run offline against any clean checkout.
# ──────────────────────────────────────────────────────────────────────────────
import os  # noqa: E402
import types  # noqa: E402

# 1. agent.prompts — auto-generated by schema.gen_system_prompt during
#    setup_project.py.  Provide a placeholder so NER_SP import succeeds.
if "agent.prompts" not in sys.modules:
    _stub = types.ModuleType("agent.prompts")
    _stub.NER_SP = "STUB_NER_SYSTEM_PROMPT"
    sys.modules["agent.prompts"] = _stub

# 2. Required Neo4j env vars — agent.agent_helper reads them at import.
os.environ.setdefault("NEO4J_URI", "bolt://stub:7687")
os.environ.setdefault("NEO4J_USERNAME", "stub")
os.environ.setdefault("NEO4J_PASSWORD", "stub")

# 3. Patch langchain_neo4j.Neo4jGraph + langchain_neo4j.GraphCypherQAChain
#    BEFORE agent.agent_helper imports them.  We construct a minimal stand-in
#    class for each so the constructor calls do not hit the network.
try:
    import langchain_neo4j as _lcn  # noqa: WPS433
except Exception:  # pragma: no cover
    _lcn = None

if _lcn is not None:
    class _StubNeo4jGraph:
        def __init__(self, *a, **kw):
            self._a, self._kw = a, kw

        def query(self, *a, **kw):
            return []

    class _StubGraphCypherQAChain:  # used by ner_agent_auto
        @classmethod
        def from_llm(cls, *a, **kw):
            return cls()

    _lcn.Neo4jGraph = _StubNeo4jGraph
    _lcn.GraphCypherQAChain = _StubGraphCypherQAChain

# 4. Stub the LLM factory so build_llm_from_config doesn't instantiate
#    real provider clients (which need API keys).
try:
    from langchain_core.language_models import BaseChatModel as _BCM  # noqa: WPS433

    class _StubLLM(_BCM):
        @property
        def _llm_type(self) -> str:  # pragma: no cover
            return "stub"

        def _generate(self, *a, **kw):  # pragma: no cover
            raise NotImplementedError("stub LLM has no inference")

    # Patch agent.llm_factory.build_llm_from_config if present.
    try:
        import agent.llm_factory as _llm_factory  # noqa: WPS433
        _llm_factory.build_llm_from_config = lambda *a, **kw: _StubLLM()
    except Exception:
        pass
except Exception:  # pragma: no cover
    pass


# ──────────────────────────────────────────────────────────────────────────────
# Fix #4 — agent.agent_helper helpers
# ──────────────────────────────────────────────────────────────────────────────


class TestNormalizeForMatch(unittest.TestCase):
    """_normalize_for_match should casefold + collapse whitespace."""

    def setUp(self):
        from agent.agent_helper import _normalize_for_match
        self.f = _normalize_for_match

    def test_empty_string(self):
        self.assertEqual(self.f(""), "")

    def test_lowercases(self):
        self.assertEqual(self.f("The Matrix"), "the matrix")

    def test_collapses_internal_whitespace(self):
        self.assertEqual(self.f("The   Matrix"), "the matrix")

    def test_strips_outer_whitespace(self):
        self.assertEqual(self.f("  The Matrix  "), "the matrix")

    def test_handles_non_ascii(self):
        # casefold is locale-aware so accented forms compare correctly
        self.assertEqual(self.f("François"), self.f("françois"))


class TestSplitEntityCandidates(unittest.TestCase):
    """_split_entity_candidates should split multi-value LLM outputs."""

    def setUp(self):
        from agent.agent_helper import _split_entity_candidates
        self.f = _split_entity_candidates

    def test_no_separator_returns_single_candidate(self):
        self.assertEqual(self.f("Tom Hanks"), ["Tom Hanks"])

    def test_does_not_split_on_bare_and(self):
        """Critical: 'Crouching Tiger and Hidden Dragon' is one title."""
        self.assertEqual(
            self.f("Crouching Tiger and Hidden Dragon"),
            ["Crouching Tiger and Hidden Dragon"],
        )

    def test_splits_on_comma(self):
        self.assertEqual(self.f("Tom Hanks, Meg Ryan"), ["Tom Hanks", "Meg Ryan"])

    def test_splits_on_semicolon(self):
        self.assertEqual(self.f("Tom; Meg"), ["Tom", "Meg"])

    def test_splits_on_slash(self):
        self.assertEqual(self.f("A/B/C"), ["A", "B", "C"])

    def test_dedupes_case_insensitively(self):
        out = self.f("tom hanks, Tom Hanks, TOM HANKS")
        self.assertEqual(len(out), 1)
        self.assertEqual(out[0], "tom hanks")  # first-seen casing wins

    def test_drops_empty_fragments(self):
        self.assertEqual(self.f(",,Tom,,"), ["Tom"])

    def test_respects_max_candidates(self):
        many = ", ".join(f"Name{i}" for i in range(20))
        self.assertEqual(len(self.f(many, max_candidates=5)), 5)

    def test_empty_input(self):
        self.assertEqual(self.f(""), [])


class TestBestCandidateBySimilarity(unittest.TestCase):
    """best_candidate_by_similarity picks the best fuzzy match."""

    def setUp(self):
        from agent.agent_helper import best_candidate_by_similarity
        self.f = best_candidate_by_similarity

    def test_returns_none_for_empty_candidates(self):
        self.assertIsNone(self.f([], ["Neo Anderson"]))

    def test_returns_none_for_empty_canonicals(self):
        self.assertIsNone(self.f(["Neo"], []))

    def test_prefers_longer_match_for_partial_form(self):
        # Both 'Neo' and 'Neo Anderson' match the canonical 'Neo Anderson'
        # but the longer surface form scores higher (1.0 vs ~0.35).
        result = self.f(["Neo", "Neo Anderson"], ["Neo Anderson"])
        self.assertEqual(result, "Neo Anderson")

    def test_picks_correct_among_distractors(self):
        result = self.f(
            ["The Matrix", "Inception", "Avatar"],
            ["Inception (2010)"],
        )
        self.assertEqual(result, "Inception")

    def test_case_insensitive(self):
        # Even though 'NEO' is uppercased, casefold-normalized compare
        # should still match 'Neo Anderson' best when paired alone.
        result = self.f(["NEO"], ["Neo Anderson"])
        self.assertEqual(result, "NEO")  # original casing preserved


class TestCleanEntityResponse(unittest.TestCase):
    """_clean_entity_response should collapse whitespace runs (new behaviour)."""

    def setUp(self):
        from agent.agent_helper import _clean_entity_response
        self.f = _clean_entity_response

    def test_collapses_double_space(self):
        self.assertEqual(self.f("The  Matrix"), "The Matrix")

    def test_preserves_single_space(self):
        self.assertEqual(self.f("The Matrix"), "The Matrix")

    def test_strips_legacy_markers_still_works(self):
        self.assertEqual(self.f("[OUTPUT]\nElijah Wood"), "Elijah Wood")

    def test_strips_answer_prefix(self):
        self.assertEqual(self.f("Answer: Neo"), "Neo")

    def test_strips_quotes(self):
        self.assertEqual(self.f('"The Matrix"'), "The Matrix")


# ──────────────────────────────────────────────────────────────────────────────
# Fix #5 — neo4j_lib.neo4j_search helpers
# ──────────────────────────────────────────────────────────────────────────────


class TestTokenFuzziness(unittest.TestCase):
    """_token_fuzziness picks 0/1/2 by token length."""

    def setUp(self):
        from neo4j_lib.neo4j_search import _token_fuzziness
        self.f = _token_fuzziness

    def test_short_token_zero(self):
        # < 5 chars → 0  (avoid the "Tom" → millions-of-matches blowup)
        self.assertEqual(self.f("Tom"), 0)
        self.assertEqual(self.f("NBA"), 0)
        self.assertEqual(self.f("a"), 0)
        self.assertEqual(self.f("Joe"), 0)

    def test_medium_token_one(self):
        # 5..10 chars → 1
        self.assertEqual(self.f("Hanks"), 1)
        self.assertEqual(self.f("Matrix"), 1)
        self.assertEqual(self.f("Inception"), 1)  # 9
        self.assertEqual(self.f("Documenta"), 1)  # 9

    def test_long_token_two(self):
        # > 10 chars → 2
        self.assertEqual(self.f("Revolutions"), 2)  # 11
        self.assertEqual(self.f("Documentary"), 2)  # 11
        self.assertEqual(self.f("Grindelwald"), 2)  # 11


class TestLuceneQueryAutoMode(unittest.TestCase):
    """_lucene_query_from_phrase fuzziness=None engages AUTO."""

    def setUp(self):
        from neo4j_lib.neo4j_search import _lucene_query_from_phrase
        self.f = _lucene_query_from_phrase

    def test_auto_short_token_no_suffix(self):
        # "Tom" → 0 → no suffix
        self.assertEqual(self.f("Tom", fuzziness=None), "Tom")

    def test_auto_medium_token_suffix_one(self):
        self.assertEqual(self.f("Hanks", fuzziness=None), "Hanks~1")

    def test_auto_long_token_suffix_two(self):
        self.assertEqual(self.f("Revolutions", fuzziness=None), "Revolutions~2")

    def test_auto_mixed_phrase(self):
        # "Tom Hanks Revolutions" → no~ , ~1, ~2
        self.assertEqual(
            self.f("Tom Hanks Revolutions", fuzziness=None),
            "Tom Hanks~1 Revolutions~2",
        )

    def test_explicit_fuzziness_one_preserved(self):
        # Legacy callers passing fuzziness=1 keep the historical behaviour.
        self.assertEqual(self.f("Tom", fuzziness=1), "Tom~1")
        self.assertEqual(self.f("Revolutions", fuzziness=1), "Revolutions~1")

    def test_explicit_fuzziness_zero_disables(self):
        self.assertEqual(self.f("Matrix", fuzziness=0), "Matrix")

    def test_lucene_specials_escaped(self):
        # Reserved chars in tokens must be escaped under all modes.
        out = self.f("foo:bar", fuzziness=None)
        # split on \w → ['foo', 'bar'] (colon is the boundary), each ~0
        self.assertEqual(out, "foo bar")


# ──────────────────────────────────────────────────────────────────────────────
# Fix #1 / #2 / #6 — ner_agent_auto helpers
#
# ner_agent_auto.py pulls in heavyweight imports (langchain_neo4j, langgraph)
# at module load time. We can still import it: the deps are part of the
# project's installed environment.  If the env is missing, we skip these
# tests with a clear message rather than failing.
# ──────────────────────────────────────────────────────────────────────────────


def _try_import_ner_module():
    """Import ner_agent_auto, returning ``(module, error_or_None)``."""
    try:
        import ner_agent_auto  # noqa: WPS433  (intentional dynamic import)
        return ner_agent_auto, None
    except Exception as exc:  # pragma: no cover — env-specific
        return None, exc


_NER_MODULE, _NER_IMPORT_ERROR = _try_import_ner_module()


@unittest.skipIf(_NER_MODULE is None, f"ner_agent_auto unavailable: {_NER_IMPORT_ERROR!r}")
class TestAdaptiveTopK(unittest.TestCase):
    """_adaptive_top_k sizes top_k by query complexity."""

    def setUp(self):
        self.f = _NER_MODULE._adaptive_top_k

    def test_floor_for_empty_query(self):
        # Empty query — return base unchanged.
        self.assertEqual(self.f("", base_top_k=10), 10)

    def test_simple_question_small_k(self):
        # Single entity, single relation → small k.
        k = self.f("Who directed Inception?", base_top_k=10)
        self.assertGreaterEqual(k, 3)
        self.assertLessEqual(k, 8)

    def test_compound_question_higher_k(self):
        simple = self.f("Who directed Inception?", base_top_k=10)
        compound = self.f(
            "How many movies have either won the Amanda Award for "
            "Best Foreign Feature Film or feature Elijah Wood in their cast?",
            base_top_k=10,
        )
        # Compound should not be smaller than simple.
        self.assertGreaterEqual(compound, simple)

    def test_clamped_to_max(self):
        # Adversarial: many entities + many relations should still clamp at 8.
        massive = (
            "From 1999 to 2010, who directed 'Inception' and 'The Matrix' "
            "and produced 'Memento' and acted in 'Tenet' and 'Interstellar'?"
        )
        k = self.f(massive, base_top_k=10)
        self.assertLessEqual(k, 8)

    def test_respects_small_base_top_k(self):
        # Caller asks for tiny budget; adaptive must not blow it up beyond 2x.
        k = self.f(
            "How many movies have either won the Amanda Award or feature "
            "Elijah Wood?",
            base_top_k=2,
        )
        self.assertLessEqual(k, 4)


@unittest.skipIf(_NER_MODULE is None, f"ner_agent_auto unavailable: {_NER_IMPORT_ERROR!r}")
class TestDropEmbeddingToolNames(unittest.TestCase):
    """_drop_embedding_tool_names L1/L2/L3 filtering."""

    def _make_tool(self, name: str, description: str = ""):
        """Build a minimal tool-like object that satisfies attribute access."""
        class FakeTool:
            def __init__(self, n, d):
                self.name = n
                self.description = d
        return FakeTool(name, description)

    def setUp(self):
        self.f = _NER_MODULE._drop_embedding_tool_names

    def test_L1_drops_name_suffix_embedding(self):
        reg = {
            "get_movie_title": self._make_tool(
                "get_movie_title",
                "Look up canonical Movie.title values.",
            ),
            "get_movie_title_embedding": self._make_tool(
                "get_movie_title_embedding",
                "Look up canonical Movie.title_embedding values.",
            ),
        }
        out = self.f(reg)
        self.assertIn("get_movie_title", out)
        self.assertNotIn("get_movie_title_embedding", out)

    def test_L1_drops_name_suffix_vector(self):
        reg = {
            "get_person_name_vector": self._make_tool(
                "get_person_name_vector",
                "Look up canonical Person.name_vector values.",
            ),
        }
        self.assertEqual(self.f(reg), {})

    def test_L2_drops_when_description_mentions_embedding(self):
        # The L1 name check misses 'unrelated_name', but the description
        # contains 'embedding' so L2 catches it.
        reg = {
            "unrelated_name": self._make_tool(
                "unrelated_name",
                "Look up canonical Movie.foo embedding values.",
            ),
        }
        self.assertEqual(self.f(reg), {})

    def test_clean_tool_survives(self):
        reg = {
            "get_movie_title": self._make_tool(
                "get_movie_title",
                "Look up canonical Movie.title values.",
            ),
        }
        out = self.f(reg)
        self.assertIn("get_movie_title", out)


@unittest.skipIf(_NER_MODULE is None, f"ner_agent_auto unavailable: {_NER_IMPORT_ERROR!r}")
class TestFailureTrackingWrapper(unittest.TestCase):
    """_wrap_tools_with_failure_tracking short-circuits after N empty results."""

    def _make_returning_tool(self, *return_values):
        """Build a stub tool whose .invoke() returns return_values[i] in order."""
        from langchain_core.tools import StructuredTool

        calls = {"i": 0, "log": []}

        def _func(user_query: str):
            i = calls["i"]
            calls["i"] += 1
            calls["log"].append(user_query)
            return return_values[i] if i < len(return_values) else []

        tool = StructuredTool.from_function(
            func=_func,
            name="get_test_tool",
            description="Test tool",
        )
        return tool, calls

    def test_short_circuits_after_two_empty_results(self):
        tool, calls = self._make_returning_tool([], [], ["should_not_be_called"])
        wrapped = _NER_MODULE._wrap_tools_with_failure_tracking([tool])
        w = wrapped[0]

        # 1st call — empty, counter=1, real tool called.
        r1 = w.invoke({"user_query": "q1"})
        self.assertEqual(r1, [])
        # 2nd call — empty, counter=2, real tool called.
        r2 = w.invoke({"user_query": "q2"})
        self.assertEqual(r2, [])
        # 3rd call — short-circuited, real tool MUST NOT be invoked.
        r3 = w.invoke({"user_query": "q3"})
        self.assertEqual(len(r3), 1)
        self.assertIn("no_more_attempts", r3[0])
        self.assertEqual(calls["i"], 2)  # real tool was called exactly twice

    def test_resets_counter_on_non_empty_result(self):
        tool, calls = self._make_returning_tool([], ["hit"], [])
        wrapped = _NER_MODULE._wrap_tools_with_failure_tracking([tool])
        w = wrapped[0]

        self.assertEqual(w.invoke({"user_query": "q1"}), [])      # streak=1
        self.assertEqual(w.invoke({"user_query": "q2"}), ["hit"])  # streak=0
        self.assertEqual(w.invoke({"user_query": "q3"}), [])      # streak=1
        # Real tool was called 3× (streak never reached 2 consecutively).
        self.assertEqual(calls["i"], 3)

    def test_treats_whitespace_only_strings_as_empty(self):
        tool, calls = self._make_returning_tool(["   "], [""], ["nope"])
        wrapped = _NER_MODULE._wrap_tools_with_failure_tracking([tool])
        w = wrapped[0]

        w.invoke({"user_query": "q1"})
        w.invoke({"user_query": "q2"})
        r3 = w.invoke({"user_query": "q3"})
        self.assertIn("no_more_attempts", r3[0])
        self.assertEqual(calls["i"], 2)

    def test_counters_isolated_per_wrap_call(self):
        # Two separate wrap calls produce wrappers with independent counters.
        tool, calls = self._make_returning_tool([], [], [], [])
        w1 = _NER_MODULE._wrap_tools_with_failure_tracking([tool])[0]
        w1.invoke({"user_query": "q1"})
        w1.invoke({"user_query": "q2"})
        # New wrap → fresh counter; first call is NOT short-circuited.
        w2 = _NER_MODULE._wrap_tools_with_failure_tracking([tool])[0]
        r = w2.invoke({"user_query": "q3"})
        self.assertEqual(r, [])  # real tool called, not short-circuit


# ──────────────────────────────────────────────────────────────────────────────
# Progress heartbeat (eval/metrics_CypherBench.py)
# ──────────────────────────────────────────────────────────────────────────────
#
# The heartbeat is purely a side-effecting print helper, so we capture stdout
# and assert on the shape of the lines.  Goal: protect the contract that a
# stalled eval still leaves a "starting record N" line in the log.

class TestHeartbeatFormatter(unittest.TestCase):
    """Smoke-test the eval-loop heartbeat lines and ETA arithmetic."""

    @classmethod
    def setUpClass(cls):
        # The eval/metrics_CypherBench import chain pulls in agent_helper and
        # ner_agent_auto, which are already stubbed at module load above.  We
        # also need to stub neo4j_lib.safe_query since CypherBench imports it.
        if "neo4j_lib.safe_query" not in sys.modules:
            sq = types.ModuleType("neo4j_lib.safe_query")
            def _scr(*a, **k):
                return []
            class _TTOE(Exception):
                pass
            sq.safe_cypher_run = _scr
            sq.TransactionTimedOutError = _TTOE
            sys.modules["neo4j_lib.safe_query"] = sq
        from eval import metrics_CypherBench  # noqa: WPS433
        cls.mod = metrics_CypherBench

    def _capture(self, fn, *a, **k):
        import io
        import contextlib
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            fn(*a, **k)
        return buf.getvalue()

    def test_fmt_hms_seconds_only(self):
        self.assertEqual(self.mod._fmt_hms(0), "0s")
        self.assertEqual(self.mod._fmt_hms(45), "45s")

    def test_fmt_hms_minutes(self):
        self.assertEqual(self.mod._fmt_hms(125), "2m05s")

    def test_fmt_hms_hours(self):
        self.assertEqual(self.mod._fmt_hms(7325), "2h02m05s")

    def test_fmt_hms_handles_negative_and_none(self):
        self.assertEqual(self.mod._fmt_hms(-1), "--")
        self.assertEqual(self.mod._fmt_hms(None), "--")

    def test_start_line_includes_question(self):
        import time as _t
        out = self._capture(
            self.mod._heartbeat,
            1, 10, _t.time(),
            kind="start",
            qid="q1",
            question="who directed The Matrix?",
            every=1,
        )
        self.assertIn("▶ start", out)
        self.assertIn("qid=q1", out)
        self.assertIn("The Matrix", out)
        # boundary record always prints regardless of sampling
        self.assertIn("[   1/10]", out)

    def test_done_line_includes_running_ea_and_eta(self):
        import time as _t
        records = [{"ea": True}, {"ea": False}, {"ea": True}]
        out = self._capture(
            self.mod._heartbeat,
            3, 10, _t.time() - 30,
            kind="done",
            qid="q3",
            ea=True, em=False, psjs=0.9,
            elapsed=4.2,
            records_so_far=records,
            every=1,
        )
        self.assertIn("✔ done", out)
        self.assertIn("runEA=0.667", out)  # 2/3 EA hits
        self.assertIn("ETA=", out)
        self.assertIn("t=4.2s", out)

    def test_sampling_skips_middle_records(self):
        """When ``every=10`` and we're not at a boundary or error, the line
        should be suppressed.  Boundary (i==total) MUST still print so the
        operator sees the end of the run."""
        import time as _t
        out_mid = self._capture(
            self.mod._heartbeat,
            5, 100, _t.time(),
            kind="done", qid="q5", ea=True, em=True, psjs=1.0,
            elapsed=1.0, records_so_far=[{"ea": True}],
            every=10,
        )
        self.assertEqual(out_mid, "")  # suppressed

        out_end = self._capture(
            self.mod._heartbeat,
            100, 100, _t.time(),
            kind="done", qid="q100", ea=True, em=True, psjs=1.0,
            elapsed=1.0, records_so_far=[{"ea": True}],
            every=10,
        )
        self.assertIn("✔ done", out_end)  # boundary always prints

    def test_error_always_prints_even_when_sampled(self):
        """An error line MUST never be silently dropped by sampling."""
        import time as _t
        out_err = self._capture(
            self.mod._heartbeat,
            7, 100, _t.time(),
            kind="done", qid="q7", ea=False, em=False, psjs=0.0,
            err="timeout: 60s",
            elapsed=60.0, records_so_far=[{"ea": False}],
            every=10,
        )
        self.assertIn("err=timeout", out_err)


if __name__ == "__main__":
    unittest.main(verbosity=2)
