# AUTO-GENERATED by gen_system_prompt.py — do not edit manually.
# Database : neo4j
# Re-run `python gen_system_prompt.py` to regenerate from the live schema.
#
# This file contains ONLY auto-generated content:
#   • System prompts (NER_SP, TEXT2CYPHER_SP, QA_SP, PROMPT_ALIGNER_SP)
#   • Schema constants derived from the live Neo4j graph
#
# User-managed hyperparameters (LLM configs, NER_MODE, SAMPLE_T, …) live
# in ``config.py`` and are NEVER overwritten by ``gen_system_prompt.py``.

# ──────────────────────────────────────────────────────────────────────────────
# System Prompts
# ──────────────────────────────────────────────────────────────────────────────

NER_SP = """\
You are a strict Named Entity Recognition (NER) agent for a Neo4j graph database.

Your sole responsibility: extract named entities from the user question and
resolve each one to its canonical database value using the provided tools.

Available tools
───────────────
{tool_list}

Extraction rules (follow strictly)
────────────────────────────────────
1.  Extract ONLY entities that are explicitly mentioned in the question.
    If no relevant entity exists, return an empty JSON object {}.

2.  Use a tool for every string entity that needs database lookup.
    Exception: purely numeric values (years, IDs, counts) must be returned
    inline as numbers — do NOT call a tool for them.

3.  A match is valid ONLY when it is:
    (a) a lexical match (case-insensitive), OR
    (b) semantically identical (same real-world referent).
    Never fabricate or guess values beyond what the tools return.

4.  Return at most 2 best-matching canonical values per key.

5.  If a tool returns NO matching values (empty result), drop that key from
    the output.  Do NOT fabricate a value.  (But always TRY the lookup
    first per rule 7 — never skip a call because you predict it will be
    empty.)

6.  Final output MUST be a single valid JSON object — nothing else.
    • Keys   : "Label.property" format (e.g. "Author.id", "Author.name", "Movie.released")
    • Values : always a JSON array, even for a single result
    • No code fences, no markdown, no explanation, no extra text.

7.  Coverage over caution: For EVERY noun phrase in the question that could
    plausibly refer to a database entity (a person, a movie, an
    organization, a category, etc.), call the corresponding tool to verify
    — even if you are not fully sure the mention matches anything.
    Lowercase, partial, abbreviated, or informal mentions ("matrix" for
    "The Matrix", "godfather" for "The Godfather") still count and MUST be
    looked up.  It is far better to make an extra tool call that returns
    nothing than to skip a tool call and miss an entity.  Do NOT decide on
    your own that a mention is "too informal" or "probably not in the
    database" — let the tool decide.

Examples
────────
Q: Find the author named "https://openalex.org/A5108081836".
A: {"Author.id": ["https://openalex.org/A5108081836"]}

Q: How many movies have released before 2006?
A: {"Movie.released": [2006]}

Q: Which movie has tagline containing "Speed has no limits"?
A: {"Movie.tagline": ["Speed has no limits"]}

Q: Which person has acted_in roles "['Ryan Maslow']"?
A: {"ACTED_IN.roles": ["['Ryan Maslow']"]}

Q: List all items in the database.
A: {}

Q: Find authors related to acted_in with roles "['Ryan Maslow']" or "['Dr. Stone']", mentioning author "Jane Rogers".
A: {"ACTED_IN.roles": [["['Ryan Maslow']"], ["['Dr. Stone']"]], "Author.name": ["Jane Rogers"]}
"""

TEXT2CYPHER_SP = """\
Task: Generate a single READ-ONLY Cypher query to answer the user question.

Output format
─────────────
Return ONLY the Cypher query — no backticks, no code fences, no explanation.

Generation rules
────────────────
- Schema adherence : use ONLY the labels, relationship types, and properties
  defined in the schema below. Never invent new ones.
- Read-only        : never generate CREATE / MERGE / SET / DELETE / REMOVE.
- No parameters    : do NOT use $param syntax; always inline literal values.
  ✓  WHERE toLower(m.title) = toLower("Inception")
  ✗  WHERE m.title = $title
- Aliases          : always use snake_case (e.g. movie_title, person_name).
- LIMIT            : always add LIMIT (default 25) unless the question asks
  for a count or aggregate.
- String comparisons: always use `toLower(n.prop) = toLower("value")` for (Author.id, Author.name, Movie.tagline).
- Entity filters   : when entity values are supplied in the "Schema-relevant
  entity filters" section below, incorporate ALL of them in the WHERE clause
  as exact-match (string) or comparison (numeric) filters.
- List-typed properties:
  When the schema declares a property as a *list/array type* (e.g.
  ``StringArray``, ``FloatArray``) — for example ``ACTED_IN.roles`` is a
  ``StringArray`` of character names — the NER pipeline emits the
  corresponding entity-filter value as a **list of lists**:
  ``"Label.prop": [[v1], [v2], ...]`` (the outer list is the standard
  "candidate values" wrapper; the inner list is the list-typed value
  itself).
  Expand each inner value ``vi`` into its own membership predicate
  ``vi IN <alias>.<prop>`` and join multiple values with ``OR``:
    ✓  ``"Neo" IN r.roles``                        (single value)
    ✓  ``("Neo" IN r.roles OR "Morpheus" IN r.roles)``  (multiple values)
    ✗  ``["Neo"] IN r.roles``                      (wrong — list-in-list never matches)
    ✗  ``r.roles CONTAINS "Neo"``                  (wrong — CONTAINS is string-only)
  For non-list (scalar) properties, keep the existing ``=`` /
  ``toLower(...)`` / numeric-comparison behaviour unchanged — the new rule
  applies *only* when the schema marks the target property as an array
  type.

Examples
────────
# 1. List-typed relationship property — single value
Question: Who played Neo in The Matrix?
Schema-relevant entity filters:
  {{"Movie.title": ["The Matrix"], "ACTED_IN.roles": [["Neo"]]}}
Cypher:
  MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix") AND "Neo" IN r.roles
  RETURN p.name AS person_name
  LIMIT 25

# 2. List-typed relationship property — multiple values
Question: Who played Neo or Morpheus in The Matrix?
Schema-relevant entity filters:
  {{"Movie.title": ["The Matrix"], "ACTED_IN.roles": [["Neo"], ["Morpheus"]]}}
Cypher:
  MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix")
        AND ("Neo" IN r.roles OR "Morpheus" IN r.roles)
  RETURN DISTINCT p.name AS person_name
  LIMIT 25

# 3. Scalar relationship property — DO NOT apply the IN-expansion rule
Question: Which reviewers gave The Matrix a rating above 90?
Schema-relevant entity filters:
  {{"Movie.title": ["The Matrix"], "REVIEWED.rating": [90]}}
Cypher:
  MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
  WHERE toLower(m.title) = toLower("The Matrix") AND r.rating > 90
  RETURN p.name AS person_name, r.rating AS rating
  LIMIT 25

Graph Schema (static snapshot — baked at generation time)
──────────────────────────────────────────────────────────
    Node Labels and Properties:
      Author : id (String), name (String)
      Movie  : released (Long), tagline (String), tagline_embedding (FloatArray), title (String), title_embedding (FloatArray)
      Person : born (Long), name (String), name_embedding (FloatArray)
      Work   : id (String), title (String), year (Long)

    Relationships:
      (:Person)-[:ACTED_IN {roles: StringArray}]->(:Movie)
      (:Author)-[:AUTHORED]->(:Work)
      (:Person)-[:DIRECTED]->(:Movie)
      (:Person)-[:FOLLOWS]->(:Person)
      (:Person)-[:PRODUCED]->(:Movie)
      (:Person)-[:REVIEWED {rating: Long, summary: String}]->(:Movie)
      (:Person)-[:WROTE]->(:Movie)

Live schema (injected at runtime by GraphCypherQAChain — authoritative):
{schema}

Schema-relevant entity filters
───────────────────────────────
(Pre-filled by the NER pipeline.  Keys are "Label.property"; values are
canonical matches from the database.  Use ALL provided pairs in WHERE.)

{relevant_entities}

Question: {question}
Answer:
"""

QA_SP = """\
You are a helpful AI assistant that answers questions about a graph database.

Rules
─────
1.  Ground all answers strictly in the "Relevant Data" provided.
    Never use internal knowledge to add, correct, or contradict the data.
2.  If Relevant Data is empty, contains no rows, or is irrelevant to the
    question, say explicitly: "The database returned no results for this
    query."  Do NOT fabricate, guess, or infer an answer from your own
    knowledge.
3.  Be concise, accurate, and use natural language.
4.  When the question asks for a list, provide it in bullet-point or table form.
5.  When the question asks for a count or aggregate, state the number directly.
6.  Do NOT expose raw Neo4j node IDs or internal identifiers.

Output format
─────────────
- For narrative answers : plain prose with bullet points where helpful.
- For tabular data      : a markdown table with clear column headers.
- For counts / numbers  : state the figure prominently at the start.

Examples
────────
Q: Who is associated with item "Alpha"?
Relevant Data: [{{"name": "Alice"}}]
A: Alice is associated with item "Alpha".

Q: How many records were created before 2020?
Relevant Data: [{{"count": 42}}]
A: There are 42 records created before 2020 in the database.

Q: What are the properties of node "X"?
Relevant Data: [{{"property": "status", "value": "active"}}, {{"property": "region", "value": "west"}}]
A:
Node "X" has the following properties:
| Property | Value  |
|----------|--------|
| status   | active |
| region   | west   |

Q: Who directed "Nonexistent Movie"?
Relevant Data: []
A: The database returned no results for this query.  There is no record matching "Nonexistent Movie" in the graph.

Now answer the following:

Question: {{question}}
Relevant Data:
{{context}}
Answer:
"""

PROMPT_ALIGNER_SP = """\
You are a Cypher query expert helping to align a user question with the query
that was actually executed against the graph database.

Context
───────
Users sometimes phrase questions using informal language, incorrect property
names, or assumptions about the schema.  The system generates the closest
valid Cypher query it can.  Your task is to rephrase the user question so it
accurately reflects what the executed Cypher query does — making it clear
which labels, properties, and filter values were used.

Rules
─────
- Output ONLY the rephrased question — no explanation, no extra text.
- Expand abbreviations and acronyms where you can infer the full form.
- If the Cypher query filters by a specific property value (e.g. a label,
  type, or dimension), include that value in the rephrased question.
- Keep the rephrased question as close to the original intent as possible.

Examples
────────
[user_question]  What items does Alice manage?
[cypher_query]   MATCH (p:Person {{name: "Alice Smith"}})-[:MANAGES]->(i:Item)
                 RETURN i.name AS item_name
[rephrased]      What items does Alice Smith manage?

[user_question]  Find old records.
[cypher_query]   MATCH (r:Record) WHERE r.created_year < 2000 RETURN r.name, r.created_year
[rephrased]      Find records created before the year 2000.

Now rephrase:

[user_question]
{{user_question}}

[cypher_query]
{{cypher_query}}

[rephrased]
"""

# ──────────────────────────────────────────────────────────────────────────────
# Schema Constants  (auto-derived from the live Neo4j database)
# ──────────────────────────────────────────────────────────────────────────────

# Node labels
NODE_AUTHOR = "Author"
NODE_MOVIE = "Movie"
NODE_PERSON = "Person"
NODE_WORK = "Work"

# Node properties
PROPERTY_AUTHOR_ID = "id"
PROPERTY_AUTHOR_NAME = "name"
PROPERTY_MOVIE_RELEASED = "released"
PROPERTY_MOVIE_TAGLINE = "tagline"
PROPERTY_MOVIE_TAGLINE_EMBEDDING = "tagline_embedding"
PROPERTY_MOVIE_TITLE = "title"
PROPERTY_MOVIE_TITLE_EMBEDDING = "title_embedding"
PROPERTY_PERSON_BORN = "born"
PROPERTY_PERSON_NAME = "name"
PROPERTY_PERSON_NAME_EMBEDDING = "name_embedding"
PROPERTY_WORK_ID = "id"
PROPERTY_WORK_TITLE = "title"
PROPERTY_WORK_YEAR = "year"

# Filterable properties per node label
FILTERABLE_AUTHOR_PROPERTIES = ["name"]
FILTERABLE_MOVIE_PROPERTIES = ["tagline", "tagline_embedding", "title", "title_embedding"]
FILTERABLE_PERSON_PROPERTIES = ["name", "name_embedding"]
FILTERABLE_WORK_PROPERTIES = ["title"]

# Relationship types
REL_ACTED_IN = "ACTED_IN"
REL_AUTHORED = "AUTHORED"
REL_DIRECTED = "DIRECTED"
REL_FOLLOWS = "FOLLOWS"
REL_PRODUCED = "PRODUCED"
REL_REVIEWED = "REVIEWED"
REL_WROTE = "WROTE"

# Relationship properties
REL_PROPERTY_ACTED_IN_ROLES = "roles"
REL_PROPERTY_REVIEWED_RATING = "rating"
REL_PROPERTY_REVIEWED_SUMMARY = "summary"

# Fulltext index names
FULLTEXT_INDEX_ACTED_IN_ROLES_REL_INDEX = "ACTED_IN_roles_RelIndex"
FULLTEXT_INDEX_ACCOUNT_HOLDER_UNIQUE_ID_INDEX = "AccountHolder_UniqueId_Index"
FULLTEXT_INDEX_ACCOUNT_HOLDER_BIRTH_DATE_INDEX = "AccountHolder_birthDate_Index"
FULLTEXT_INDEX_ACCOUNT_HOLDER_FIRST_NAME_INDEX = "AccountHolder_firstName_Index"
FULLTEXT_INDEX_ACCOUNT_HOLDER_FULL_NAME_INDEX = "AccountHolder_fullName_Index"
FULLTEXT_INDEX_ACCOUNT_HOLDER_LAST_NAME_INDEX = "AccountHolder_lastName_Index"
FULLTEXT_INDEX_ADDRESS_CITY_INDEX = "Address_city_Index"
FULLTEXT_INDEX_ADDRESS_STATE_INDEX = "Address_state_Index"
FULLTEXT_INDEX_ADDRESS_STREET_ADDRESS_INDEX = "Address_streetAddress_Index"
FULLTEXT_INDEX_ADDRESS_ZIP_INDEX = "Address_zip_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_ALIASES_INDEX = "AircraftManufacturer_aliases_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_COUNTRY_INDEX = "AircraftManufacturer_country_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_DESCRIPTION_INDEX = "AircraftManufacturer_description_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_EID_INDEX = "AircraftManufacturer_eid_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_LAUNCH_YEAR_INDEX = "AircraftManufacturer_launch_year_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_NAME_INDEX = "AircraftManufacturer_name_Index"
FULLTEXT_INDEX_AIRCRAFT_MANUFACTURER_PROVENANCE_INDEX = "AircraftManufacturer_provenance_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_ALIASES_INDEX = "AircraftModel_aliases_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_DESCRIPTION_INDEX = "AircraftModel_description_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_EID_INDEX = "AircraftModel_eid_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_FIRST_FLIGHT_INDEX = "AircraftModel_first_flight_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_HEIGHT_METRE_INDEX = "AircraftModel_height_metre_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_LENGTH_METRE_INDEX = "AircraftModel_length_metre_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_NAME_INDEX = "AircraftModel_name_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_PROVENANCE_INDEX = "AircraftModel_provenance_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_RANGE_KM_INDEX = "AircraftModel_range_km_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_SERVICE_ENTRY_INDEX = "AircraftModel_service_entry_Index"
FULLTEXT_INDEX_AIRCRAFT_MODEL_WINGSPAN_METRE_INDEX = "AircraftModel_wingspan_metre_Index"
FULLTEXT_INDEX_AIRPORT_ALIASES_INDEX = "Airport_aliases_Index"
FULLTEXT_INDEX_AIRPORT_COUNTRY_INDEX = "Airport_country_Index"
FULLTEXT_INDEX_AIRPORT_DESCRIPTION_INDEX = "Airport_description_Index"
FULLTEXT_INDEX_AIRPORT_EID_INDEX = "Airport_eid_Index"
FULLTEXT_INDEX_AIRPORT_IATA_CODE_INDEX = "Airport_iata_code_Index"
FULLTEXT_INDEX_AIRPORT_ICAO_CODE_INDEX = "Airport_icao_code_Index"
FULLTEXT_INDEX_AIRPORT_LOCATION_INDEX = "Airport_location_Index"
FULLTEXT_INDEX_AIRPORT_NAME_INDEX = "Airport_name_Index"
FULLTEXT_INDEX_AIRPORT_PROVENANCE_INDEX = "Airport_provenance_Index"
FULLTEXT_INDEX_AREA_AREA_CODE_INDEX = "Area_areaCode_Index"
FULLTEXT_INDEX_AUTHOR_ID_INDEX = "Author_id_Index"
FULLTEXT_INDEX_AUTHOR_NAME_INDEX = "Author_name_Index"
FULLTEXT_INDEX_AWARD_ALIASES_INDEX = "Award_aliases_Index"
FULLTEXT_INDEX_AWARD_DESCRIPTION_INDEX = "Award_description_Index"
FULLTEXT_INDEX_AWARD_EID_INDEX = "Award_eid_Index"
FULLTEXT_INDEX_AWARD_NAME_INDEX = "Award_name_Index"
FULLTEXT_INDEX_AWARD_PROVENANCE_INDEX = "Award_provenance_Index"
FULLTEXT_INDEX_BANK_ACCOUNT_ACCOUNT_NUMBER_INDEX = "BankAccount_accountNumber_Index"
FULLTEXT_INDEX_BANK_ACCOUNT_BALANCE_INDEX = "BankAccount_balance_Index"
FULLTEXT_INDEX_BANK_ACCOUNT_LAST_RECEIVED_INDEX = "BankAccount_lastReceived_Index"
FULLTEXT_INDEX_BANK_ACCOUNT_LAST_SEND_INDEX = "BankAccount_lastSend_Index"
FULLTEXT_INDEX_BANK_CARD_ACCOUNT_NUMBER_INDEX = "BankCard_accountNumber_Index"
FULLTEXT_INDEX_BANK_CARD_BALANCE_INDEX = "BankCard_balance_Index"
FULLTEXT_INDEX_BANK_CARD_EXPIRATION_DATE_INDEX = "BankCard_expirationDate_Index"
FULLTEXT_INDEX_BANK_CARD_LATE_PAYMENTS_INDEX = "BankCard_latePayments_Index"
FULLTEXT_INDEX_BANK_CARD_LIMIT_INDEX = "BankCard_limit_Index"
FULLTEXT_INDEX_BANK_CARD_SECURITY_CODE_INDEX = "BankCard_securityCode_Index"
FULLTEXT_INDEX_CHARACTER_ALIASES_INDEX = "Character_aliases_Index"
FULLTEXT_INDEX_CHARACTER_BIRTH_NAME_INDEX = "Character_birth_name_Index"
FULLTEXT_INDEX_CHARACTER_COUNTRY_OF_CITIZENSHIP_INDEX = "Character_country_of_citizenship_Index"
FULLTEXT_INDEX_CHARACTER_CREATOR_INDEX = "Character_creator_Index"
FULLTEXT_INDEX_CHARACTER_DESCRIPTION_INDEX = "Character_description_Index"
FULLTEXT_INDEX_CHARACTER_EID_INDEX = "Character_eid_Index"
FULLTEXT_INDEX_CHARACTER_GENDER_INDEX = "Character_gender_Index"
FULLTEXT_INDEX_CHARACTER_NAME_INDEX = "Character_name_Index"
FULLTEXT_INDEX_CHARACTER_OCCUPATION_INDEX = "Character_occupation_Index"
FULLTEXT_INDEX_CHARACTER_PROVENANCE_INDEX = "Character_provenance_Index"
FULLTEXT_INDEX_COMPANY_ALIASES_INDEX = "Company_aliases_Index"
FULLTEXT_INDEX_COMPANY_DESCRIPTION_INDEX = "Company_description_Index"
FULLTEXT_INDEX_COMPANY_EID_INDEX = "Company_eid_Index"
FULLTEXT_INDEX_COMPANY_LAUNCH_YEAR_INDEX = "Company_launch_year_Index"
FULLTEXT_INDEX_COMPANY_NAME_INDEX = "Company_name_Index"
FULLTEXT_INDEX_COMPANY_PROVENANCE_INDEX = "Company_provenance_Index"
FULLTEXT_INDEX_CONFERENCE_ALIASES_INDEX = "Conference_aliases_Index"
FULLTEXT_INDEX_CONFERENCE_DESCRIPTION_INDEX = "Conference_description_Index"
FULLTEXT_INDEX_CONFERENCE_EID_INDEX = "Conference_eid_Index"
FULLTEXT_INDEX_CONFERENCE_NAME_INDEX = "Conference_name_Index"
FULLTEXT_INDEX_CONFERENCE_PROVENANCE_INDEX = "Conference_provenance_Index"
FULLTEXT_INDEX_CONTINENT_ALIASES_INDEX = "Continent_aliases_Index"
FULLTEXT_INDEX_CONTINENT_DESCRIPTION_INDEX = "Continent_description_Index"
FULLTEXT_INDEX_CONTINENT_EID_INDEX = "Continent_eid_Index"
FULLTEXT_INDEX_CONTINENT_NAME_INDEX = "Continent_name_Index"
FULLTEXT_INDEX_CONTINENT_PROVENANCE_INDEX = "Continent_provenance_Index"
FULLTEXT_INDEX_COUNTRY_ALIASES_INDEX = "Country_aliases_Index"
FULLTEXT_INDEX_COUNTRY_AREA_KM2_INDEX = "Country_area_km2_Index"
FULLTEXT_INDEX_COUNTRY_CAPITAL_INDEX = "Country_capital_Index"
FULLTEXT_INDEX_COUNTRY_DESCRIPTION_INDEX = "Country_description_Index"
FULLTEXT_INDEX_COUNTRY_EID_INDEX = "Country_eid_Index"
FULLTEXT_INDEX_COUNTRY_FOUNDING_DATE_INDEX = "Country_founding_date_Index"
FULLTEXT_INDEX_COUNTRY_NAME_INDEX = "Country_name_Index"
FULLTEXT_INDEX_COUNTRY_OFFICIAL_LANGUAGE_INDEX = "Country_official_language_Index"
FULLTEXT_INDEX_COUNTRY_PROVENANCE_INDEX = "Country_provenance_Index"
FULLTEXT_INDEX_CREDIT_CARD_ACCOUNT_NUMBER_INDEX = "CreditCard_accountNumber_Index"
FULLTEXT_INDEX_CREDIT_CARD_BALANCE_INDEX = "CreditCard_balance_Index"
FULLTEXT_INDEX_CREDIT_CARD_EXPIRATION_DATE_INDEX = "CreditCard_expirationDate_Index"
FULLTEXT_INDEX_CREDIT_CARD_LATE_PAYMENTS_INDEX = "CreditCard_latePayments_Index"
FULLTEXT_INDEX_CREDIT_CARD_LIMIT_INDEX = "CreditCard_limit_Index"
FULLTEXT_INDEX_CREDIT_CARD_SECURITY_CODE_INDEX = "CreditCard_securityCode_Index"
FULLTEXT_INDEX_CRIME_CHARGE_INDEX = "Crime_charge_Index"
FULLTEXT_INDEX_CRIME_DATE_INDEX = "Crime_date_Index"
FULLTEXT_INDEX_CRIME_ID_INDEX = "Crime_id_Index"
FULLTEXT_INDEX_CRIME_LAST_OUTCOME_INDEX = "Crime_last_outcome_Index"
FULLTEXT_INDEX_CRIME_NOTE_INDEX = "Crime_note_Index"
FULLTEXT_INDEX_CRIME_TYPE_INDEX = "Crime_type_Index"
FULLTEXT_INDEX_DELIVERY_ADDRESS_CITY_INDEX = "DeliveryAddress_city_Index"
FULLTEXT_INDEX_DELIVERY_ADDRESS_STATE_INDEX = "DeliveryAddress_state_Index"
FULLTEXT_INDEX_DELIVERY_ADDRESS_STREET_ADDRESS_INDEX = "DeliveryAddress_streetAddress_Index"
FULLTEXT_INDEX_DELIVERY_ADDRESS_ZIP_INDEX = "DeliveryAddress_zip_Index"
FULLTEXT_INDEX_DIVISION_ALIASES_INDEX = "Division_aliases_Index"
FULLTEXT_INDEX_DIVISION_DESCRIPTION_INDEX = "Division_description_Index"
FULLTEXT_INDEX_DIVISION_EID_INDEX = "Division_eid_Index"
FULLTEXT_INDEX_DIVISION_NAME_INDEX = "Division_name_Index"
FULLTEXT_INDEX_DIVISION_PROVENANCE_INDEX = "Division_provenance_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_ALIASES_INDEX = "DrainageBasin_aliases_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_AREA_KM2_INDEX = "DrainageBasin_area_km2_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_DESCRIPTION_INDEX = "DrainageBasin_description_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_EID_INDEX = "DrainageBasin_eid_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_NAME_INDEX = "DrainageBasin_name_Index"
FULLTEXT_INDEX_DRAINAGE_BASIN_PROVENANCE_INDEX = "DrainageBasin_provenance_Index"
FULLTEXT_INDEX_EMAIL_EMAIL_ADDRESS_INDEX = "Email_email_address_Index"
FULLTEXT_INDEX_FAMILY_REL_REL_TYPE_REL_INDEX = "FAMILY_REL_rel_type_RelIndex"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_ALIASES_INDEX = "FictionalUniverse_aliases_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_COPYRIGHT_HOLDER_INDEX = "FictionalUniverse_copyright_holder_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_CREATOR_INDEX = "FictionalUniverse_creator_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_DESCRIPTION_INDEX = "FictionalUniverse_description_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_EID_INDEX = "FictionalUniverse_eid_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_INCEPTION_YEAR_INDEX = "FictionalUniverse_inception_year_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_NAME_INDEX = "FictionalUniverse_name_Index"
FULLTEXT_INDEX_FICTIONAL_UNIVERSE_PROVENANCE_INDEX = "FictionalUniverse_provenance_Index"
FULLTEXT_INDEX_FILM_SERIES_ALIASES_INDEX = "FilmSeries_aliases_Index"
FULLTEXT_INDEX_FILM_SERIES_DESCRIPTION_INDEX = "FilmSeries_description_Index"
FULLTEXT_INDEX_FILM_SERIES_EID_INDEX = "FilmSeries_eid_Index"
FULLTEXT_INDEX_FILM_SERIES_NAME_INDEX = "FilmSeries_name_Index"
FULLTEXT_INDEX_FILM_SERIES_PROVENANCE_INDEX = "FilmSeries_provenance_Index"
FULLTEXT_INDEX_FINANCIAL_INSTITUTE_NAME_INDEX = "FinancialInstitute_name_Index"
FULLTEXT_INDEX_FINANCIAL_INSTITUTE_WEBSITE_INDEX = "FinancialInstitute_website_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_ALIASES_INDEX = "FlightAccident_aliases_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_DATE_INDEX = "FlightAccident_date_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_DESCRIPTION_INDEX = "FlightAccident_description_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_EID_INDEX = "FlightAccident_eid_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_FLIGHT_NUMBER_INDEX = "FlightAccident_flight_number_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_LOCATION_INDEX = "FlightAccident_location_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_NAME_INDEX = "FlightAccident_name_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_NUMBER_OF_DEATHS_INDEX = "FlightAccident_number_of_deaths_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_NUMBER_OF_INJURIES_INDEX = "FlightAccident_number_of_injuries_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_NUMBER_OF_SURVIVORS_INDEX = "FlightAccident_number_of_survivors_Index"
FULLTEXT_INDEX_FLIGHT_ACCIDENT_PROVENANCE_INDEX = "FlightAccident_provenance_Index"
FULLTEXT_INDEX_GENRE_ALIASES_INDEX = "Genre_aliases_Index"
FULLTEXT_INDEX_GENRE_DESCRIPTION_INDEX = "Genre_description_Index"
FULLTEXT_INDEX_GENRE_EID_INDEX = "Genre_eid_Index"
FULLTEXT_INDEX_GENRE_NAME_INDEX = "Genre_name_Index"
FULLTEXT_INDEX_GENRE_PROVENANCE_INDEX = "Genre_provenance_Index"
FULLTEXT_INDEX_GOVERNMENT_ORGANIZATION_ALIASES_INDEX = "GovernmentOrganization_aliases_Index"
FULLTEXT_INDEX_GOVERNMENT_ORGANIZATION_DESCRIPTION_INDEX = "GovernmentOrganization_description_Index"
FULLTEXT_INDEX_GOVERNMENT_ORGANIZATION_EID_INDEX = "GovernmentOrganization_eid_Index"
FULLTEXT_INDEX_GOVERNMENT_ORGANIZATION_NAME_INDEX = "GovernmentOrganization_name_Index"
FULLTEXT_INDEX_GOVERNMENT_ORGANIZATION_PROVENANCE_INDEX = "GovernmentOrganization_provenance_Index"
FULLTEXT_INDEX_IP_IP_INDEX = "IP_ip_Index"
FULLTEXT_INDEX_INDUSTRY_ALIASES_INDEX = "Industry_aliases_Index"
FULLTEXT_INDEX_INDUSTRY_DESCRIPTION_INDEX = "Industry_description_Index"
FULLTEXT_INDEX_INDUSTRY_EID_INDEX = "Industry_eid_Index"
FULLTEXT_INDEX_INDUSTRY_NAME_INDEX = "Industry_name_Index"
FULLTEXT_INDEX_INDUSTRY_PROVENANCE_INDEX = "Industry_provenance_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_ALIASES_INDEX = "InternationalOrganization_aliases_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_DESCRIPTION_INDEX = "InternationalOrganization_description_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_EID_INDEX = "InternationalOrganization_eid_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_FOUNDING_YEAR_INDEX = "InternationalOrganization_founding_year_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_NAME_INDEX = "InternationalOrganization_name_Index"
FULLTEXT_INDEX_INTERNATIONAL_ORGANIZATION_PROVENANCE_INDEX = "InternationalOrganization_provenance_Index"
FULLTEXT_INDEX_LAKE_ALIASES_INDEX = "Lake_aliases_Index"
FULLTEXT_INDEX_LAKE_AREA_KM2_INDEX = "Lake_area_km2_Index"
FULLTEXT_INDEX_LAKE_DESCRIPTION_INDEX = "Lake_description_Index"
FULLTEXT_INDEX_LAKE_EID_INDEX = "Lake_eid_Index"
FULLTEXT_INDEX_LAKE_NAME_INDEX = "Lake_name_Index"
FULLTEXT_INDEX_LAKE_PROVENANCE_INDEX = "Lake_provenance_Index"
FULLTEXT_INDEX_LAKE_VERTICAL_DEPTH_M_INDEX = "Lake_vertical_depth_m_Index"
FULLTEXT_INDEX_LOCATION_ADDRESS_INDEX = "Location_address_Index"
FULLTEXT_INDEX_LOCATION_ALIASES_INDEX = "Location_aliases_Index"
FULLTEXT_INDEX_LOCATION_DESCRIPTION_INDEX = "Location_description_Index"
FULLTEXT_INDEX_LOCATION_EID_INDEX = "Location_eid_Index"
FULLTEXT_INDEX_LOCATION_LATITUDE_INDEX = "Location_latitude_Index"
FULLTEXT_INDEX_LOCATION_LONGITUDE_INDEX = "Location_longitude_Index"
FULLTEXT_INDEX_LOCATION_NAME_INDEX = "Location_name_Index"
FULLTEXT_INDEX_LOCATION_POSTCODE_INDEX = "Location_postcode_Index"
FULLTEXT_INDEX_LOCATION_PROVENANCE_INDEX = "Location_provenance_Index"
FULLTEXT_INDEX_LOGIN_FIRST_NAME_INDEX = "Login_firstName_Index"
FULLTEXT_INDEX_LOGIN_LAST_NAME_INDEX = "Login_lastName_Index"
FULLTEXT_INDEX_LOGIN_MAIL_INDEX = "Login_mail_Index"
FULLTEXT_INDEX_LOGIN_START_DATE_INDEX = "Login_startDate_Index"
FULLTEXT_INDEX_LOGIN_USERID_INDEX = "Login_userid_Index"
FULLTEXT_INDEX_MONEY_TRANSFER_AMOUNT_INDEX = "MoneyTransfer_amount_Index"
FULLTEXT_INDEX_MONEY_TRANSFER_TRANSACTION_DATE_INDEX = "MoneyTransfer_transactionDate_Index"
FULLTEXT_INDEX_MOUNTAIN_RANGE_ALIASES_INDEX = "MountainRange_aliases_Index"
FULLTEXT_INDEX_MOUNTAIN_RANGE_DESCRIPTION_INDEX = "MountainRange_description_Index"
FULLTEXT_INDEX_MOUNTAIN_RANGE_EID_INDEX = "MountainRange_eid_Index"
FULLTEXT_INDEX_MOUNTAIN_RANGE_NAME_INDEX = "MountainRange_name_Index"
FULLTEXT_INDEX_MOUNTAIN_RANGE_PROVENANCE_INDEX = "MountainRange_provenance_Index"
FULLTEXT_INDEX_MOUNTAIN_ALIASES_INDEX = "Mountain_aliases_Index"
FULLTEXT_INDEX_MOUNTAIN_DESCRIPTION_INDEX = "Mountain_description_Index"
FULLTEXT_INDEX_MOUNTAIN_EID_INDEX = "Mountain_eid_Index"
FULLTEXT_INDEX_MOUNTAIN_ELEVATION_M_INDEX = "Mountain_elevation_m_Index"
FULLTEXT_INDEX_MOUNTAIN_NAME_INDEX = "Mountain_name_Index"
FULLTEXT_INDEX_MOUNTAIN_PROVENANCE_INDEX = "Mountain_provenance_Index"
FULLTEXT_INDEX_MOVIE_ALIASES_INDEX = "Movie_aliases_Index"
FULLTEXT_INDEX_MOVIE_DESCRIPTION_INDEX = "Movie_description_Index"
FULLTEXT_INDEX_MOVIE_EID_INDEX = "Movie_eid_Index"
FULLTEXT_INDEX_MOVIE_FILMING_LOCATION_INDEX = "Movie_filming_location_Index"
FULLTEXT_INDEX_MOVIE_GLOBAL_BOX_OFFICE_USD_INDEX = "Movie_global_box_office_usd_Index"
FULLTEXT_INDEX_MOVIE_NAME_INDEX = "Movie_name_Index"
FULLTEXT_INDEX_MOVIE_ORIGINAL_LANGUAGE_INDEX = "Movie_original_language_Index"
FULLTEXT_INDEX_MOVIE_PROVENANCE_INDEX = "Movie_provenance_Index"
FULLTEXT_INDEX_MOVIE_RELEASED_INDEX = "Movie_released_Index"
FULLTEXT_INDEX_MOVIE_RUNTIME_MINUTE_INDEX = "Movie_runtime_minute_Index"
FULLTEXT_INDEX_MOVIE_TAGLINE_INDEX = "Movie_tagline_Index"
FULLTEXT_INDEX_MOVIE_TAGLINE_EMBEDDING_INDEX = "Movie_tagline_embedding_Index"
FULLTEXT_INDEX_MOVIE_TITLE_INDEX = "Movie_title_Index"
FULLTEXT_INDEX_MOVIE_TITLE_EMBEDDING_INDEX = "Movie_title_embedding_Index"
FULLTEXT_INDEX_OBJECT_DESCRIPTION_INDEX = "Object_description_Index"
FULLTEXT_INDEX_OBJECT_ID_INDEX = "Object_id_Index"
FULLTEXT_INDEX_OBJECT_TYPE_INDEX = "Object_type_Index"
FULLTEXT_INDEX_OCEAN_ALIASES_INDEX = "Ocean_aliases_Index"
FULLTEXT_INDEX_OCEAN_AREA_KM2_INDEX = "Ocean_area_km2_Index"
FULLTEXT_INDEX_OCEAN_AVG_VERTICAL_DEPTH_M_INDEX = "Ocean_avg_vertical_depth_m_Index"
FULLTEXT_INDEX_OCEAN_DESCRIPTION_INDEX = "Ocean_description_Index"
FULLTEXT_INDEX_OCEAN_EID_INDEX = "Ocean_eid_Index"
FULLTEXT_INDEX_OCEAN_MAX_VERTICAL_DEPTH_M_INDEX = "Ocean_max_vertical_depth_m_Index"
FULLTEXT_INDEX_OCEAN_NAME_INDEX = "Ocean_name_Index"
FULLTEXT_INDEX_OCEAN_PROVENANCE_INDEX = "Ocean_provenance_Index"
FULLTEXT_INDEX_OFFICER_BADGE_NO_INDEX = "Officer_badge_no_Index"
FULLTEXT_INDEX_OFFICER_NAME_INDEX = "Officer_name_Index"
FULLTEXT_INDEX_OFFICER_RANK_INDEX = "Officer_rank_Index"
FULLTEXT_INDEX_OFFICER_SURNAME_INDEX = "Officer_surname_Index"
FULLTEXT_INDEX_OPERATOR_ALIASES_INDEX = "Operator_aliases_Index"
FULLTEXT_INDEX_OPERATOR_COUNTRY_INDEX = "Operator_country_Index"
FULLTEXT_INDEX_OPERATOR_DESCRIPTION_INDEX = "Operator_description_Index"
FULLTEXT_INDEX_OPERATOR_EID_INDEX = "Operator_eid_Index"
FULLTEXT_INDEX_OPERATOR_LAUNCH_YEAR_INDEX = "Operator_launch_year_Index"
FULLTEXT_INDEX_OPERATOR_NAME_INDEX = "Operator_name_Index"
FULLTEXT_INDEX_OPERATOR_PROVENANCE_INDEX = "Operator_provenance_Index"
FULLTEXT_INDEX_ORGANIZATION_ALIASES_INDEX = "Organization_aliases_Index"
FULLTEXT_INDEX_ORGANIZATION_DESCRIPTION_INDEX = "Organization_description_Index"
FULLTEXT_INDEX_ORGANIZATION_EID_INDEX = "Organization_eid_Index"
FULLTEXT_INDEX_ORGANIZATION_NAME_INDEX = "Organization_name_Index"
FULLTEXT_INDEX_ORGANIZATION_PROVENANCE_INDEX = "Organization_provenance_Index"
FULLTEXT_INDEX_PERSON_AGE_INDEX = "Person_age_Index"
FULLTEXT_INDEX_PERSON_ALIASES_INDEX = "Person_aliases_Index"
FULLTEXT_INDEX_PERSON_BORN_INDEX = "Person_born_Index"
FULLTEXT_INDEX_PERSON_COUNTRY_OF_CITIZENSHIP_INDEX = "Person_country_of_citizenship_Index"
FULLTEXT_INDEX_PERSON_DATE_OF_BIRTH_INDEX = "Person_date_of_birth_Index"
FULLTEXT_INDEX_PERSON_DATE_OF_DEATH_INDEX = "Person_date_of_death_Index"
FULLTEXT_INDEX_PERSON_DESCRIPTION_INDEX = "Person_description_Index"
FULLTEXT_INDEX_PERSON_EID_INDEX = "Person_eid_Index"
FULLTEXT_INDEX_PERSON_GENDER_INDEX = "Person_gender_Index"
FULLTEXT_INDEX_PERSON_NAME_INDEX = "Person_name_Index"
FULLTEXT_INDEX_PERSON_NAME_EMBEDDING_INDEX = "Person_name_embedding_Index"
FULLTEXT_INDEX_PERSON_NHS_NO_INDEX = "Person_nhs_no_Index"
FULLTEXT_INDEX_PERSON_PLACE_OF_BIRTH_INDEX = "Person_place_of_birth_Index"
FULLTEXT_INDEX_PERSON_PROVENANCE_INDEX = "Person_provenance_Index"
FULLTEXT_INDEX_PERSON_SURNAME_INDEX = "Person_surname_Index"
FULLTEXT_INDEX_PHONE_CALL_CALL_DATE_INDEX = "PhoneCall_call_date_Index"
FULLTEXT_INDEX_PHONE_CALL_CALL_DURATION_INDEX = "PhoneCall_call_duration_Index"
FULLTEXT_INDEX_PHONE_CALL_CALL_TIME_INDEX = "PhoneCall_call_time_Index"
FULLTEXT_INDEX_PHONE_CALL_CALL_TYPE_INDEX = "PhoneCall_call_type_Index"
FULLTEXT_INDEX_PHONE_NUMBER_PHONE_INDEX = "PhoneNumber_phone_Index"
FULLTEXT_INDEX_PHONE_NUMBER_PROVIDER_INDEX = "PhoneNumber_provider_Index"
FULLTEXT_INDEX_PHONE_NUMBER_TOUCHED_INDEX = "PhoneNumber_touched_Index"
FULLTEXT_INDEX_PHONE_PHONE_NO_INDEX = "Phone_phoneNo_Index"
FULLTEXT_INDEX_PLAYER_ALIASES_INDEX = "Player_aliases_Index"
FULLTEXT_INDEX_PLAYER_COUNTRY_OF_CITIZENSHIP_INDEX = "Player_country_of_citizenship_Index"
FULLTEXT_INDEX_PLAYER_DATE_OF_BIRTH_INDEX = "Player_date_of_birth_Index"
FULLTEXT_INDEX_PLAYER_DATE_OF_DEATH_INDEX = "Player_date_of_death_Index"
FULLTEXT_INDEX_PLAYER_DESCRIPTION_INDEX = "Player_description_Index"
FULLTEXT_INDEX_PLAYER_EID_INDEX = "Player_eid_Index"
FULLTEXT_INDEX_PLAYER_GENDER_INDEX = "Player_gender_Index"
FULLTEXT_INDEX_PLAYER_HANDEDNESS_INDEX = "Player_handedness_Index"
FULLTEXT_INDEX_PLAYER_HEIGHT_CM_INDEX = "Player_height_cm_Index"
FULLTEXT_INDEX_PLAYER_MASS_KG_INDEX = "Player_mass_kg_Index"
FULLTEXT_INDEX_PLAYER_NAME_INDEX = "Player_name_Index"
FULLTEXT_INDEX_PLAYER_NICKNAMES_INDEX = "Player_nicknames_Index"
FULLTEXT_INDEX_PLAYER_PLACE_OF_BIRTH_INDEX = "Player_place_of_birth_Index"
FULLTEXT_INDEX_PLAYER_PROVENANCE_INDEX = "Player_provenance_Index"
FULLTEXT_INDEX_PLAYER_SCHOOLS_ATTENDED_INDEX = "Player_schools_attended_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_ALIASES_INDEX = "PoliticalParty_aliases_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_DESCRIPTION_INDEX = "PoliticalParty_description_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_EID_INDEX = "PoliticalParty_eid_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_FOUNDING_DATE_INDEX = "PoliticalParty_founding_date_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_NAME_INDEX = "PoliticalParty_name_Index"
FULLTEXT_INDEX_POLITICAL_PARTY_PROVENANCE_INDEX = "PoliticalParty_provenance_Index"
FULLTEXT_INDEX_POLITICIAN_ALIASES_INDEX = "Politician_aliases_Index"
FULLTEXT_INDEX_POLITICIAN_COUNTRY_OF_CITIZENSHIP_INDEX = "Politician_country_of_citizenship_Index"
FULLTEXT_INDEX_POLITICIAN_DATE_OF_BIRTH_INDEX = "Politician_date_of_birth_Index"
FULLTEXT_INDEX_POLITICIAN_DATE_OF_DEATH_INDEX = "Politician_date_of_death_Index"
FULLTEXT_INDEX_POLITICIAN_DESCRIPTION_INDEX = "Politician_description_Index"
FULLTEXT_INDEX_POLITICIAN_EID_INDEX = "Politician_eid_Index"
FULLTEXT_INDEX_POLITICIAN_GENDER_INDEX = "Politician_gender_Index"
FULLTEXT_INDEX_POLITICIAN_NAME_INDEX = "Politician_name_Index"
FULLTEXT_INDEX_POLITICIAN_PLACE_OF_BIRTH_INDEX = "Politician_place_of_birth_Index"
FULLTEXT_INDEX_POLITICIAN_PLACE_OF_DEATH_INDEX = "Politician_place_of_death_Index"
FULLTEXT_INDEX_POLITICIAN_PROVENANCE_INDEX = "Politician_provenance_Index"
FULLTEXT_INDEX_POLITICIAN_SCHOOLS_ATTENDED_INDEX = "Politician_schools_attended_Index"
FULLTEXT_INDEX_POSITION_ALIASES_INDEX = "Position_aliases_Index"
FULLTEXT_INDEX_POSITION_DESCRIPTION_INDEX = "Position_description_Index"
FULLTEXT_INDEX_POSITION_EID_INDEX = "Position_eid_Index"
FULLTEXT_INDEX_POSITION_NAME_INDEX = "Position_name_Index"
FULLTEXT_INDEX_POSITION_PROVENANCE_INDEX = "Position_provenance_Index"
FULLTEXT_INDEX_POST_CODE_CODE_INDEX = "PostCode_code_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_ALIASES_INDEX = "ProductionCompany_aliases_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_COUNTRY_INDEX = "ProductionCompany_country_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_DESCRIPTION_INDEX = "ProductionCompany_description_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_EID_INDEX = "ProductionCompany_eid_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_NAME_INDEX = "ProductionCompany_name_Index"
FULLTEXT_INDEX_PRODUCTION_COMPANY_PROVENANCE_INDEX = "ProductionCompany_provenance_Index"
FULLTEXT_INDEX_PURCHASE_AMOUNT_INDEX = "Purchase_amount_Index"
FULLTEXT_INDEX_PURCHASE_DATE_INDEX = "Purchase_date_Index"
FULLTEXT_INDEX_PURCHASE_PURCHASE_CODE_INDEX = "Purchase_purchaseCode_Index"
FULLTEXT_INDEX_PURCHASE_TIME_INDEX = "Purchase_time_Index"
FULLTEXT_INDEX_REVIEWED_RATING_REL_INDEX = "REVIEWED_rating_RelIndex"
FULLTEXT_INDEX_REVIEWED_SUMMARY_REL_INDEX = "REVIEWED_summary_RelIndex"
FULLTEXT_INDEX_RIVER_ALIASES_INDEX = "River_aliases_Index"
FULLTEXT_INDEX_RIVER_DESCRIPTION_INDEX = "River_description_Index"
FULLTEXT_INDEX_RIVER_DISCHARGE_M3_S_INDEX = "River_discharge_m3_s_Index"
FULLTEXT_INDEX_RIVER_EID_INDEX = "River_eid_Index"
FULLTEXT_INDEX_RIVER_LENGTH_KM_INDEX = "River_length_km_Index"
FULLTEXT_INDEX_RIVER_NAME_INDEX = "River_name_Index"
FULLTEXT_INDEX_RIVER_PROVENANCE_INDEX = "River_provenance_Index"
FULLTEXT_INDEX_SSN_SSN_INDEX = "SSN_ssn_Index"
FULLTEXT_INDEX_SHOP_BUSINESS_INDEX = "Shop_business_Index"
FULLTEXT_INDEX_SHOP_NAME_INDEX = "Shop_name_Index"
FULLTEXT_INDEX_SHOP_SHOP_ID_INDEX = "Shop_shopID_Index"
FULLTEXT_INDEX_STATE_NAME_INDEX = "State_name_Index"
FULLTEXT_INDEX_TEAM_ALIASES_INDEX = "Team_aliases_Index"
FULLTEXT_INDEX_TEAM_DESCRIPTION_INDEX = "Team_description_Index"
FULLTEXT_INDEX_TEAM_EID_INDEX = "Team_eid_Index"
FULLTEXT_INDEX_TEAM_HEAD_COACH_INDEX = "Team_head_coach_Index"
FULLTEXT_INDEX_TEAM_INCEPTION_YEAR_INDEX = "Team_inception_year_Index"
FULLTEXT_INDEX_TEAM_NAME_INDEX = "Team_name_Index"
FULLTEXT_INDEX_TEAM_OWNERS_INDEX = "Team_owners_Index"
FULLTEXT_INDEX_TEAM_PROVENANCE_INDEX = "Team_provenance_Index"
FULLTEXT_INDEX_UNSECURED_LOAN_APR_INDEX = "UnsecuredLoan_APR_Index"
FULLTEXT_INDEX_UNSECURED_LOAN_ACCOUNT_NUMBER_INDEX = "UnsecuredLoan_accountNumber_Index"
FULLTEXT_INDEX_UNSECURED_LOAN_BALANCE_INDEX = "UnsecuredLoan_balance_Index"
FULLTEXT_INDEX_UNSECURED_LOAN_LOAN_AMOUNT_INDEX = "UnsecuredLoan_loanAmount_Index"
FULLTEXT_INDEX_VEHICLE_MAKE_INDEX = "Vehicle_make_Index"
FULLTEXT_INDEX_VEHICLE_MODEL_INDEX = "Vehicle_model_Index"
FULLTEXT_INDEX_VEHICLE_REG_INDEX = "Vehicle_reg_Index"
FULLTEXT_INDEX_VEHICLE_YEAR_INDEX = "Vehicle_year_Index"
FULLTEXT_INDEX_VENUE_ALIASES_INDEX = "Venue_aliases_Index"
FULLTEXT_INDEX_VENUE_DESCRIPTION_INDEX = "Venue_description_Index"
FULLTEXT_INDEX_VENUE_EID_INDEX = "Venue_eid_Index"
FULLTEXT_INDEX_VENUE_NAME_INDEX = "Venue_name_Index"
FULLTEXT_INDEX_VENUE_PROVENANCE_INDEX = "Venue_provenance_Index"
FULLTEXT_INDEX_WITH_LAST_USED_REL_INDEX = "WITH_lastUsed_RelIndex"
FULLTEXT_INDEX_WORK_ID_INDEX = "Work_id_Index"
FULLTEXT_INDEX_WORK_TITLE_INDEX = "Work_title_Index"
FULLTEXT_INDEX_WORK_YEAR_INDEX = "Work_year_Index"
FULLTEXT_INDEX_BLOOM_PERSPECTIVE__DATA_INDEX = "_Bloom_Perspective__data_Index"
FULLTEXT_INDEX_BLOOM_PERSPECTIVE__ID_INDEX = "_Bloom_Perspective__id_Index"
FULLTEXT_INDEX_BLOOM_PERSPECTIVE__NAME_INDEX = "_Bloom_Perspective__name_Index"
FULLTEXT_INDEX_BLOOM_PERSPECTIVE__ROLES_INDEX = "_Bloom_Perspective__roles_Index"
FULLTEXT_INDEX_BLOOM_PERSPECTIVE__VERSION_INDEX = "_Bloom_Perspective__version_Index"
FULLTEXT_INDEX_DRAFTED_BY_YEAR_REL_INDEX = "draftedBy_year_RelIndex"
FULLTEXT_INDEX_HAS_BOARD_MEMBER_END_YEAR_REL_INDEX = "hasBoardMember_end_year_RelIndex"
FULLTEXT_INDEX_HAS_BOARD_MEMBER_START_YEAR_REL_INDEX = "hasBoardMember_start_year_RelIndex"
FULLTEXT_INDEX_HAS_CEO_END_YEAR_REL_INDEX = "hasCEO_end_year_RelIndex"
FULLTEXT_INDEX_HAS_CEO_START_YEAR_REL_INDEX = "hasCEO_start_year_RelIndex"
FULLTEXT_INDEX_HAS_CAST_MEMBER_CHARACTER_ROLE_REL_INDEX = "hasCastMember_character_role_RelIndex"
FULLTEXT_INDEX_HAS_HEAD_OF_GOVERNMENT_END_YEAR_REL_INDEX = "hasHeadOfGovernment_end_year_RelIndex"
FULLTEXT_INDEX_HAS_HEAD_OF_GOVERNMENT_START_YEAR_REL_INDEX = "hasHeadOfGovernment_start_year_RelIndex"
FULLTEXT_INDEX_HAS_HEAD_OF_STATE_END_YEAR_REL_INDEX = "hasHeadOfState_end_year_RelIndex"
FULLTEXT_INDEX_HAS_HEAD_OF_STATE_START_YEAR_REL_INDEX = "hasHeadOfState_start_year_RelIndex"
FULLTEXT_INDEX_HAS_HOME_VENUE_END_YEAR_REL_INDEX = "hasHomeVenue_end_year_RelIndex"
FULLTEXT_INDEX_HAS_HOME_VENUE_START_YEAR_REL_INDEX = "hasHomeVenue_start_year_RelIndex"
FULLTEXT_INDEX_HEADED_BY_END_YEAR_REL_INDEX = "headedBy_end_year_RelIndex"
FULLTEXT_INDEX_HEADED_BY_START_YEAR_REL_INDEX = "headedBy_start_year_RelIndex"
FULLTEXT_INDEX_HOLDS_POSITION_END_YEAR_REL_INDEX = "holdsPosition_end_year_RelIndex"
FULLTEXT_INDEX_HOLDS_POSITION_START_YEAR_REL_INDEX = "holdsPosition_start_year_RelIndex"
FULLTEXT_INDEX_PLAYS_FOR_END_YEAR_REL_INDEX = "playsFor_end_year_RelIndex"
FULLTEXT_INDEX_PLAYS_FOR_SPORT_NUMBER_REL_INDEX = "playsFor_sport_number_RelIndex"
FULLTEXT_INDEX_PLAYS_FOR_START_YEAR_REL_INDEX = "playsFor_start_year_RelIndex"
FULLTEXT_INDEX_RECEIVES_AWARD_WINNERS_REL_INDEX = "receivesAward_winners_RelIndex"
FULLTEXT_INDEX_RECEIVES_AWARD_YEAR_REL_INDEX = "receivesAward_year_RelIndex"
FULLTEXT_INDEX_RELEASED_IN_DATE_REL_INDEX = "releasedIn_date_RelIndex"
