#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_tools.py
============
Introspects a live Neo4j database and emits two ready-to-import Python source
files containing LangChain ``@tool``-decorated functions:

  generated_node_tools.py
      One tool per (node label × property) pair.
      Each tool extracts a keyword from the user query with ``get_entity()``,
      then calls ``search_tool()`` to return canonical property values.

  generated_rel_tools.py
      • Part 1 – relationships WITH properties:
        One tool per (relationship type × property) pair.
        Calls ``search_rel_tool()`` (defined in neo4j_search.py).
      • Part 2 – structural (property-less) relationships:
        One tool per unique (rel_type, from_label, to_label) pattern.
        Calls ``search_tool()`` on the end-node's primary identifying property.

Usage
-----
  python gen_tools.py
  python gen_tools.py --node-output node_tools.py --rel-output rel_tools.py
  python gen_tools.py --database movies

Environment variables  (loaded from .env)
-----------------------------------------
  NEO4J_URI        bolt / neo4j+s URI
  NEO4J_USERNAME
  NEO4J_PASSWORD
  NEO4J_DATABASE   default: neo4j
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple, Union

from dotenv import load_dotenv
from loguru import logger
from neo4j import GraphDatabase
from neo4j.exceptions import Neo4jError

from paths import GENERATED_NODE_TOOLS, GENERATED_REL_TOOLS, SCHEMA_META

load_dotenv()

# ──────────────────────────────────────────────────────────────────────────────
# File headers written verbatim into the generated files
# ──────────────────────────────────────────────────────────────────────────────

_NODE_HEADER = '''\
# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
#
# Retrieval-mode dispatch (v1):
#   • Node value-lookup tools (this file)        → hybrid-capable.
#       The `mode` argument is left at its default so search_tool reads
#       vector_config.TOOL_RETRIEVAL_MODE at runtime. Switch the config
#       value to run "fuzzy" / "vector" / "hybrid" ablations without
#       regenerating these tools.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from agent.agent_helper import get_entity
from neo4j_lib.neo4j_search import search_tool
from config import TOOL_TOP_K


'''

_REL_HEADER = '''\
# AUTO-GENERATED by gen_tools.py — do not edit manually.
# Re-run `python gen_tools.py` to regenerate from the live Neo4j schema.
#
# Retrieval-mode dispatch (v1):
#   • Relationship-property tools (Part 1)       → fuzzy ONLY.
#       v2 extension point: vector retrieval over relationship properties
#       is deferred until the target database with rel-property semantics
#       is finalized. `mode="fuzzy"` is passed explicitly so this stays
#       fixed even if TOOL_RETRIEVAL_MODE is flipped to "hybrid" for the
#       node ablation.
#   • Structural traversal tools (Part 2)        → fuzzy ONLY (PERMANENT).
#       Structural tools follow graph paths to reach values; they are NOT
#       semantic retrieval. Mixing in a vector index over the end-node
#       label would conflate "value linking via traversal" with "value
#       linking via embedding similarity" and break tool semantics.
from __future__ import annotations
from typing import List
from langchain_core.tools import tool
from agent.agent_helper import get_entity
from neo4j_lib.neo4j_search import search_tool, search_rel_tool
from config import TOOL_TOP_K


'''


# ──────────────────────────────────────────────────────────────────────────────
# Neo4j connection helpers
# ──────────────────────────────────────────────────────────────────────────────

def _require_env(name: str) -> str:
    """Raise a clear error when a required environment variable is missing."""
    v = os.getenv(name)
    if not v:
        raise RuntimeError(
            f"Missing required environment variable: {name}. "
            "Set it in .env or your system environment."
        )
    return v


def _get_driver():
    """Build a Neo4j driver from environment variables."""
    return GraphDatabase.driver(
        _require_env("NEO4J_URI"),
        auth=(_require_env("NEO4J_USERNAME"), _require_env("NEO4J_PASSWORD")),
    )


# ──────────────────────────────────────────────────────────────────────────────
# Embedding-column filter
#
# Vector-embedding properties (e.g. ``Movie.title_embedding``) are written into
# Neo4j by ``setup_project.py`` Step 6, which means they show up in
# ``db.schema.nodeTypeProperties()`` / ``db.schema.relTypeProperties()`` like
# any other property. Without filtering they get promoted into nonsensical
# ``get_<label>_<prop>_embedding`` @tool functions that pollute the FAISS
# tool-selection index.
#
# ``_drop_embedding_pairs()`` is the single, authoritative chokepoint that
# removes them. It applies three layers of defense in priority order:
#
#   1. Type-based   — ``propertyTypes`` is a floating-point list
#                     (``LIST<FLOAT>``, ``LIST<FLOAT64>``, ``LIST<DOUBLE>``,
#                     etc.). Catches embeddings regardless of naming.
#   2. Config-based — pair is registered in
#                     ``vector_config.EMBEDDABLE_PROPERTIES``.
#   3. Naming-based — property name ends in ``_embedding`` or ``_vector``.
#                     Belt-and-braces against orphaned columns from old
#                     runs or hand-built databases.
# ──────────────────────────────────────────────────────────────────────────────

def _is_embedding_type(property_types: Optional[List[str]]) -> bool:
    """
    Return True if any element of *property_types* denotes a floating-point
    list (e.g. ``LIST<FLOAT>``, ``LIST<FLOAT64>``, ``LIST<DOUBLE>``,
    ``FloatArray``, ``DoubleArray``).

    Neo4j's ``propertyTypes`` field is a list of strings — formats vary across
    versions (4.x returns ``LIST<FLOAT>``; some drivers return ``FloatArray``)
    so this check is intentionally tolerant.
    """
    if not property_types:
        return False
    for t in property_types:
        if not t:
            continue
        tu = str(t).upper().replace(" ", "")
        if "LIST" in tu and ("FLOAT" in tu or "DOUBLE" in tu):
            return True
        if "FLOATARRAY" in tu or "DOUBLEARRAY" in tu:
            return True
    return False


def _embeddable_properties_set(entity_type: str) -> Set[Tuple[str, str]]:
    """
    Return the set of ``(label_or_reltype, embedding_property)`` pairs that
    ``vector_config.EMBEDDABLE_PROPERTIES`` registers for *entity_type*
    (``"node"`` or ``"relationship"``).

    Imported lazily so ``tools.gen_tools`` does not hard-depend on
    ``vector_config`` for callers who only need the rendering helpers.
    Returns an empty set if the import fails for any reason.
    """
    try:
        from vector_config import EMBEDDABLE_PROPERTIES  # noqa: WPS433
    except Exception:
        return set()

    out: Set[Tuple[str, str]] = set()
    for entry in EMBEDDABLE_PROPERTIES:
        if entry.get("entity_type") != entity_type:
            continue
        # Node entries use "label"; relationship entries may use "label" or
        # "rel_type". Accept both so future-proof relationship configs work.
        label = (entry.get("label")
                 or entry.get("rel_type")
                 or entry.get("relationship"))
        emb = entry.get("embedding_property")
        if label and emb:
            out.add((label, emb))
    return out


def _drop_embedding_pairs(
    triples: List[Tuple[str, str, Optional[List[str]]]],
    *,
    entity_type: str,
) -> List[Tuple[str, str]]:
    """
    Filter ``(label_or_reltype, property, propertyTypes)`` triples,
    removing any that look like a vector / embedding column.

    Uses three-layer defense in priority order: type > config > naming
    (see module-level docstring above).

    Logs every drop at INFO level with the layer that caught it, so
    ``setup_project.py`` re-runs leave a paper trail proving the filter
    fired on the expected columns.

    Returns the surviving ``(label, property)`` pairs in input order.
    """
    embeddable = _embeddable_properties_set(entity_type)
    out: List[Tuple[str, str]] = []

    for label, prop, types in triples:
        # Layer 1 — type-based (most robust, catches embeddings regardless of name)
        if _is_embedding_type(types):
            logger.info(
                f"[gen_tools] Filtered embedding column: {label}.{prop} "
                f"(reason: type={types})"
            )
            continue

        # Layer 2 — config-based (authoritative source of truth)
        if (label, prop) in embeddable:
            logger.info(
                f"[gen_tools] Filtered embedding column: {label}.{prop} "
                f"(reason: vector_config.EMBEDDABLE_PROPERTIES)"
            )
            continue

        # Layer 3 — naming-based (belt-and-braces for orphaned columns)
        lower = prop.lower()
        if lower.endswith("_embedding") or lower.endswith("_vector"):
            logger.info(
                f"[gen_tools] Filtered embedding column: {label}.{prop} "
                f"(reason: name suffix)"
            )
            continue

        out.append((label, prop))

    return out


# ──────────────────────────────────────────────────────────────────────────────
# Schema introspection
# ──────────────────────────────────────────────────────────────────────────────

def list_node_pairs(driver, database: str) -> List[Tuple[str, str]]:
    """
    Return deduplicated ``(primary_label, property_name)`` pairs for every
    node property found in the database.

    Tries ``db.schema.nodeTypeProperties()`` first (Neo4j 4.4+).
    Falls back to scanning each label's ``keys(n)`` if the procedure is
    unavailable.

    Vector/embedding columns are filtered out via :func:`_drop_embedding_pairs`
    before returning, so callers never see them. The primary path leverages
    the procedure's ``propertyTypes`` field for type-based filtering; the
    fallback path has no type info so it relies on the config and naming
    layers only.
    """
    triples: List[Tuple[str, str, Optional[List[str]]]] = []
    seen: Set[Tuple[str, str]] = set()

    with driver.session(database=database) as session:
        # ── Primary path: schema procedure ────────────────────────────────────
        try:
            records = list(session.run(
                "CALL db.schema.nodeTypeProperties() "
                "YIELD nodeType, propertyName, propertyTypes "
                "RETURN nodeType, propertyName, propertyTypes"
            ))
            for r in records:
                nt = str(r.get("nodeType") or "").strip()
                pn = str(r.get("propertyName") or "").strip()
                pts = r.get("propertyTypes")
                if not nt or not pn:
                    continue
                label = _parse_primary_label(nt)
                key = (label, pn)
                if key not in seen:
                    seen.add(key)
                    triples.append((label, pn, list(pts) if pts else None))
            return _drop_embedding_pairs(triples, entity_type="node")
        except (Neo4jError, Exception):
            pass  # fall through to scan

        # ── Fallback: scan each label ─────────────────────────────────────────
        label_rows = list(session.run("CALL db.labels() YIELD label RETURN label"))
        for lr in label_rows:
            label = str(lr.get("label") or "").strip()
            if not label:
                continue
            safe = label.replace("`", "``")
            for r in session.run(
                f"MATCH (n:`{safe}`) UNWIND keys(n) AS k RETURN DISTINCT k AS propertyName"
            ):
                pn = str(r.get("propertyName") or "").strip()
                if pn:
                    key = (label, pn)
                    if key not in seen:
                        seen.add(key)
                        # Fallback path has no propertyTypes — config &
                        # naming layers in _drop_embedding_pairs still apply.
                        triples.append((label, pn, None))

    return _drop_embedding_pairs(triples, entity_type="node")


def list_rel_property_pairs(driver, database: str) -> List[Tuple[str, str]]:
    """
    Return deduplicated ``(rel_type, property_name)`` pairs for every
    relationship property found in the database.

    Tries ``db.schema.relTypeProperties()`` first (Neo4j 4.4+).
    Falls back to scanning live relationships.

    Vector/embedding columns are filtered out via :func:`_drop_embedding_pairs`
    before returning. The demo Movies graph has no relationship-level
    embeddings today, but the moment any are added (e.g. ``ACTED_IN.summary``
    + ``ACTED_IN.summary_embedding``) this filter prevents them from being
    promoted into bogus ``get_<reltype>_<prop>_embedding`` tools.
    """
    triples: List[Tuple[str, str, Optional[List[str]]]] = []
    seen: Set[Tuple[str, str]] = set()

    with driver.session(database=database) as session:
        # ── Primary path: schema procedure ────────────────────────────────────
        try:
            records = list(session.run(
                "CALL db.schema.relTypeProperties() "
                "YIELD relType, propertyName, propertyTypes "
                "WHERE propertyName IS NOT NULL "
                "RETURN relType, propertyName, propertyTypes"
            ))
            for r in records:
                # relType may arrive as `:`ACTED_IN`` — clean it unconditionally
                rt = _clean_rel_type(str(r.get("relType") or ""))
                pn = str(r.get("propertyName") or "").strip()
                pts = r.get("propertyTypes")
                if not rt or not pn:
                    continue
                key = (rt, pn)
                if key not in seen:
                    seen.add(key)
                    triples.append((rt, pn, list(pts) if pts else None))
            return _drop_embedding_pairs(triples, entity_type="relationship")
        except (Neo4jError, Exception):
            pass  # fall through to scan

        # ── Fallback: scan live relationship keys ─────────────────────────────
        for r in session.run(
            "MATCH ()-[r]->() "
            "WHERE size(keys(r)) > 0 "
            "UNWIND keys(r) AS k "
            "RETURN DISTINCT type(r) AS relType, k AS propertyName "
            "ORDER BY relType, k"
        ):
            rt = _clean_rel_type(str(r.get("relType") or ""))
            pn = str(r.get("propertyName") or "").strip()
            if rt and pn:
                key = (rt, pn)
                if key not in seen:
                    seen.add(key)
                    # Fallback path has no propertyTypes — config &
                    # naming layers in _drop_embedding_pairs still apply.
                    triples.append((rt, pn, None))

    return _drop_embedding_pairs(triples, entity_type="relationship")


def list_structural_relations(driver, database: str) -> List[Tuple[str, str, str]]:
    """
    Return deduplicated ``(rel_type, from_label, to_label)`` triples for every
    unique relationship pattern in the database (including those with properties).

    The caller is responsible for filtering out rel types that already have
    property-specific tools in Part 1.
    """
    patterns: List[Tuple[str, str, str]] = []
    seen: Set[Tuple[str, str, str]] = set()

    with driver.session(database=database) as session:
        for r in session.run(
            "MATCH (a)-[r]->(b) "
            "RETURN DISTINCT type(r) AS relType, "
            "head(labels(a)) AS fromLabel, "
            "head(labels(b)) AS toLabel "
            "ORDER BY relType"
        ):
            rt = _clean_rel_type(str(r.get("relType") or ""))
            fl = str(r.get("fromLabel") or "").strip()
            tl = str(r.get("toLabel") or "").strip()
            if rt and fl and tl:
                key = (rt, fl, tl)
                if key not in seen:
                    seen.add(key)
                    patterns.append(key)

    return patterns


# ──────────────────────────────────────────────────────────────────────────────
# Naming helpers
# ──────────────────────────────────────────────────────────────────────────────

def _parse_primary_label(node_type: str) -> str:
    """
    Extract the primary label from a nodeType string, stripping any
    backtick quoting that Neo4j may include.

    Examples::

        ':Movie'           → 'Movie'
        ':`Movie`'         → 'Movie'
        ':Person:Employee' → 'Person'   (first label)
        'Movie'            → 'Movie'    (bare label, no colon prefix)
    """
    if node_type.startswith(":"):
        parts = [p.strip().strip("`") for p in node_type.split(":") if p.strip()]
        return parts[0] if parts else node_type.strip("`")
    return node_type.strip("`")


def _camel_to_snake(name: str) -> str:
    """
    Convert CamelCase (or mixedCase) to snake_case.

    Examples::

        'JobPosting' → 'job_posting'
        'tagline'    → 'tagline'
        'firstName'  → 'first_name'
    """
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def _safe_ident(s: str) -> str:
    """
    Replace every non-alphanumeric character with ``_``, collapse runs,
    strip leading/trailing underscores, and lower-case.
    """
    s = re.sub(r"[^a-zA-Z0-9]", "_", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_").lower()


def _label_snake(label: str) -> str:
    """Convert a node label to a snake_case identifier fragment."""
    return _camel_to_snake(_safe_ident(label))


def _clean_rel_type(raw: str) -> str:
    """
    Strip Neo4j formatting artefacts from a relationship type string.

    Neo4j's ``db.schema.relTypeProperties()`` may return the type wrapped in
    backticks and prefixed with a colon, e.g. `` :`ACTED_IN` ``.
    This helper normalises all variants to the bare type name, e.g. ``ACTED_IN``.
    """
    s = raw.strip()           # remove surrounding whitespace
    s = s.strip("`")          # remove wrapping backticks
    s = s.lstrip(":")         # remove leading colon (`:ACTED_IN` → `ACTED_IN`)
    s = s.strip("`")          # remove any remaining inner backticks
    return s


def _rel_snake(rel_type: str) -> str:
    """
    Convert a relationship type (ALL_CAPS, possibly prefixed with ``:`` or
    wrapped in backticks) to a safe snake_case Python identifier fragment.

    Examples::

        'ACTED_IN'        → 'acted_in'
        ':ACTED_IN'       → 'acted_in'
        ':`ACTED_IN`'     → 'acted_in'
        'HAS_WORKED_FOR'  → 'has_worked_for'
    """
    return _safe_ident(_clean_rel_type(rel_type))


def _prop_snake(prop: str) -> str:
    """Convert a property name to snake_case."""
    return _camel_to_snake(prop)


def _unique_name(base: str, seen: Set[str]) -> str:
    """
    Return *base* if not already taken; otherwise append ``_2``, ``_3`` …
    Mutates *seen* by adding the returned name.
    """
    name = base
    counter = 2
    while name in seen:
        name = f"{base}_{counter}"
        counter += 1
    seen.add(name)
    return name


# ──────────────────────────────────────────────────────────────────────────────
# Topic string helpers (feed into get_entity's `topic` argument)
# ──────────────────────────────────────────────────────────────────────────────

# Properties whose names benefit from a clarifying suffix in the topic string.
_PROP_TOPIC_SUFFIX: Dict[str, str] = {
    "released": "year",
    "born":     "year",
    "year":     "year",
    "date":     "date",
    "id":       "ID",
    "rating":   "rating",
    "score":    "score",
}


def _node_topic(label: str, prop: str) -> str:
    """Human-readable topic for a node property search."""
    # schema_meta.json (authoritative when available)
    topic = (_schema_meta.get("nodes", {})
             .get(label, {}).get("properties", {})
             .get(prop, {}).get("topic"))
    if topic:
        return topic
    # Fallback: heuristic
    suffix = _PROP_TOPIC_SUFFIX.get(prop.lower(), "")
    base = f"{label} {prop}"
    return f"{base} {suffix}".strip() if suffix else base


def _rel_prop_topic(rel_type: str, prop: str) -> str:
    """Human-readable topic for a relationship property search."""
    # schema_meta.json (authoritative when available)
    topic = (_schema_meta.get("relationships", {})
             .get(rel_type, {}).get("properties", {})
             .get(prop, {}).get("topic"))
    if topic:
        return topic
    # Fallback: heuristic
    return f"{prop} in {rel_type} relationship"


def _structural_rel_topic(rel_type: str, to_label: str, end_prop: str) -> str:
    """Human-readable topic for a structural (property-less) relationship tool."""
    # schema_meta.json — look up the end-node's property topic
    topic = (_schema_meta.get("nodes", {})
             .get(to_label, {}).get("properties", {})
             .get(end_prop, {}).get("topic"))
    if topic:
        return f"{topic} in {rel_type} relationship"
    # Fallback: heuristic
    return f"{to_label.lower()} {end_prop} in {rel_type} relationship"


def _load_schema_meta(path: Union[str, Path] = SCHEMA_META) -> Dict[str, Any]:
    """
    Load ``schema_meta.json`` if it exists.  Returns an empty dict on any
    failure so callers can fall back gracefully.
    """
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}


# Module-level cache — populated once by main() or generate_rel_tools_file().
_schema_meta: Dict[str, Any] = {}


def _guess_id_property(label: str) -> str:
    """
    Pick the primary identifying property for a node label.

    Resolution order:
      1. ``schema_meta.json``  →  ``nodes.<label>.id_property``
      2. English-name heuristic  →  ``"title"`` for media-like labels,
         ``"name"`` otherwise.
    """
    # ── 1. schema_meta.json (authoritative when available) ────────────────
    nodes_meta = _schema_meta.get("nodes", {})
    label_meta = nodes_meta.get(label, {})
    id_prop = label_meta.get("id_property")
    if id_prop:
        return id_prop

    # ── 2. English-name fallback ─────────────────────────────────────────
    lower = label.lower()
    if any(kw in lower for kw in ("movie", "film", "book", "song", "album",
                                   "article", "post", "product", "item")):
        return "title"
    return "name"


# ──────────────────────────────────────────────────────────────────────────────
# Code-rendering helpers — each returns a complete function block as a string
# ──────────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────────
# Tool-description helpers
#
# The tool docstring IS the retrieval signal — FAISS embeds it and the ReAct
# agent reads it to decide which tool to call. Two failure modes observed on
# the cypherbench_augmented__movie partial-name probe motivate the
# property-class branching and relational-hint injection below:
#
#   Bug #2 (`*_eid` vs `*_name` conflation):
#     The legacy docstring was identical across machine-ID properties (eid,
#     uuid, ...) and human-readable name properties (name, title, ...).
#     FAISS could not separate them, so the agent picked `get_award_eid`
#     when the question said "Award for Best Foreign Feature Film" — a
#     human-readable name. Fix: branch the docstring template by
#     `data_type` from `schema_meta.json` (ID props get a restrictive
#     "ONLY for literal Q-IDs / UUIDs" line; name props get an inclusive
#     "primary entity-name tool" line).
#
#   Bug #1 (Person tool missing from top-K when question is relational):
#     The agent saw "feature Elijah Wood in cast" and FAISS returned
#     movie/award/filmseries tools, with no Person tool in the top-10.
#     Person.name's docstring mentioned only "person's name" — nothing
#     about "cast member", "starring", "directed by", etc. Fix: derive
#     relational verb forms from `structural_relations` (e.g. the rel
#     `(:Movie)-[:hasCastMember]->(:Person)` yields the English hint
#     "has cast member <name>") and inject them into the docstrings of
#     name-class properties for labels that participate in those rels.
# ──────────────────────────────────────────────────────────────────────────────

# Property names that strictly identify a machine identifier. The agent
# should ONLY call these when the question contains a verbatim ID token.
_MACHINE_ID_PROP_NAMES = frozenset({
    "eid", "id", "uuid", "qid", "wid", "wikidata_id", "wikidata", "wikidataid",
    "freebase_id", "freebaseid", "imdb_id", "imdbid", "tmdb_id", "tmdbid",
    "isbn", "issn", "doi", "orcid", "uri", "url",
})

# Property names that hold a human-readable display name. These are the
# PRIMARY entity-resolution channel — the agent should default to these
# whenever a question references an entity by name.
_NAME_PROP_NAMES = frozenset({
    "name", "title", "label", "fullname", "full_name", "displayname",
    "display_name",
})

# Property names that hold long descriptive text. The agent should pick
# these when the question paraphrases content rather than naming entities.
_DESCRIPTION_PROP_NAMES = frozenset({
    "description", "summary", "biography", "bio", "plot", "synopsis",
    "overview", "abstract", "content",
})


def _indef_article(noun: str) -> str:
    """
    Return ``"a"`` or ``"an"`` for *noun* (the bare noun, no leading
    article).  Heuristic by first letter — good enough for the labels
    we see in practice (Movie, Person, Award, Country, Genre, FilmSeries,
    ProductionCompany, Award, Date, …). The function only needs to be
    right for the docstrings we render — those strings are mostly read
    by FAISS embedding (which is article-insensitive) and a human
    reviewer, so we accept the well-known h-silent edge cases
    ("an hour") that this heuristic mishandles.
    """
    if not noun:
        return "a"
    return "an" if noun[0].lower() in "aeiou" else "a"


def _classify_property(label: str, prop: str) -> str:
    """
    Return the property class — drives the docstring template inside
    :func:`_render_node_tool`.

    Resolution order:
      1. `schema_meta.json` `data_type` (authoritative when present —
         `setup_project.py` step 5 fills this in by inspecting actual
         property values, so it's strictly better than name heuristics).
      2. Property-name match against the frozensets above.
      3. Suffix heuristic for unrecognised `*_id` / `*_eid` / `*_uuid`.
      4. Fallback: `"other"`.

    Returns one of: ``"id"`` | ``"name"`` | ``"description"`` | ``"other"``.
    """
    # ── 1. schema_meta.json data_type ────────────────────────────────────────
    dtype = (
        _schema_meta.get("nodes", {})
        .get(label, {})
        .get("properties", {})
        .get(prop, {})
        .get("data_type")
    )
    if dtype:
        dt = str(dtype).strip().lower()
        if dt in ("id", "identifier", "external_id"):
            return "id"
        if dt in ("name", "title", "label"):
            return "name"
        if dt in ("text", "description", "summary"):
            return "description"

    # ── 2. Property-name match ───────────────────────────────────────────────
    p = prop.lower()
    if p in _MACHINE_ID_PROP_NAMES:
        return "id"
    if p in _NAME_PROP_NAMES:
        return "name"
    if p in _DESCRIPTION_PROP_NAMES:
        return "description"

    # ── 3. Suffix heuristic for unrecognised ID-shaped names ─────────────────
    if p.endswith("_id") or p.endswith("_eid") or p.endswith("_uuid"):
        return "id"

    # ── 4. Fallback ──────────────────────────────────────────────────────────
    return "other"


# CamelCase / mixedCase → space-separated lowercase words. Used to turn
# Neo4j relationship type names into English verb forms for relational
# hint injection. Examples:
#     'hasCastMember' → 'has cast member'
#     'directedBy'    → 'directed by'
#     'releasedIn'    → 'released in'
#     'partOfSeries'  → 'part of series'
def _camel_to_english(name: str) -> str:
    """CamelCase / mixedCase → English-style 'has cast member', 'directed by'."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", s)
    # Also split SNAKE_CASE / kebab-case
    s = s.replace("_", " ").replace("-", " ")
    return " ".join(s.split()).lower()


def _relational_hint(
    label: str,
    structural_relations: List[Tuple[str, str, str]],
) -> str:
    """
    Build an English-verb hint string for *label* by inspecting which
    relationships connect TO or FROM it.

    Example, for ``label = "Person"`` and a movie graph with::

        (:Movie)-[:hasCastMember]->(:Person)
        (:Movie)-[:directedBy]->(:Person)
        (:Movie)-[:writtenBy]->(:Person)

    we return::

        "Often invoked via relational phrasings like 'has cast member X', "
        "'directed by X', 'written by X' — call this tool whenever the "
        "question references a person through such a phrasing, not only "
        "when it literally says the word 'person'."

    Returns an empty string when *label* participates in no structural
    relations (e.g. an isolated node label), so the caller can append
    the hint unconditionally without a branch.

    Implementation notes
    --------------------
    * Only relations where *label* appears as `from_label` OR `to_label`
      are considered; we do not include self-edges twice.
    * The relation type itself is camelCase → English-verbalised
      (`hasCastMember` → `has cast member`). This works because Neo4j
      conventions for the movie / cypherbench graphs already encode the
      verb in the relation name; no NLP model is required.
    * Hints are deduplicated and capped at the first 6 distinct verb
      forms — more than that produces noisy embeddings that hurt FAISS
      ranking more than they help.
    """
    if not structural_relations:
        return ""

    verbs: List[str] = []
    seen: Set[str] = set()
    for rt, fl, tl in structural_relations:
        if fl != label and tl != label:
            continue
        verb = _camel_to_english(rt)
        if not verb or verb in seen:
            continue
        seen.add(verb)
        verbs.append(verb)
        if len(verbs) >= 6:
            break

    if not verbs:
        return ""

    quoted = ", ".join(f"'{v} X'" for v in verbs)
    label_low = label.lower()
    art       = _indef_article(label_low)
    return (
        f" Often invoked via relational phrasings like {quoted} — "
        f"call this tool whenever the question references {art} "
        f"{label_low} through such a phrasing, not only when it "
        f"literally says the word '{label_low}'."
    )


def _render_node_tool(
    func_name: str,
    label: str,
    prop: str,
    structural_relations: Optional[List[Tuple[str, str, str]]] = None,
) -> str:
    """
    Render a single node @tool function — HYBRID-CAPABLE.

    Retrieval mode is intentionally NOT pinned here. `search_tool`
    reads `vector_config.TOOL_RETRIEVAL_MODE` at call time when `mode`
    is omitted, so flipping the config value runs the
    fuzzy/vector/hybrid ablation without regenerating these tools.

    Docstring template
    ------------------
    The docstring IS the retrieval signal — FAISS embeds it and the
    ReAct agent reads it to decide WHEN to call this tool. We pick the
    template based on the property class returned by
    :func:`_classify_property`:

    * **id** props (eid, uuid, …)  — restrictive: "ONLY when the
      question contains a literal machine identifier". This pushes
      `get_<label>_name` ahead of `get_<label>_eid` when the question
      mentions a human-readable entity, which is the common case.

    * **name** props (name, title, …)  — inclusive: "PRIMARY tool for
      resolving <label> entities", PLUS a relational-hint clause built
      from ``structural_relations`` so phrasings like
      "feature X in cast" / "directed by X" / "released in X" recall
      the right name-lookup tool.

    * **description** props (description, summary, …)  — paraphrase
      mode: "Call when the question paraphrases content".

    * **other** (years, ratings, structural codes, …)  — the legacy
      "lowercase/abbreviated/partial mentions" template, unchanged.

    The phrase ``"canonical {label}.{prop} values"`` is preserved
    verbatim in every branch so the regex parser in
    ``schema.gen_system_prompt._RE_NODE_DESC`` continues to capture
    (label, prop) for the NER prompt's tool-list section.
    """
    topic     = _node_topic(label, prop)
    klass     = _classify_property(label, prop)
    label_low = label.lower()
    art       = _indef_article(label_low)         # "a" / "an"

    if klass == "id":
        # ID props: restrict invocation to literal machine-identifier mentions.
        doc = (
            f"Look up canonical {label}.{prop} values. "
            f"ONLY call this when the question contains a literal machine "
            f"identifier (e.g. a Wikidata 'Q12345' / 'wd:Q12345' code, an "
            f"IMDb 'tt0000000' code, a UUID, or a similar opaque ID string) "
            f"that refers to {art} {label_low}. "
            f"NEVER call this for human-readable {label_low} names — use "
            f"the corresponding name lookup tool (get_{_label_snake(label)}_name "
            f"if present) instead."
        )
    elif klass == "name":
        # Name props: this is the PRIMARY entity-resolution channel.
        # Inject relational hint built from structural_relations so the
        # tool is discoverable via phrasings that don't literally say
        # "<label> name" (e.g. "has cast member X" → Person.name).
        rel_hint = _relational_hint(label, structural_relations or [])
        doc = (
            f"Look up canonical {label}.{prop} values. "
            f"This is the PRIMARY tool for resolving {art} {label_low} entity "
            f"by name. Call this whenever the question references {art} "
            f"{label_low} BY NAME \u2014 including lowercase, abbreviated, "
            f"partial, paraphrased, or possessive mentions "
            f"(e.g. 'matrix' \u2192 'The Matrix', "
            f"'Foreign Feature Film' \u2192 "
            f"'Amanda Award for Best Foreign Feature Film')."
            f"{rel_hint} "
            f"When in doubt between this and a *_eid tool, prefer this one."
        )
    elif klass == "description":
        # Description props: paraphrase-friendly free-text.
        doc = (
            f"Look up canonical {label}.{prop} values. "
            f"Call this when the question paraphrases or summarises the "
            f"{label_low}'s content (themes, topics, plot points, "
            f"biographical details) rather than naming it directly. "
            f"For name-based references, prefer the name-lookup tool "
            f"(get_{_label_snake(label)}_name if present) instead."
        )
    else:
        # Other props (years, ratings, structural codes, …): legacy template.
        doc = (
            f"Look up canonical {label}.{prop} values. "
            f"Call this whenever the question mentions a {label_low}'s "
            f"{prop} \u2014 including lowercase, abbreviated, or partial "
            f"mentions (e.g. 'matrix' \u2192 'The Matrix'). When in doubt, "
            f"call it."
        )

    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    # Retrieval mode resolved at call time from '
        f'vector_config.TOOL_RETRIEVAL_MODE.\n'
        f'    return search_tool(phrase=search_term, node_label="{label}", '
        f'property_name="{prop}", k=TOOL_TOP_K, verbose=True)\n'
    )


def _render_rel_property_tool(func_name: str, rel_type: str, prop: str) -> str:
    """
    Render a relationship-property @tool function — FUZZY-ONLY (v1).

    `mode="fuzzy"` is pinned explicitly so this stays on the legacy path
    even when `TOOL_RETRIEVAL_MODE` is flipped to "hybrid" for the
    node ablation.

    v2 extension point: when relationship-property vector retrieval lands,
    drop the explicit `mode="fuzzy"` and let it default to the config
    switch (same pattern as the node tool above)::

        @tool
        def get_acted_in_roles(user_query: str) -> List[str]:
            \"\"\"Get the canonical ACTED_IN.roles values from the database.\"\"\"
            search_term = get_entity(user_query, topic="character names")
            return search_rel_tool(phrase=search_term, rel_type="ACTED_IN",
                                   property_name="roles", k=TOOL_TOP_K,
                                   verbose=True, mode="fuzzy")
    """
    topic = _rel_prop_topic(rel_type, prop)
    # Action-oriented docstring (see _render_node_tool for rationale).
    # The "canonical {RelType}.{prop} values" phrase is preserved so that
    # ``schema.gen_system_prompt._RE_REL_PROP`` keeps matching this format
    # via .search() (the rel-type's all-caps anchor still distinguishes
    # rel-property descriptions from node-property descriptions).
    doc = (
        f"Look up canonical {rel_type}.{prop} values. "
        f"Call this whenever the question mentions a {prop} value associated "
        f"with a {rel_type.lower()} relationship. When in doubt, call it."
    )
    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    # v1: relationship-property retrieval is fuzzy-only.\n'
        f'    # TODO(v2): drop mode="fuzzy" once rel-property vector indexes ship.\n'
        f'    return search_rel_tool(phrase=search_term, rel_type="{rel_type}", '
        f'property_name="{prop}", k=TOOL_TOP_K, verbose=True, mode="fuzzy")\n'
    )


def _render_structural_rel_tool(
    func_name: str,
    rel_type: str,
    from_label: str,
    to_label: str,
) -> str:
    """
    Render a structural (property-less) relationship @tool function —
    FUZZY-ONLY (PERMANENT).

    Structural traversal tools follow graph paths to reach values; they
    are NOT semantic retrieval. Mixing in a vector index over the
    end-node label would conflate two distinct retrieval semantics and
    break the agent's tool-selection signal. `mode="fuzzy"` is pinned
    permanently — no v2 extension point here.

    Searches the end-node's primary identifying property so the agent
    can resolve canonical values for Cypher WHERE clauses::

        @tool
        def get_directed_relation(user_query: str) -> List[str]:
            \"\"\"Find Movie.title values reachable via
            (:Person)-[:DIRECTED]->(:Movie) in the database.\"\"\"
            search_term = get_entity(user_query, topic="movie title in DIRECTED relationship")
            return search_tool(phrase=search_term, node_label="Movie",
                               property_name="title", k=TOOL_TOP_K,
                               verbose=True, mode="fuzzy")
    """
    end_prop = _guess_id_property(to_label)
    topic    = _structural_rel_topic(rel_type, to_label, end_prop)
    # Action-oriented docstring.  The full graph-pattern notation
    # ``(:From)-[:Rel]->(:To)`` is preserved so the regex parser in
    # ``schema.gen_system_prompt._RE_STRUCTURAL`` continues to capture
    # (to_label, end_prop, from_label, rel_type, to_label).  The trailing
    # action prose is what the NER agent reads to decide WHEN to call.
    doc = (
        f"Find {to_label}.{end_prop} values reachable via "
        f"(:{from_label})-[:{rel_type}]->(:{to_label}). "
        f"Call this when the question references a {to_label.lower()}'s "
        f"{end_prop} that may be related to a {from_label.lower()}, "
        f"including partial or informal mentions. When in doubt, call it."
    )
    return (
        f"@tool\n"
        f"def {func_name}(user_query: str) -> List[str]:\n"
        f'    """{doc}"""\n'
        f'    search_term = get_entity(user_query, topic="{topic}")\n'
        f'    # PERMANENT: structural traversal tools are not semantic retrieval.\n'
        f'    # mode="fuzzy" is intentional and must NOT be removed.\n'
        f'    return search_tool(phrase=search_term, node_label="{to_label}", '
        f'property_name="{end_prop}", k=TOOL_TOP_K, verbose=True, mode="fuzzy")\n'
    )


# ──────────────────────────────────────────────────────────────────────────────
# File generators
# ──────────────────────────────────────────────────────────────────────────────

def generate_node_tools_file(
    node_pairs: List[Tuple[str, str]],
    output_path: Union[str, Path],
    meta_path: Union[str, Path] = SCHEMA_META,
    structural_relations: Optional[List[Tuple[str, str, str]]] = None,
) -> int:
    """
    Write ``generated_node_tools.py``.

    When *meta_path* points to a valid ``schema_meta.json``, topics for each
    node property are read from it instead of inferred by heuristic.

    *structural_relations* (optional) carries the
    ``(rel_type, from_label, to_label)`` triples from
    :func:`list_structural_relations`. When supplied, name-class
    docstrings receive relational-hint clauses derived from these
    triples (e.g. Person.name picks up "has cast member X / directed by
    X / written by X"), which fixes the
    "tool buried below top-K when question is relational" failure mode
    observed on the partial-name probe. Caller is expected to pass it;
    defaulting to ``None`` keeps the legacy contract for any external
    importer of this function.

    Returns the number of @tool functions written.
    """
    global _schema_meta
    if not _schema_meta:
        _schema_meta = _load_schema_meta(meta_path)

    seen_names: Set[str] = set()
    blocks: List[str] = []

    for label, prop in node_pairs:
        base      = f"get_{_label_snake(label)}_{_prop_snake(prop)}"
        func_name = _unique_name(base, seen_names)
        blocks.append(_render_node_tool(
            func_name, label, prop,
            structural_relations=structural_relations,
        ))

    content = _NODE_HEADER + "\n\n".join(blocks) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    return len(blocks)


def generate_rel_tools_file(
    rel_prop_pairs: List[Tuple[str, str]],
    structural_relations: List[Tuple[str, str, str]],
    output_path: Union[str, Path],
    meta_path: Union[str, Path] = SCHEMA_META,
) -> int:
    """
    Write ``generated_rel_tools.py``.

    The file has two clearly separated sections:

    * **Part 1** – relationship property tools (``search_rel_tool``).
    * **Part 2** – structural traversal tools for property-less relationships
      (``search_tool`` on the end node).

    When *meta_path* points to a valid ``schema_meta.json``, the
    ``id_property`` for each label is read from it instead of guessed.

    Returns the total number of @tool functions written.
    """
    global _schema_meta
    if not _schema_meta:
        _schema_meta = _load_schema_meta(meta_path)
    seen_names: Set[str] = set()
    blocks: List[str]    = []

    # ── Part 1: relationship property tools ───────────────────────────────────
    if rel_prop_pairs:
        blocks.append(
            "# " + "─" * 72 + "\n"
            "# Part 1 — Relationship PROPERTY tools\n"
            "#          Search canonical values stored on relationship objects.\n"
            "# " + "─" * 72
        )
        for rel_type, prop in rel_prop_pairs:
            base      = f"get_{_rel_snake(rel_type)}_{_prop_snake(prop)}"
            func_name = _unique_name(base, seen_names)
            blocks.append(_render_rel_property_tool(func_name, rel_type, prop))

    # ── Part 2: structural (property-less) relationship tools ─────────────────
    # Exclude rel types that already have dedicated property tools above.
    rels_with_props: Set[str] = {rt for rt, _ in rel_prop_pairs}
    pure_structural = [
        (rt, fl, tl)
        for rt, fl, tl in structural_relations
        if rt not in rels_with_props
    ]

    if pure_structural:
        blocks.append(
            "\n\n# " + "─" * 72 + "\n"
            "# Part 2 — Structural TRAVERSAL tools\n"
            "#          No properties on the relationship itself; searches the\n"
            "#          end-node's primary identifying property instead.\n"
            "# " + "─" * 72
        )
        for rel_type, from_label, to_label in pure_structural:
            base      = f"get_{_rel_snake(rel_type)}_relation"
            func_name = _unique_name(base, seen_names)
            blocks.append(
                _render_structural_rel_tool(func_name, rel_type, from_label, to_label)
            )

    content = _REL_HEADER + "\n\n".join(blocks) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    # Count only @tool blocks (skip comment-only separator blocks)
    return sum(1 for b in blocks if b.startswith("@tool"))


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Generate LangChain @tool functions from a Neo4j schema "
            "into two Python files."
        )
    )
    p.add_argument(
        "--node-output",
        default=str(GENERATED_NODE_TOOLS),
        metavar="PATH",
        help=f"Output path for node tools (default: {GENERATED_NODE_TOOLS})",
    )
    p.add_argument(
        "--rel-output",
        default=str(GENERATED_REL_TOOLS),
        metavar="PATH",
        help=f"Output path for relation tools (default: {GENERATED_REL_TOOLS})",
    )
    p.add_argument(
        "--database",
        default=os.getenv("NEO4J_DATABASE", "neo4j"),
        metavar="DB",
        help="Neo4j database name (default: $NEO4J_DATABASE or 'neo4j')",
    )
    p.add_argument(
        "--meta",
        default=str(SCHEMA_META),
        metavar="PATH",
        help=f"Path to schema_meta.json (default: {SCHEMA_META})",
    )
    return p.parse_args()


def main() -> None:
    global _schema_meta
    args = _parse_args()

    # Load schema_meta.json so _guess_id_property() can use id_property
    _schema_meta = _load_schema_meta(args.meta)
    if _schema_meta:
        labels = list(_schema_meta.get("nodes", {}).keys())
        print(f"Loaded schema_meta.json  (labels: {labels})", flush=True)
    else:
        print("No schema_meta.json found — using heuristic id_property guessing.", flush=True)

    print("Connecting to Neo4j …", flush=True)
    driver = _get_driver()

    try:
        db = args.database
        print(f"Introspecting schema  (database={db!r}) …", flush=True)

        node_pairs       = list_node_pairs(driver, db)
        rel_prop_pairs   = list_rel_property_pairs(driver, db)
        structural_rels  = list_structural_relations(driver, db)

    finally:
        driver.close()

    print(
        f"  {len(node_pairs):>3d}  node (label, property) pairs\n"
        f"  {len(rel_prop_pairs):>3d}  relationship property pairs\n"
        f"  {len(structural_rels):>3d}  unique relationship patterns",
        flush=True,
    )

    # Pass structural_rels into the node generator so name-class docstrings
    # get relational-hint clauses ("has cast member X", "directed by X", ...)
    # derived from the graph's actual rel patterns. This is what makes
    # Person.name discoverable when the question uses relational phrasings
    # — see _render_node_tool for the failure mode being patched.
    n_node = generate_node_tools_file(
        node_pairs, args.node_output,
        structural_relations=structural_rels,
    )
    print(f"\n✓  {n_node:>3d} node tools  →  {args.node_output}", flush=True)

    n_rel = generate_rel_tools_file(rel_prop_pairs, structural_rels, args.rel_output)
    print(f"✓  {n_rel:>3d} rel  tools  →  {args.rel_output}", flush=True)


if __name__ == "__main__":
    main()
